/**
 * Seed topics for Anime & Manga, Comics, Video Games, Technology, Programming
 * Using EXISTING subcategory slugs from the database
 */

import { ensureTopic, getTopics, initRegistry } from '../src/lib/registry';

initRegistry();

const categories = ['anime-manga', 'comics', 'video-games', 'technology', 'programming'];
const existingTopics = categories.flatMap(c => getTopics(c));
const existingSlugs = new Set(existingTopics.map(t => t.slug));

const topics: Record<string, Record<string, Array<{ name: string; slug: string }>>> = {
  'anime-manga': {
    'shonen': [
      { name: "Dragon Ball", slug: "dragon-ball" },
      { name: "Naruto", slug: "naruto" },
      { name: "One Piece", slug: "one-piece" },
      { name: "Bleach", slug: "bleach" },
      { name: "My Hero Academia", slug: "my-hero-academia" },
      { name: "Demon Slayer", slug: "demon-slayer" },
      { name: "Jujutsu Kaisen", slug: "jujutsu-kaisen" },
      { name: "Attack on Titan", slug: "attack-on-titan" },
      { name: "Hunter x Hunter", slug: "hunter-x-hunter" },
      { name: "Fullmetal Alchemist", slug: "fullmetal-alchemist" },
      { name: "Black Clover", slug: "black-clover" },
      { name: "Yu Yu Hakusho", slug: "yu-yu-hakusho" },
      { name: "Chainsaw Man", slug: "chainsaw-man" },
      { name: "Death Note", slug: "death-note" },
      { name: "One Punch Man", slug: "one-punch-man" },
    ],
    'seinen': [
      { name: "Berserk", slug: "berserk" },
      { name: "Vinland Saga", slug: "vinland-saga" },
      { name: "Tokyo Ghoul", slug: "tokyo-ghoul" },
      { name: "Parasyte", slug: "parasyte" },
      { name: "Monster", slug: "monster-anime" },
      { name: "Akira", slug: "akira" },
      { name: "Ghost in the Shell", slug: "ghost-in-the-shell" },
      { name: "Cowboy Bebop", slug: "cowboy-bebop" },
      { name: "Steins;Gate", slug: "steins-gate" },
      { name: "Psycho-Pass", slug: "psycho-pass" },
      { name: "Hellsing", slug: "hellsing" },
      { name: "Gantz", slug: "gantz" },
    ],
    'shojo': [
      { name: "Sailor Moon", slug: "sailor-moon" },
      { name: "Cardcaptor Sakura", slug: "cardcaptor-sakura" },
      { name: "Fruits Basket", slug: "fruits-basket" },
      { name: "Ouran High School Host Club", slug: "ouran-host-club" },
      { name: "Nana", slug: "nana-anime" },
      { name: "Vampire Knight", slug: "vampire-knight" },
      { name: "Kimi ni Todoke", slug: "kimi-ni-todoke" },
      { name: "Skip Beat!", slug: "skip-beat" },
      { name: "Lovely Complex", slug: "lovely-complex" },
      { name: "Revolutionary Girl Utena", slug: "utena" },
    ],
    'mecha': [
      { name: "Mobile Suit Gundam", slug: "gundam" },
      { name: "Neon Genesis Evangelion", slug: "evangelion" },
      { name: "Code Geass", slug: "code-geass" },
      { name: "Macross", slug: "macross" },
      { name: "Gurren Lagann", slug: "gurren-lagann" },
      { name: "Voltron", slug: "voltron" },
      { name: "Full Metal Panic!", slug: "full-metal-panic" },
      { name: "Eureka Seven", slug: "eureka-seven" },
      { name: "Darling in the Franxx", slug: "darling-in-franxx" },
      { name: "86", slug: "86-anime" },
    ],
    'isekai': [
      { name: "Sword Art Online", slug: "sword-art-online" },
      { name: "Re:Zero", slug: "re-zero" },
      { name: "Konosuba", slug: "konosuba" },
      { name: "That Time I Got Reincarnated as a Slime", slug: "slime-isekai" },
      { name: "Overlord", slug: "overlord-anime" },
      { name: "Rising of the Shield Hero", slug: "shield-hero" },
      { name: "No Game No Life", slug: "no-game-no-life" },
      { name: "The Saga of Tanya the Evil", slug: "tanya-evil" },
      { name: "Mushoku Tensei", slug: "mushoku-tensei" },
      { name: "Log Horizon", slug: "log-horizon" },
    ],
    'slice-of-life': [
      { name: "Your Lie in April", slug: "your-lie-in-april" },
      { name: "A Silent Voice", slug: "a-silent-voice" },
      { name: "March Comes in Like a Lion", slug: "march-lion" },
      { name: "Clannad", slug: "clannad" },
      { name: "Anohana", slug: "anohana" },
      { name: "Barakamon", slug: "barakamon" },
      { name: "K-On!", slug: "k-on" },
      { name: "Toradora!", slug: "toradora" },
      { name: "Violet Evergarden", slug: "violet-evergarden" },
      { name: "The Quintessential Quintuplets", slug: "quintessential-quintuplets" },
    ],
    'classic-anime': [
      { name: "Astro Boy", slug: "astro-boy" },
      { name: "Speed Racer", slug: "speed-racer" },
      { name: "Lupin III", slug: "lupin-iii" },
      { name: "Captain Tsubasa", slug: "captain-tsubasa" },
      { name: "Doraemon", slug: "doraemon" },
      { name: "Fist of the North Star", slug: "fist-north-star" },
      { name: "Saint Seiya", slug: "saint-seiya" },
      { name: "City Hunter", slug: "city-hunter-anime" },
      { name: "Slam Dunk", slug: "slam-dunk-anime" },
      { name: "Rurouni Kenshin", slug: "rurouni-kenshin" },
      { name: "Your Name", slug: "your-name-anime" },
      { name: "Weathering with You", slug: "weathering-with-you" },
      { name: "Perfect Blue", slug: "perfect-blue" },
      { name: "Paprika", slug: "paprika-anime" },
      { name: "Summer Wars", slug: "summer-wars" },
    ],
    'studio-ghibli': [
      { name: "Spirited Away", slug: "spirited-away" },
      { name: "My Neighbor Totoro", slug: "totoro" },
      { name: "Princess Mononoke", slug: "princess-mononoke" },
      { name: "Howl's Moving Castle", slug: "howls-moving-castle" },
      { name: "Kiki's Delivery Service", slug: "kikis-delivery-service" },
      { name: "Ponyo", slug: "ponyo" },
      { name: "Castle in the Sky", slug: "castle-in-sky" },
      { name: "Grave of the Fireflies", slug: "grave-fireflies" },
      { name: "The Wind Rises", slug: "wind-rises" },
      { name: "Nausicaä of the Valley of the Wind", slug: "nausicaa" },
      { name: "Hayao Miyazaki", slug: "hayao-miyazaki" },
      { name: "Studio Ghibli History", slug: "studio-ghibli-history" },
    ],
    'anime-creators': [
      { name: "Akira Toriyama", slug: "akira-toriyama" },
      { name: "Eiichiro Oda", slug: "eiichiro-oda" },
      { name: "Masashi Kishimoto", slug: "masashi-kishimoto" },
      { name: "Rumiko Takahashi", slug: "rumiko-takahashi" },
      { name: "Osamu Tezuka", slug: "osamu-tezuka" },
      { name: "Kentaro Miura", slug: "kentaro-miura" },
      { name: "Naoko Takeuchi", slug: "naoko-takeuchi" },
      { name: "CLAMP", slug: "clamp-artists" },
      { name: "Hirohiko Araki", slug: "hirohiko-araki" },
      { name: "Hajime Isayama", slug: "hajime-isayama" },
      { name: "Makoto Shinkai", slug: "makoto-shinkai" },
      { name: "Satoshi Kon", slug: "satoshi-kon" },
    ],
    'manga': [
      { name: "Shonen Jump", slug: "shonen-jump" },
      { name: "Manga History", slug: "manga-history" },
      { name: "Manga Industry", slug: "manga-industry" },
      { name: "Manga Art Styles", slug: "manga-art-styles" },
      { name: "Manga Awards", slug: "manga-awards" },
      { name: "Light Novels", slug: "light-novels" },
      { name: "Manga vs Anime", slug: "manga-vs-anime" },
      { name: "Best-Selling Manga", slug: "best-selling-manga" },
    ],
  },
  'comics': {
    'dc': [
      { name: "Batman", slug: "batman-comics" },
      { name: "Superman", slug: "superman-comics" },
      { name: "Wonder Woman", slug: "wonder-woman-comics" },
      { name: "The Flash", slug: "flash-comics" },
      { name: "Aquaman", slug: "aquaman-comics" },
      { name: "Green Lantern", slug: "green-lantern-comics" },
      { name: "Justice League", slug: "justice-league-comics" },
      { name: "Teen Titans", slug: "teen-titans-comics" },
      { name: "Suicide Squad", slug: "suicide-squad-comics" },
      { name: "Watchmen", slug: "watchmen" },
      { name: "The Sandman", slug: "sandman-comics" },
      { name: "DC Origins", slug: "dc-origins" },
      { name: "Crisis on Infinite Earths", slug: "crisis-infinite-earths" },
    ],
    'marvel': [
      { name: "Spider-Man", slug: "spider-man-comics" },
      { name: "X-Men", slug: "x-men-comics" },
      { name: "The Avengers", slug: "avengers-comics" },
      { name: "Iron Man", slug: "iron-man-comics" },
      { name: "Captain America", slug: "captain-america-comics" },
      { name: "Thor", slug: "thor-comics" },
      { name: "Hulk", slug: "hulk-comics" },
      { name: "Fantastic Four", slug: "fantastic-four-comics" },
      { name: "Daredevil", slug: "daredevil-comics" },
      { name: "Deadpool", slug: "deadpool-comics" },
      { name: "Wolverine", slug: "wolverine-comics" },
      { name: "Black Panther", slug: "black-panther-comics" },
    ],
    'indie': [
      { name: "Hellboy", slug: "hellboy" },
      { name: "The Walking Dead", slug: "walking-dead-comic" },
      { name: "Spawn", slug: "spawn" },
      { name: "Invincible", slug: "invincible-comic" },
      { name: "Saga", slug: "saga-comic" },
      { name: "Sin City", slug: "sin-city-comic" },
      { name: "300", slug: "300-comic" },
      { name: "Bone", slug: "bone-comic" },
      { name: "Y: The Last Man", slug: "y-last-man" },
      { name: "Preacher", slug: "preacher-comic" },
      { name: "The Boys", slug: "the-boys-comic" },
      { name: "Image Comics", slug: "image-comics" },
    ],
    'comic-creators': [
      { name: "Stan Lee", slug: "stan-lee" },
      { name: "Jack Kirby", slug: "jack-kirby" },
      { name: "Todd McFarlane", slug: "todd-mcfarlane" },
      { name: "Jim Lee", slug: "jim-lee-artist" },
      { name: "Frank Miller", slug: "frank-miller" },
      { name: "Alan Moore", slug: "alan-moore" },
      { name: "Neil Gaiman", slug: "neil-gaiman" },
      { name: "Robert Kirkman", slug: "robert-kirkman" },
      { name: "Mike Mignola", slug: "mike-mignola" },
      { name: "Alex Ross", slug: "alex-ross" },
      { name: "Brian Michael Bendis", slug: "brian-bendis" },
      { name: "Grant Morrison", slug: "grant-morrison" },
    ],
    'villains': [
      { name: "The Joker", slug: "the-joker" },
      { name: "Thanos", slug: "thanos" },
      { name: "Lex Luthor", slug: "lex-luthor" },
      { name: "Magneto", slug: "magneto" },
      { name: "Doctor Doom", slug: "doctor-doom" },
      { name: "Darkseid", slug: "darkseid" },
      { name: "Green Goblin", slug: "green-goblin" },
      { name: "Venom", slug: "venom" },
      { name: "Loki", slug: "loki-comics" },
      { name: "Catwoman", slug: "catwoman" },
      { name: "Harley Quinn", slug: "harley-quinn" },
      { name: "Galactus", slug: "galactus" },
    ],
    'superheroes': [
      { name: "Superhero Origins", slug: "superhero-origins" },
      { name: "Superhero Teams", slug: "superhero-teams" },
      { name: "Superhero Powers", slug: "superhero-powers" },
      { name: "Superhero Costumes", slug: "superhero-costumes" },
      { name: "Secret Identities", slug: "secret-identities" },
      { name: "Sidekicks", slug: "sidekicks" },
      { name: "Anti-Heroes", slug: "anti-heroes" },
      { name: "Superhero Cities", slug: "superhero-cities" },
    ],
    'comic-history': [
      { name: "Golden Age of Comics", slug: "golden-age-comics" },
      { name: "Silver Age of Comics", slug: "silver-age-comics" },
      { name: "Bronze Age of Comics", slug: "bronze-age-comics" },
      { name: "Modern Age of Comics", slug: "modern-age-comics" },
      { name: "Comics Code Authority", slug: "comics-code" },
      { name: "Secret Wars", slug: "secret-wars" },
      { name: "Civil War (Comics)", slug: "civil-war-comics" },
      { name: "Infinity Gauntlet", slug: "infinity-gauntlet" },
      { name: "Comic Book Collecting", slug: "comic-collecting" },
      { name: "San Diego Comic-Con", slug: "sdcc" },
    ],
    'graphic-novels': [
      { name: "Maus", slug: "maus" },
      { name: "Persepolis", slug: "persepolis" },
      { name: "V for Vendetta", slug: "v-for-vendetta" },
      { name: "From Hell", slug: "from-hell" },
      { name: "Batman: The Killing Joke", slug: "killing-joke" },
      { name: "Kingdom Come", slug: "kingdom-come" },
      { name: "All-Star Superman", slug: "all-star-superman" },
      { name: "Ghost World", slug: "ghost-world" },
      { name: "Fun Home", slug: "fun-home" },
      { name: "The Dark Knight Returns", slug: "dark-knight-returns" },
    ],
    'webcomics': [
      { name: "xkcd", slug: "xkcd" },
      { name: "The Oatmeal", slug: "the-oatmeal" },
      { name: "Penny Arcade", slug: "penny-arcade" },
      { name: "Homestuck", slug: "homestuck" },
      { name: "Cyanide & Happiness", slug: "cyanide-happiness" },
      { name: "Webtoons", slug: "webtoons" },
      { name: "Tower of God", slug: "tower-of-god" },
      { name: "Solo Leveling", slug: "solo-leveling" },
      { name: "Lore Olympus", slug: "lore-olympus" },
      { name: "Peanuts", slug: "peanuts-comic" },
      { name: "Garfield", slug: "garfield" },
      { name: "Calvin and Hobbes", slug: "calvin-hobbes" },
    ],
    'comic-movies': [
      { name: "MCU Movies", slug: "mcu-movies" },
      { name: "DCEU Movies", slug: "dceu-movies" },
      { name: "X-Men Films", slug: "x-men-films" },
      { name: "Spider-Man Films", slug: "spider-man-films" },
      { name: "Batman Films", slug: "batman-films" },
      { name: "Superman Films", slug: "superman-films" },
      { name: "Avengers Films", slug: "avengers-films" },
      { name: "Comic Book Movie History", slug: "comic-movie-history" },
    ],
  },
  'video-games': {
    'nintendo': [
      { name: "Super Mario Bros.", slug: "super-mario" },
      { name: "The Legend of Zelda", slug: "zelda" },
      { name: "Pokémon", slug: "pokemon" },
      { name: "Animal Crossing", slug: "animal-crossing" },
      { name: "Super Smash Bros.", slug: "smash-bros" },
      { name: "Mario Kart", slug: "mario-kart" },
      { name: "Metroid", slug: "metroid" },
      { name: "Kirby", slug: "kirby" },
      { name: "Splatoon", slug: "splatoon" },
      { name: "Fire Emblem", slug: "fire-emblem" },
      { name: "Pikmin", slug: "pikmin" },
      { name: "F-Zero", slug: "f-zero" },
      { name: "Star Fox", slug: "star-fox" },
      { name: "Shigeru Miyamoto", slug: "shigeru-miyamoto" },
      { name: "Nintendo History", slug: "nintendo-history" },
    ],
    'playstation': [
      { name: "God of War", slug: "god-of-war" },
      { name: "The Last of Us", slug: "last-of-us" },
      { name: "Uncharted", slug: "uncharted" },
      { name: "Spider-Man (PS4/PS5)", slug: "spider-man-ps" },
      { name: "Horizon Zero Dawn", slug: "horizon-zero-dawn" },
      { name: "Ghost of Tsushima", slug: "ghost-of-tsushima" },
      { name: "Ratchet & Clank", slug: "ratchet-clank" },
      { name: "Gran Turismo", slug: "gran-turismo" },
      { name: "Bloodborne", slug: "bloodborne" },
      { name: "Jak and Daxter", slug: "jak-daxter" },
      { name: "LittleBigPlanet", slug: "littlebigplanet" },
      { name: "PlayStation History", slug: "playstation-history" },
    ],
    'pc-games': [
      { name: "Halo", slug: "halo" },
      { name: "Gears of War", slug: "gears-of-war" },
      { name: "Minecraft", slug: "minecraft" },
      { name: "Age of Empires", slug: "age-of-empires" },
      { name: "Flight Simulator", slug: "flight-simulator" },
      { name: "Starfield", slug: "starfield" },
      { name: "Steam Platform", slug: "steam" },
      { name: "PC Gaming History", slug: "pc-gaming-history" },
      { name: "Hollow Knight", slug: "hollow-knight" },
      { name: "Stardew Valley", slug: "stardew-valley" },
      { name: "Disco Elysium", slug: "disco-elysium" },
      { name: "Outer Wilds", slug: "outer-wilds" },
    ],
    'rpg': [
      { name: "Final Fantasy", slug: "final-fantasy" },
      { name: "The Elder Scrolls", slug: "elder-scrolls" },
      { name: "Dark Souls", slug: "dark-souls" },
      { name: "Elden Ring", slug: "elden-ring" },
      { name: "The Witcher", slug: "witcher-games" },
      { name: "Dragon Quest", slug: "dragon-quest" },
      { name: "Mass Effect", slug: "mass-effect" },
      { name: "Fallout", slug: "fallout" },
      { name: "Persona", slug: "persona" },
      { name: "Diablo", slug: "diablo" },
      { name: "World of Warcraft", slug: "world-of-warcraft" },
      { name: "Baldur's Gate", slug: "baldurs-gate" },
      { name: "Kingdom Hearts", slug: "kingdom-hearts" },
      { name: "Chrono Trigger", slug: "chrono-trigger" },
    ],
    'fps': [
      { name: "Call of Duty", slug: "call-of-duty" },
      { name: "Counter-Strike", slug: "counter-strike" },
      { name: "Doom", slug: "doom" },
      { name: "Half-Life", slug: "half-life" },
      { name: "Overwatch", slug: "overwatch" },
      { name: "Battlefield", slug: "battlefield" },
      { name: "Valorant", slug: "valorant" },
      { name: "Rainbow Six Siege", slug: "rainbow-six" },
      { name: "Destiny", slug: "destiny" },
      { name: "Titanfall", slug: "titanfall" },
      { name: "Bioshock", slug: "bioshock" },
      { name: "Far Cry", slug: "far-cry" },
      { name: "Fortnite", slug: "fortnite" },
      { name: "PUBG", slug: "pubg" },
      { name: "Apex Legends", slug: "apex-legends" },
    ],
    'sports-racing': [
      { name: "FIFA / EA Sports FC", slug: "fifa" },
      { name: "NBA 2K", slug: "nba-2k" },
      { name: "Madden NFL", slug: "madden" },
      { name: "WWE 2K", slug: "wwe-2k" },
      { name: "PES / eFootball", slug: "pes" },
      { name: "MLB The Show", slug: "mlb-the-show" },
      { name: "Tony Hawk's Pro Skater", slug: "tony-hawk" },
      { name: "NHL Series", slug: "nhl-games" },
      { name: "Rocket League", slug: "rocket-league" },
      { name: "Forza", slug: "forza" },
      { name: "Need for Speed", slug: "need-for-speed" },
      { name: "Mario Kart History", slug: "mario-kart-history" },
    ],
    'action': [
      { name: "Grand Theft Auto", slug: "gta" },
      { name: "Red Dead Redemption", slug: "red-dead" },
      { name: "Assassin's Creed", slug: "assassins-creed" },
      { name: "Metal Gear Solid", slug: "metal-gear" },
      { name: "Devil May Cry", slug: "devil-may-cry" },
      { name: "Resident Evil", slug: "resident-evil" },
      { name: "Tomb Raider", slug: "tomb-raider" },
      { name: "Just Cause", slug: "just-cause" },
      { name: "Watch Dogs", slug: "watch-dogs" },
      { name: "Sekiro", slug: "sekiro" },
    ],
    'strategy': [
      { name: "Civilization", slug: "civilization" },
      { name: "StarCraft", slug: "starcraft" },
      { name: "Total War", slug: "total-war" },
      { name: "XCOM", slug: "xcom" },
      { name: "Command & Conquer", slug: "command-conquer" },
      { name: "Crusader Kings", slug: "crusader-kings" },
      { name: "Anno", slug: "anno" },
      { name: "Cities: Skylines", slug: "cities-skylines" },
      { name: "Warcraft", slug: "warcraft" },
      { name: "Company of Heroes", slug: "company-heroes" },
    ],
    'puzzle': [
      { name: "Tetris", slug: "tetris" },
      { name: "Portal", slug: "portal" },
      { name: "The Witness", slug: "the-witness" },
      { name: "Baba Is You", slug: "baba-is-you" },
      { name: "Return of the Obra Dinn", slug: "obra-dinn" },
      { name: "Candy Crush", slug: "candy-crush" },
      { name: "Monument Valley", slug: "monument-valley" },
      { name: "The Talos Principle", slug: "talos-principle" },
      { name: "Limbo", slug: "limbo-game" },
      { name: "Inside", slug: "inside-game" },
    ],
    'esports': [
      { name: "League of Legends Esports", slug: "lol-esports" },
      { name: "Dota 2 Esports", slug: "dota-esports" },
      { name: "CS:GO/CS2 Esports", slug: "csgo-esports" },
      { name: "Overwatch League", slug: "owl-esports" },
      { name: "Valorant Champions", slug: "valorant-esports" },
      { name: "Fighting Game Community", slug: "fgc" },
      { name: "Smash Bros Competitive", slug: "smash-competitive" },
      { name: "Esports History", slug: "esports-history" },
      { name: "Famous Esports Players", slug: "esports-players" },
    ],
    'retro': [
      { name: "Pac-Man", slug: "pac-man" },
      { name: "Space Invaders", slug: "space-invaders" },
      { name: "Donkey Kong", slug: "donkey-kong-arcade" },
      { name: "Street Fighter II", slug: "street-fighter-ii" },
      { name: "Mortal Kombat", slug: "mortal-kombat" },
      { name: "Sonic the Hedgehog", slug: "sonic" },
      { name: "Mega Man", slug: "mega-man" },
      { name: "Castlevania", slug: "castlevania" },
      { name: "Contra", slug: "contra" },
      { name: "Atari Games", slug: "atari-games" },
      { name: "Arcade History", slug: "arcade-history" },
      { name: "Celeste", slug: "celeste" },
      { name: "Undertale", slug: "undertale" },
      { name: "Hades", slug: "hades-game" },
      { name: "Cuphead", slug: "cuphead" },
    ],
    'consoles': [
      { name: "Console Wars History", slug: "console-wars" },
      { name: "Nintendo Console History", slug: "nintendo-consoles" },
      { name: "PlayStation Console History", slug: "playstation-consoles" },
      { name: "Xbox Console History", slug: "xbox-consoles" },
      { name: "Sega History", slug: "sega-history" },
      { name: "Atari History", slug: "atari-history" },
      { name: "Handheld Gaming", slug: "handheld-gaming" },
      { name: "Virtual Reality Gaming", slug: "vr-gaming" },
    ],
    'gaming-history': [
      { name: "Video Game Crash of 1983", slug: "video-game-crash" },
      { name: "Video Game Pioneers", slug: "game-pioneers" },
      { name: "Gaming Industry Evolution", slug: "gaming-evolution" },
      { name: "Best-Selling Games Ever", slug: "best-selling-games" },
      { name: "Game Awards History", slug: "game-awards" },
      { name: "E3 History", slug: "e3-history" },
      { name: "Gaming Controversies", slug: "gaming-controversies" },
    ],
  },
  'technology': {
    'computing': [
      { name: "History of Computers", slug: "computer-history" },
      { name: "Alan Turing", slug: "alan-turing" },
      { name: "Ada Lovelace", slug: "ada-lovelace" },
      { name: "Charles Babbage", slug: "charles-babbage" },
      { name: "ENIAC", slug: "eniac" },
      { name: "Personal Computer Revolution", slug: "pc-revolution" },
      { name: "Computer Architecture", slug: "computer-architecture" },
      { name: "Cloud Computing", slug: "cloud-computing" },
      { name: "Quantum Computing", slug: "quantum-computing" },
      { name: "Supercomputers", slug: "supercomputers" },
      { name: "Moore's Law", slug: "moores-law" },
    ],
    'internet': [
      { name: "History of the Internet", slug: "internet-history" },
      { name: "World Wide Web", slug: "world-wide-web" },
      { name: "Tim Berners-Lee", slug: "tim-berners-lee" },
      { name: "Search Engines", slug: "search-engines" },
      { name: "Email History", slug: "email-history" },
      { name: "Social Media History", slug: "social-media-history" },
      { name: "E-Commerce", slug: "e-commerce" },
      { name: "Net Neutrality", slug: "net-neutrality" },
      { name: "Internet Protocols", slug: "internet-protocols" },
      { name: "Dot-Com Bubble", slug: "dotcom-bubble" },
      { name: "Web 2.0", slug: "web-2" },
    ],
    'mobile': [
      { name: "iPhone History", slug: "iphone-history" },
      { name: "Android History", slug: "android-history" },
      { name: "Smartphone Evolution", slug: "smartphone-evolution" },
      { name: "Mobile Apps", slug: "mobile-apps" },
      { name: "5G Technology", slug: "5g-technology" },
      { name: "Nokia History", slug: "nokia-history" },
      { name: "BlackBerry History", slug: "blackberry-history" },
      { name: "Tablet Computing", slug: "tablet-computing" },
      { name: "Mobile Payment", slug: "mobile-payment" },
      { name: "App Store History", slug: "app-store-history" },
    ],
    'ai': [
      { name: "Artificial Intelligence History", slug: "ai-history" },
      { name: "Machine Learning Basics", slug: "machine-learning" },
      { name: "Deep Learning", slug: "deep-learning" },
      { name: "Neural Networks", slug: "neural-networks" },
      { name: "ChatGPT & LLMs", slug: "chatgpt-llms" },
      { name: "Computer Vision", slug: "computer-vision" },
      { name: "Natural Language Processing", slug: "nlp" },
      { name: "AI Ethics", slug: "ai-ethics" },
      { name: "Self-Driving Cars", slug: "self-driving-cars" },
      { name: "AI in Healthcare", slug: "ai-healthcare" },
      { name: "AI Pioneers", slug: "ai-pioneers" },
    ],
    'tech-companies': [
      { name: "Apple Inc.", slug: "apple-company" },
      { name: "Microsoft", slug: "microsoft" },
      { name: "Google", slug: "google" },
      { name: "Amazon", slug: "amazon-company" },
      { name: "Meta/Facebook", slug: "meta-facebook" },
      { name: "Netflix", slug: "netflix-company" },
      { name: "Tesla", slug: "tesla-company" },
      { name: "SpaceX", slug: "spacex" },
      { name: "IBM History", slug: "ibm-history" },
      { name: "Intel", slug: "intel" },
      { name: "NVIDIA", slug: "nvidia" },
      { name: "Samsung", slug: "samsung" },
      { name: "Alibaba", slug: "alibaba" },
      { name: "Tencent", slug: "tencent" },
      { name: "Steve Jobs", slug: "steve-jobs" },
      { name: "Bill Gates", slug: "bill-gates" },
      { name: "Elon Musk", slug: "elon-musk-tech" },
      { name: "Jeff Bezos", slug: "jeff-bezos" },
      { name: "Mark Zuckerberg", slug: "mark-zuckerberg" },
    ],
    'innovations': [
      { name: "Blockchain Technology", slug: "blockchain" },
      { name: "Cryptocurrency", slug: "cryptocurrency" },
      { name: "The Metaverse", slug: "metaverse" },
      { name: "IoT (Internet of Things)", slug: "iot" },
      { name: "3D Printing", slug: "3d-printing" },
      { name: "Drones Technology", slug: "drones" },
      { name: "Wearable Technology", slug: "wearables" },
      { name: "Green Tech", slug: "green-tech" },
      { name: "Biotechnology", slug: "biotechnology-tech" },
      { name: "Space Technology", slug: "space-tech" },
    ],
    'robotics': [
      { name: "Industrial Robots", slug: "industrial-robots" },
      { name: "Boston Dynamics", slug: "boston-dynamics" },
      { name: "Humanoid Robots", slug: "humanoid-robots" },
      { name: "Robot History", slug: "robot-history" },
      { name: "Surgical Robots", slug: "surgical-robots" },
      { name: "Drones & UAVs", slug: "drones-uavs" },
      { name: "Robot Ethics", slug: "robot-ethics" },
      { name: "Home Robots", slug: "home-robots" },
    ],
    'vr-ar': [
      { name: "Virtual Reality", slug: "virtual-reality" },
      { name: "Augmented Reality", slug: "augmented-reality" },
      { name: "VR Headsets", slug: "vr-headsets" },
      { name: "Meta Quest", slug: "meta-quest" },
      { name: "Apple Vision Pro", slug: "apple-vision-pro" },
      { name: "VR in Gaming", slug: "vr-gaming-tech" },
      { name: "AR Applications", slug: "ar-applications" },
      { name: "Mixed Reality", slug: "mixed-reality" },
    ],
    'software': [
      { name: "Windows History", slug: "windows-history" },
      { name: "macOS History", slug: "macos-history" },
      { name: "Linux History", slug: "linux-history" },
      { name: "Open Source Software", slug: "open-source" },
      { name: "Microsoft Office", slug: "microsoft-office" },
      { name: "Adobe Software", slug: "adobe-software" },
      { name: "Video Editing Software", slug: "video-editing-software" },
      { name: "Browsers History", slug: "browsers-history" },
    ],
    'cybersecurity': [
      { name: "Hacking History", slug: "hacking-history" },
      { name: "Famous Hackers", slug: "famous-hackers" },
      { name: "Cyber Attacks", slug: "cyber-attacks" },
      { name: "Ransomware", slug: "ransomware" },
      { name: "Data Breaches", slug: "data-breaches" },
      { name: "Privacy & Encryption", slug: "privacy-encryption" },
      { name: "Cybersecurity Careers", slug: "cybersecurity-careers" },
      { name: "White Hat vs Black Hat", slug: "white-black-hat" },
    ],
    'tech-history': [
      { name: "Silicon Valley History", slug: "silicon-valley" },
      { name: "Tech IPOs", slug: "tech-ipos" },
      { name: "Tech Acquisitions", slug: "tech-acquisitions" },
      { name: "Failed Tech Products", slug: "failed-tech" },
      { name: "Tech Milestones", slug: "tech-milestones" },
      { name: "Memes History", slug: "memes-history" },
      { name: "Viral Videos", slug: "viral-videos" },
      { name: "YouTube History", slug: "youtube-history" },
    ],
  },
  'programming': {
    'javascript': [
      { name: "JavaScript Basics", slug: "javascript-basics" },
      { name: "JavaScript ES6+", slug: "javascript-es6" },
      { name: "Node.js", slug: "nodejs" },
      { name: "React", slug: "react" },
      { name: "Vue.js", slug: "vue" },
      { name: "Angular", slug: "angular" },
      { name: "TypeScript", slug: "typescript" },
      { name: "JavaScript History", slug: "javascript-history" },
      { name: "Brendan Eich", slug: "brendan-eich" },
    ],
    'python': [
      { name: "Python Basics", slug: "python-basics" },
      { name: "Python for Data Science", slug: "python-data-science" },
      { name: "Django", slug: "django" },
      { name: "Flask", slug: "flask" },
      { name: "Pandas", slug: "pandas" },
      { name: "NumPy", slug: "numpy" },
      { name: "Python History", slug: "python-history" },
      { name: "Guido van Rossum", slug: "guido-van-rossum" },
    ],
    'java': [
      { name: "Java Basics", slug: "java-basics" },
      { name: "Spring Framework", slug: "spring-framework" },
      { name: "Android with Java", slug: "android-java" },
      { name: "Java Enterprise", slug: "java-enterprise" },
      { name: "JVM Languages", slug: "jvm-languages" },
      { name: "Java History", slug: "java-history" },
    ],
    'cpp': [
      { name: "C Programming", slug: "c-programming" },
      { name: "C++ Basics", slug: "cpp-basics" },
      { name: "C++ STL", slug: "cpp-stl" },
      { name: "Game Development with C++", slug: "cpp-game-dev" },
      { name: "Systems Programming", slug: "systems-programming" },
      { name: "Dennis Ritchie", slug: "dennis-ritchie" },
    ],
    'web-dev': [
      { name: "HTML & CSS", slug: "html-css" },
      { name: "REST APIs", slug: "rest-apis" },
      { name: "GraphQL", slug: "graphql" },
      { name: "Web Security", slug: "web-security" },
      { name: "Frontend Development", slug: "frontend-dev" },
      { name: "Backend Development", slug: "backend-dev" },
      { name: "Responsive Design", slug: "responsive-design" },
      { name: "CSS Frameworks", slug: "css-frameworks" },
    ],
    'databases': [
      { name: "MySQL", slug: "mysql" },
      { name: "PostgreSQL", slug: "postgresql" },
      { name: "MongoDB", slug: "mongodb" },
      { name: "Redis", slug: "redis" },
      { name: "SQLite", slug: "sqlite" },
      { name: "Database Design", slug: "database-design" },
      { name: "NoSQL Databases", slug: "nosql" },
      { name: "SQL Language", slug: "sql-language" },
    ],
    'devops': [
      { name: "Git & GitHub", slug: "git-github" },
      { name: "Docker", slug: "docker" },
      { name: "Kubernetes", slug: "kubernetes" },
      { name: "CI/CD", slug: "ci-cd" },
      { name: "AWS", slug: "aws" },
      { name: "Azure", slug: "azure" },
      { name: "Google Cloud", slug: "google-cloud" },
      { name: "Terraform", slug: "terraform" },
      { name: "Linux Administration", slug: "linux-admin" },
    ],
    'mobile-dev': [
      { name: "iOS Development", slug: "ios-dev" },
      { name: "Android Development", slug: "android-dev" },
      { name: "React Native", slug: "react-native" },
      { name: "Flutter", slug: "flutter" },
      { name: "Swift Language", slug: "swift-language" },
      { name: "Kotlin", slug: "kotlin" },
      { name: "Mobile UI/UX", slug: "mobile-ui-ux" },
    ],
    'algorithms': [
      { name: "Sorting Algorithms", slug: "sorting-algorithms" },
      { name: "Search Algorithms", slug: "search-algorithms" },
      { name: "Graph Algorithms", slug: "graph-algorithms" },
      { name: "Dynamic Programming", slug: "dynamic-programming" },
      { name: "Data Structures", slug: "data-structures" },
      { name: "Big O Notation", slug: "big-o" },
      { name: "Trees & Binary Trees", slug: "trees-binary" },
      { name: "Hash Tables", slug: "hash-tables" },
      { name: "Coding Interviews", slug: "coding-interviews" },
    ],
    'open-source': [
      { name: "Open Source History", slug: "open-source-history" },
      { name: "Linux Kernel", slug: "linux-kernel" },
      { name: "Linus Torvalds", slug: "linus-torvalds" },
      { name: "GNU Project", slug: "gnu-project" },
      { name: "Richard Stallman", slug: "richard-stallman" },
      { name: "Open Source Licenses", slug: "open-source-licenses" },
      { name: "Famous Open Source Projects", slug: "famous-oss" },
      { name: "GitHub", slug: "github" },
    ],
  },
};

let added = 0;
let skipped = 0;

for (const [category, subcats] of Object.entries(topics)) {
  console.log(`\n=== ${category.toUpperCase()} ===\n`);

  for (const [subcategory, topicList] of Object.entries(subcats)) {
    console.log(`${subcategory}:`);

    for (const topic of topicList) {
      if (existingSlugs.has(topic.slug)) {
        console.log(`  ~ ${topic.name} (exists)`);
        skipped++;
      } else {
        ensureTopic({
          category,
          subcategory,
          slug: topic.slug,
          name: topic.name,
        });
        existingSlugs.add(topic.slug);
        console.log(`  + ${topic.name}`);
        added++;
      }
    }
    console.log();
  }
}

console.log(`✓ Added: ${added} topics`);
console.log(`- Skipped: ${skipped} (already exist)`);

// Show total
const totalTopics = categories.flatMap(c => getTopics(c)).length;
console.log(`\nTotal topics in these categories: ${totalTopics}`);
