/**
 * Seed history topics for all history-related categories
 */

import { ensureTopic, getTopics, initRegistry } from '../src/lib/registry';

initRegistry();

// Get existing topics
const existingTopics = [
  ...getTopics('history'),
  ...getTopics('regional-history'),
  ...getTopics('military'),
  ...getTopics('famous-people'),
  ...getTopics('inventions'),
  ...getTopics('world-cultures'),
];
const existingSlugs = new Set(existingTopics.map(t => t.slug));

const history: Record<string, Record<string, Array<{ name: string; slug: string }>>> = {
  'history': {
    'ancient': [
      { name: "Ancient Egypt", slug: "ancient-egypt" },
      { name: "Ancient Greece", slug: "ancient-greece" },
      { name: "Roman Empire", slug: "roman-empire" },
      { name: "Ancient Mesopotamia", slug: "ancient-mesopotamia" },
      { name: "Ancient Persia", slug: "ancient-persia" },
      { name: "Ancient India", slug: "ancient-india" },
      { name: "Ancient China", slug: "ancient-china" },
      { name: "Phoenicians", slug: "phoenicians" },
      { name: "Carthage", slug: "carthage" },
      { name: "Ancient Israel", slug: "ancient-israel" },
      { name: "Minoan Civilization", slug: "minoan-civilization" },
      { name: "Mycenaean Greece", slug: "mycenaean-greece" },
      { name: "Assyrian Empire", slug: "assyrian-empire" },
      { name: "Babylonian Empire", slug: "babylonian-empire" },
      { name: "Hittites", slug: "hittites" },
      { name: "Ancient Olympics", slug: "ancient-olympics" },
      { name: "Seven Wonders of Ancient World", slug: "seven-wonders-ancient" },
      { name: "Fall of Rome", slug: "fall-of-rome" },
    ],
    'civilizations': [
      { name: "Indus Valley Civilization", slug: "indus-valley" },
      { name: "Maya Civilization", slug: "maya-civilization" },
      { name: "Aztec Empire", slug: "aztec-empire" },
      { name: "Inca Empire", slug: "inca-empire" },
      { name: "Ancient Olmec", slug: "olmec-civilization" },
      { name: "Khmer Empire", slug: "khmer-empire" },
      { name: "Kingdom of Aksum", slug: "aksum-kingdom" },
      { name: "Great Zimbabwe", slug: "great-zimbabwe" },
      { name: "Sumerian Civilization", slug: "sumerian-civilization" },
      { name: "Maurya Empire", slug: "maurya-empire" },
      { name: "Gupta Empire", slug: "gupta-empire" },
      { name: "Han Dynasty", slug: "han-dynasty" },
      { name: "Tang Dynasty", slug: "tang-dynasty" },
      { name: "Silk Road Civilizations", slug: "silk-road-civilizations" },
      { name: "Polynesian Voyagers", slug: "polynesian-voyagers" },
      { name: "Native American Civilizations", slug: "native-american-civs" },
    ],
    'medieval': [
      { name: "Byzantine Empire", slug: "byzantine-empire" },
      { name: "Islamic Golden Age", slug: "islamic-golden-age" },
      { name: "Crusades", slug: "crusades" },
      { name: "Viking Age", slug: "viking-age" },
      { name: "Mongol Empire", slug: "mongol-empire" },
      { name: "Holy Roman Empire", slug: "holy-roman-empire" },
      { name: "Medieval Europe", slug: "medieval-europe" },
      { name: "Feudalism", slug: "feudalism" },
      { name: "Black Death", slug: "black-death" },
      { name: "Hundred Years' War", slug: "hundred-years-war" },
      { name: "Norman Conquest", slug: "norman-conquest" },
      { name: "Reconquista", slug: "reconquista" },
      { name: "Ottoman Rise", slug: "ottoman-rise" },
      { name: "Medieval Japan", slug: "medieval-japan" },
      { name: "Knights Templar", slug: "knights-templar" },
      { name: "Medieval Castles", slug: "medieval-castles" },
      { name: "Hanseatic League", slug: "hanseatic-league" },
      { name: "Marco Polo", slug: "marco-polo" },
    ],
    'renaissance': [
      { name: "Italian Renaissance", slug: "italian-renaissance" },
      { name: "Northern Renaissance", slug: "northern-renaissance" },
      { name: "Age of Exploration", slug: "age-of-exploration" },
      { name: "Protestant Reformation", slug: "protestant-reformation" },
      { name: "Scientific Revolution", slug: "scientific-revolution" },
      { name: "Renaissance Art", slug: "renaissance-art" },
      { name: "Leonardo da Vinci", slug: "leonardo-da-vinci" },
      { name: "Michelangelo", slug: "michelangelo" },
      { name: "Medici Family", slug: "medici-family" },
      { name: "Printing Press", slug: "printing-press" },
      { name: "Columbus's Voyages", slug: "columbus-voyages" },
      { name: "Magellan's Circumnavigation", slug: "magellan-voyage" },
      { name: "Spanish Conquistadors", slug: "spanish-conquistadors" },
      { name: "Elizabethan Era", slug: "elizabethan-era" },
      { name: "Rise of Nation-States", slug: "rise-nation-states" },
      { name: "Humanism", slug: "humanism" },
    ],
    'modern': [
      { name: "Industrial Revolution", slug: "industrial-revolution" },
      { name: "French Revolution", slug: "french-revolution" },
      { name: "American Revolution", slug: "american-revolution" },
      { name: "Napoleonic Wars", slug: "napoleonic-wars" },
      { name: "Victorian Era", slug: "victorian-era" },
      { name: "Colonialism in Africa", slug: "colonialism-africa" },
      { name: "British Empire", slug: "british-empire" },
      { name: "American Civil War", slug: "american-civil-war" },
      { name: "Meiji Restoration", slug: "meiji-restoration" },
      { name: "Russian Revolution", slug: "russian-revolution" },
      { name: "Rise of Fascism", slug: "rise-of-fascism" },
      { name: "Great Depression", slug: "great-depression" },
      { name: "Abolition of Slavery", slug: "abolition-slavery" },
      { name: "Women's Suffrage", slug: "womens-suffrage" },
      { name: "Opium Wars", slug: "opium-wars" },
      { name: "Scramble for Africa", slug: "scramble-for-africa" },
    ],
    'world-wars': [
      { name: "Causes of World War I", slug: "causes-ww1" },
      { name: "Western Front WWI", slug: "western-front-ww1" },
      { name: "Treaty of Versailles", slug: "treaty-versailles" },
      { name: "Rise of Hitler", slug: "rise-of-hitler" },
      { name: "Nazi Germany", slug: "nazi-germany" },
      { name: "Holocaust", slug: "holocaust" },
      { name: "D-Day Normandy", slug: "d-day-normandy" },
      { name: "Battle of Stalingrad", slug: "battle-stalingrad" },
      { name: "Pacific Theater WWII", slug: "pacific-theater-ww2" },
      { name: "Pearl Harbor", slug: "pearl-harbor" },
      { name: "Atomic Bombings", slug: "atomic-bombings" },
      { name: "Allied Powers", slug: "allied-powers" },
      { name: "Axis Powers", slug: "axis-powers" },
      { name: "Home Front WWII", slug: "home-front-ww2" },
      { name: "Winston Churchill", slug: "winston-churchill" },
      { name: "Franklin D. Roosevelt", slug: "fdr" },
      { name: "Battle of Britain", slug: "battle-of-britain" },
      { name: "Nuremberg Trials", slug: "nuremberg-trials" },
    ],
    'cold-war': [
      { name: "Origins of Cold War", slug: "origins-cold-war" },
      { name: "Iron Curtain", slug: "iron-curtain" },
      { name: "Korean War", slug: "korean-war" },
      { name: "Vietnam War", slug: "vietnam-war" },
      { name: "Cuban Missile Crisis", slug: "cuban-missile-crisis" },
      { name: "Space Race", slug: "space-race-history" },
      { name: "Berlin Wall", slug: "berlin-wall" },
      { name: "Arms Race", slug: "arms-race" },
      { name: "Proxy Wars", slug: "proxy-wars" },
      { name: "Decolonization", slug: "decolonization" },
      { name: "Non-Aligned Movement", slug: "non-aligned-movement" },
      { name: "Soviet Union", slug: "soviet-union" },
      { name: "Fall of USSR", slug: "fall-of-ussr" },
      { name: "Reagan Era", slug: "reagan-era" },
      { name: "Solidarity Movement", slug: "solidarity-movement" },
      { name: "Cold War Spies", slug: "cold-war-spies" },
    ],
    'contemporary': [
      { name: "9/11 and War on Terror", slug: "911-war-on-terror" },
      { name: "Fall of Berlin Wall", slug: "fall-berlin-wall" },
      { name: "European Union Formation", slug: "eu-formation" },
      { name: "Arab Spring", slug: "arab-spring" },
      { name: "Rise of China", slug: "rise-of-china" },
      { name: "Digital Revolution", slug: "digital-revolution" },
      { name: "Globalization", slug: "globalization" },
      { name: "Climate Change Movement", slug: "climate-movement" },
      { name: "COVID-19 Pandemic", slug: "covid-pandemic" },
      { name: "Brexit", slug: "brexit" },
      { name: "Rwandan Genocide", slug: "rwandan-genocide" },
      { name: "Yugoslav Wars", slug: "yugoslav-wars" },
      { name: "Syrian Civil War", slug: "syrian-civil-war" },
      { name: "Ukraine Conflict", slug: "ukraine-conflict" },
      { name: "Me Too Movement", slug: "metoo-movement" },
      { name: "Black Lives Matter", slug: "blm-movement" },
    ],
    'revolutions': [
      { name: "Glorious Revolution", slug: "glorious-revolution" },
      { name: "Haitian Revolution", slug: "haitian-revolution" },
      { name: "Latin American Independence", slug: "latin-american-independence" },
      { name: "Revolutions of 1848", slug: "revolutions-1848" },
      { name: "Chinese Revolution 1949", slug: "chinese-revolution-1949" },
      { name: "Cuban Revolution", slug: "cuban-revolution" },
      { name: "Iranian Revolution", slug: "iranian-revolution" },
      { name: "Velvet Revolution", slug: "velvet-revolution" },
      { name: "Color Revolutions", slug: "color-revolutions" },
      { name: "Indian Independence Movement", slug: "indian-independence" },
      { name: "Irish Independence", slug: "irish-independence" },
      { name: "Algerian War", slug: "algerian-war" },
      { name: "Egyptian Revolution 2011", slug: "egyptian-revolution-2011" },
      { name: "Texas Revolution", slug: "texas-revolution" },
      { name: "Philippine Revolution", slug: "philippine-revolution" },
      { name: "Hungarian Revolution 1956", slug: "hungarian-revolution-1956" },
    ],
    'colonialism': [
      { name: "Age of Imperialism", slug: "age-of-imperialism" },
      { name: "British Raj", slug: "british-raj" },
      { name: "Dutch East Indies", slug: "dutch-east-indies" },
      { name: "French Colonial Empire", slug: "french-colonial-empire" },
      { name: "Spanish Empire", slug: "spanish-empire" },
      { name: "Portuguese Empire", slug: "portuguese-empire" },
      { name: "Belgian Congo", slug: "belgian-congo" },
      { name: "Partition of India", slug: "partition-of-india" },
      { name: "Apartheid South Africa", slug: "apartheid" },
      { name: "Trail of Tears", slug: "trail-of-tears" },
      { name: "East India Company", slug: "east-india-company" },
      { name: "Opium Trade", slug: "opium-trade" },
      { name: "Slave Trade", slug: "slave-trade" },
      { name: "Colonization of Australia", slug: "colonization-australia" },
      { name: "African Independence Movements", slug: "african-independence" },
      { name: "Post-Colonial Africa", slug: "post-colonial-africa" },
    ],
  },

  'regional-history': {
    'american': [
      { name: "Native American History", slug: "native-american-history" },
      { name: "Colonial America", slug: "colonial-america" },
      { name: "Founding Fathers", slug: "founding-fathers" },
      { name: "U.S. Constitution", slug: "us-constitution" },
      { name: "Westward Expansion", slug: "westward-expansion" },
      { name: "Civil Rights Movement", slug: "civil-rights-movement" },
      { name: "Roaring Twenties", slug: "roaring-twenties" },
      { name: "Prohibition Era", slug: "prohibition-era" },
      { name: "Civil War Battles", slug: "civil-war-battles" },
      { name: "Abraham Lincoln", slug: "abraham-lincoln" },
      { name: "George Washington", slug: "george-washington" },
      { name: "Thomas Jefferson", slug: "thomas-jefferson" },
      { name: "JFK & Camelot", slug: "jfk-camelot" },
      { name: "Martin Luther King Jr.", slug: "martin-luther-king" },
      { name: "American Presidents", slug: "american-presidents" },
      { name: "Gold Rush", slug: "gold-rush" },
      { name: "Underground Railroad", slug: "underground-railroad" },
      { name: "Gilded Age", slug: "gilded-age" },
    ],
    'british': [
      { name: "Roman Britain", slug: "roman-britain" },
      { name: "Anglo-Saxon England", slug: "anglo-saxon-england" },
      { name: "Medieval England", slug: "medieval-england" },
      { name: "Tudor Dynasty", slug: "tudor-dynasty" },
      { name: "Henry VIII", slug: "henry-viii" },
      { name: "Elizabeth I", slug: "elizabeth-i" },
      { name: "English Civil War", slug: "english-civil-war" },
      { name: "British Monarchy", slug: "british-monarchy" },
      { name: "Queen Victoria", slug: "queen-victoria" },
      { name: "Scottish History", slug: "scottish-history" },
      { name: "Irish History", slug: "irish-history" },
      { name: "Welsh History", slug: "welsh-history" },
      { name: "Battle of Hastings", slug: "battle-of-hastings" },
      { name: "Magna Carta", slug: "magna-carta" },
      { name: "British Industrial Revolution", slug: "british-industrial-revolution" },
      { name: "London History", slug: "london-history" },
      { name: "Winston Churchill Era", slug: "churchill-era" },
      { name: "British Royal Family", slug: "british-royal-family" },
    ],
    'european': [
      { name: "French History", slug: "french-history" },
      { name: "German History", slug: "german-history" },
      { name: "Italian History", slug: "italian-history" },
      { name: "Spanish History", slug: "spanish-history" },
      { name: "Dutch Golden Age", slug: "dutch-golden-age" },
      { name: "Austro-Hungarian Empire", slug: "austro-hungarian-empire" },
      { name: "Polish History", slug: "polish-history" },
      { name: "Scandinavian History", slug: "scandinavian-history" },
      { name: "Greek History (Modern)", slug: "modern-greek-history" },
      { name: "Unification of Germany", slug: "german-unification" },
      { name: "Unification of Italy", slug: "italian-unification" },
      { name: "French Monarchs", slug: "french-monarchs" },
      { name: "Habsburg Dynasty", slug: "habsburg-dynasty" },
      { name: "Napoleonic France", slug: "napoleonic-france" },
      { name: "European Royalty", slug: "european-royalty" },
      { name: "Reformation in Europe", slug: "european-reformation" },
    ],
    'asian': [
      { name: "Japanese History", slug: "japanese-history" },
      { name: "Korean History", slug: "korean-history" },
      { name: "Vietnamese History", slug: "vietnamese-history" },
      { name: "Thai History", slug: "thai-history" },
      { name: "Indonesian History", slug: "indonesian-history" },
      { name: "Philippine History", slug: "philippine-history" },
      { name: "Samurai Era", slug: "samurai-era" },
      { name: "Shogunate Japan", slug: "shogunate-japan" },
      { name: "Korean War History", slug: "korean-war-history" },
      { name: "Southeast Asian Empires", slug: "southeast-asian-empires" },
      { name: "Mongol Invasions of Asia", slug: "mongol-invasions-asia" },
      { name: "Rise of Singapore", slug: "rise-of-singapore" },
      { name: "Asian Tigers", slug: "asian-tigers-history" },
      { name: "Cambodian History", slug: "cambodian-history" },
      { name: "Myanmar/Burma History", slug: "myanmar-history" },
      { name: "Central Asian History", slug: "central-asian-history" },
    ],
    'chinese': [
      { name: "Chinese Dynasties", slug: "chinese-dynasties" },
      { name: "Qin Dynasty", slug: "qin-dynasty" },
      { name: "Ming Dynasty", slug: "ming-dynasty" },
      { name: "Qing Dynasty", slug: "qing-dynasty" },
      { name: "Terracotta Army", slug: "terracotta-army" },
      { name: "Great Wall of China", slug: "great-wall-history" },
      { name: "Confucius", slug: "confucius" },
      { name: "Chinese Emperors", slug: "chinese-emperors" },
      { name: "Taiping Rebellion", slug: "taiping-rebellion" },
      { name: "Boxer Rebellion", slug: "boxer-rebellion" },
      { name: "Republic of China", slug: "republic-of-china" },
      { name: "Mao Zedong", slug: "mao-zedong" },
      { name: "Cultural Revolution", slug: "cultural-revolution" },
      { name: "Tiananmen Square", slug: "tiananmen-square" },
      { name: "Hong Kong History", slug: "hong-kong-history" },
      { name: "Taiwan History", slug: "taiwan-history" },
    ],
    'india': [
      { name: "Vedic Period", slug: "vedic-period" },
      { name: "Mughal Empire", slug: "mughal-empire" },
      { name: "Maratha Empire", slug: "maratha-empire" },
      { name: "Chola Dynasty", slug: "chola-dynasty" },
      { name: "Vijayanagara Empire", slug: "vijayanagara-empire" },
      { name: "Delhi Sultanate", slug: "delhi-sultanate" },
      { name: "Indian Rebellion 1857", slug: "indian-rebellion-1857" },
      { name: "Mahatma Gandhi", slug: "mahatma-gandhi" },
      { name: "Jawaharlal Nehru", slug: "jawaharlal-nehru" },
      { name: "Indian Independence", slug: "indian-independence-history" },
      { name: "Partition of India 1947", slug: "partition-1947" },
      { name: "Ancient Indian Empires", slug: "ancient-indian-empires" },
      { name: "Indian Kingdoms", slug: "indian-kingdoms" },
      { name: "Sikh Empire", slug: "sikh-empire" },
      { name: "Indian Prime Ministers", slug: "indian-prime-ministers" },
      { name: "Modern India", slug: "modern-india-history" },
      { name: "Indo-Pakistani Wars", slug: "indo-pak-wars" },
      { name: "Indian Freedom Fighters", slug: "indian-freedom-fighters" },
    ],
    'middle-eastern': [
      { name: "Ottoman Empire", slug: "ottoman-empire" },
      { name: "Persian Empire", slug: "persian-empire" },
      { name: "Arab Caliphates", slug: "arab-caliphates" },
      { name: "Rise of Islam", slug: "rise-of-islam" },
      { name: "Saladin", slug: "saladin" },
      { name: "Safavid Empire", slug: "safavid-empire" },
      { name: "Creation of Israel", slug: "creation-of-israel" },
      { name: "Arab-Israeli Conflict", slug: "arab-israeli-conflict" },
      { name: "Iran History", slug: "iran-history" },
      { name: "Iraq History", slug: "iraq-history" },
      { name: "Saudi Arabia History", slug: "saudi-arabia-history" },
      { name: "Egyptian Modern History", slug: "egyptian-modern-history" },
      { name: "Lebanese Civil War", slug: "lebanese-civil-war" },
      { name: "Gulf Wars", slug: "gulf-wars" },
      { name: "Suez Crisis", slug: "suez-crisis" },
      { name: "Palestinian History", slug: "palestinian-history" },
    ],
    'african': [
      { name: "Ancient Egypt (African)", slug: "ancient-egypt-africa" },
      { name: "Nubian Kingdoms", slug: "nubian-kingdoms" },
      { name: "Mali Empire", slug: "mali-empire" },
      { name: "Songhai Empire", slug: "songhai-empire" },
      { name: "Ethiopian History", slug: "ethiopian-history" },
      { name: "Zulu Kingdom", slug: "zulu-kingdom" },
      { name: "African Kingdoms", slug: "african-kingdoms" },
      { name: "Transatlantic Slave Trade", slug: "transatlantic-slave-trade" },
      { name: "Scramble for Africa", slug: "scramble-for-africa-history" },
      { name: "South African History", slug: "south-african-history" },
      { name: "Nelson Mandela", slug: "nelson-mandela" },
      { name: "Nigerian History", slug: "nigerian-history" },
      { name: "Kenyan History", slug: "kenyan-history" },
      { name: "Ghanaian History", slug: "ghanaian-history" },
      { name: "Egyptian Independence", slug: "egyptian-independence" },
      { name: "African Union", slug: "african-union" },
    ],
    'russian': [
      { name: "Kievan Rus", slug: "kievan-rus" },
      { name: "Russian Tsars", slug: "russian-tsars" },
      { name: "Peter the Great", slug: "peter-the-great" },
      { name: "Catherine the Great", slug: "catherine-the-great" },
      { name: "Russian Empire", slug: "russian-empire" },
      { name: "Romanov Dynasty", slug: "romanov-dynasty" },
      { name: "Russian Revolution 1917", slug: "russian-revolution-1917" },
      { name: "Lenin", slug: "lenin" },
      { name: "Stalin Era", slug: "stalin-era" },
      { name: "Soviet Collectivization", slug: "soviet-collectivization" },
      { name: "Siege of Leningrad", slug: "siege-of-leningrad" },
      { name: "Gorbachev & Perestroika", slug: "gorbachev-perestroika" },
      { name: "Post-Soviet Russia", slug: "post-soviet-russia" },
      { name: "Crimean History", slug: "crimean-history" },
      { name: "Siberian Exploration", slug: "siberian-exploration" },
      { name: "Russian Culture History", slug: "russian-culture-history" },
    ],
    'latin-american': [
      { name: "Pre-Columbian Americas", slug: "pre-columbian-americas" },
      { name: "Spanish Conquest", slug: "spanish-conquest" },
      { name: "Brazilian History", slug: "brazilian-history" },
      { name: "Mexican History", slug: "mexican-history" },
      { name: "Argentine History", slug: "argentine-history" },
      { name: "Cuban History", slug: "cuban-history" },
      { name: "Chilean History", slug: "chilean-history" },
      { name: "Simón Bolívar", slug: "simon-bolivar" },
      { name: "Mexican Revolution", slug: "mexican-revolution" },
      { name: "Latin American Dictators", slug: "latin-american-dictators" },
      { name: "Dirty War Argentina", slug: "dirty-war-argentina" },
      { name: "Pinochet's Chile", slug: "pinochet-chile" },
      { name: "Venezuelan History", slug: "venezuelan-history" },
      { name: "Peruvian History", slug: "peruvian-history" },
      { name: "Colombian History", slug: "colombian-history" },
      { name: "Central American History", slug: "central-american-history" },
    ],
  },

  'military': {
    'ancient-warfare': [
      { name: "Greek Phalanx", slug: "greek-phalanx" },
      { name: "Roman Legions", slug: "roman-legions" },
      { name: "Persian Wars", slug: "persian-wars" },
      { name: "Battle of Thermopylae", slug: "battle-thermopylae" },
      { name: "Alexander the Great Campaigns", slug: "alexander-campaigns" },
      { name: "Punic Wars", slug: "punic-wars" },
      { name: "Hannibal Barca", slug: "hannibal-barca" },
      { name: "Julius Caesar's Wars", slug: "julius-caesar-wars" },
      { name: "Siege Warfare Ancient", slug: "ancient-siege-warfare" },
      { name: "Ancient Naval Warfare", slug: "ancient-naval-warfare" },
      { name: "Spartan Warriors", slug: "spartan-warriors" },
      { name: "Sun Tzu & Art of War", slug: "sun-tzu-art-of-war" },
      { name: "Ancient Chinese Warfare", slug: "ancient-chinese-warfare" },
      { name: "Egyptian Military", slug: "egyptian-military" },
      { name: "Chariot Warfare", slug: "chariot-warfare" },
    ],
    'medieval-warfare': [
      { name: "Knights & Chivalry", slug: "knights-chivalry" },
      { name: "Siege Warfare Medieval", slug: "medieval-siege-warfare" },
      { name: "Crusader Battles", slug: "crusader-battles" },
      { name: "Mongol Military Tactics", slug: "mongol-tactics" },
      { name: "Hundred Years War Battles", slug: "hundred-years-war-battles" },
      { name: "Battle of Agincourt", slug: "battle-agincourt" },
      { name: "Longbow & Crossbow", slug: "longbow-crossbow" },
      { name: "Castle Defense", slug: "castle-defense" },
      { name: "Samurai Warfare", slug: "samurai-warfare" },
      { name: "Viking Warfare", slug: "viking-warfare" },
      { name: "Byzantine Military", slug: "byzantine-military" },
      { name: "Gunpowder Introduction", slug: "gunpowder-introduction" },
      { name: "Mercenary Companies", slug: "mercenary-companies" },
      { name: "Wars of the Roses", slug: "wars-of-roses" },
      { name: "Ottoman Military", slug: "ottoman-military" },
    ],
    'famous-battles': [
      { name: "Battle of Marathon", slug: "battle-marathon" },
      { name: "Battle of Cannae", slug: "battle-cannae" },
      { name: "Battle of Gaugamela", slug: "battle-gaugamela" },
      { name: "Battle of Tours", slug: "battle-tours" },
      { name: "Battle of Crécy", slug: "battle-crecy" },
      { name: "Battle of Lepanto", slug: "battle-lepanto" },
      { name: "Battle of Waterloo", slug: "battle-waterloo" },
      { name: "Battle of Gettysburg", slug: "battle-gettysburg" },
      { name: "Battle of Austerlitz", slug: "battle-austerlitz" },
      { name: "Battle of Trafalgar", slug: "battle-trafalgar" },
      { name: "Battle of Kursk", slug: "battle-kursk" },
      { name: "Battle of Midway", slug: "battle-midway" },
      { name: "Battle of El Alamein", slug: "battle-el-alamein" },
      { name: "Battle of the Bulge", slug: "battle-of-bulge" },
      { name: "Siege of Constantinople", slug: "siege-constantinople" },
      { name: "Battle of Vienna", slug: "battle-vienna" },
    ],
    'military-leaders': [
      { name: "Alexander the Great", slug: "alexander-the-great" },
      { name: "Julius Caesar", slug: "julius-caesar" },
      { name: "Napoleon Bonaparte", slug: "napoleon-bonaparte" },
      { name: "Genghis Khan", slug: "genghis-khan" },
      { name: "Hannibal", slug: "hannibal" },
      { name: "Sun Tzu", slug: "sun-tzu" },
      { name: "Attila the Hun", slug: "attila-hun" },
      { name: "George Patton", slug: "george-patton" },
      { name: "Erwin Rommel", slug: "erwin-rommel" },
      { name: "Douglas MacArthur", slug: "douglas-macarthur" },
      { name: "Dwight Eisenhower", slug: "dwight-eisenhower" },
      { name: "Georgy Zhukov", slug: "georgy-zhukov" },
      { name: "William the Conqueror", slug: "william-conqueror" },
      { name: "Duke of Wellington", slug: "duke-wellington" },
      { name: "Robert E. Lee", slug: "robert-e-lee" },
      { name: "Ulysses S. Grant", slug: "ulysses-grant" },
    ],
    'world-war-1': [
      { name: "Causes of WWI", slug: "ww1-causes" },
      { name: "Assassination of Franz Ferdinand", slug: "franz-ferdinand" },
      { name: "Trench Warfare", slug: "trench-warfare" },
      { name: "Battle of the Somme", slug: "battle-somme" },
      { name: "Battle of Verdun", slug: "battle-verdun" },
      { name: "Gallipoli Campaign", slug: "gallipoli" },
      { name: "Eastern Front WWI", slug: "eastern-front-ww1" },
      { name: "Chemical Warfare WWI", slug: "chemical-warfare-ww1" },
      { name: "Tank Introduction", slug: "tank-introduction" },
      { name: "U-Boat Warfare", slug: "u-boat-warfare" },
      { name: "American Entry WWI", slug: "american-entry-ww1" },
      { name: "Armistice 1918", slug: "armistice-1918" },
      { name: "WWI Casualties", slug: "ww1-casualties" },
      { name: "WWI Flying Aces", slug: "ww1-flying-aces" },
      { name: "Lawrence of Arabia", slug: "lawrence-of-arabia-history" },
      { name: "Ottoman Front WWI", slug: "ottoman-front-ww1" },
    ],
    'world-war-2': [
      { name: "Blitzkrieg", slug: "blitzkrieg" },
      { name: "Battle of France", slug: "battle-of-france" },
      { name: "Dunkirk Evacuation", slug: "dunkirk-evacuation" },
      { name: "Operation Barbarossa", slug: "operation-barbarossa" },
      { name: "North Africa Campaign", slug: "north-africa-campaign" },
      { name: "Italian Campaign", slug: "italian-campaign-ww2" },
      { name: "Operation Market Garden", slug: "operation-market-garden" },
      { name: "Iwo Jima", slug: "iwo-jima" },
      { name: "Okinawa", slug: "okinawa" },
      { name: "V-E Day", slug: "ve-day" },
      { name: "V-J Day", slug: "vj-day" },
      { name: "WWII Technology", slug: "ww2-technology" },
      { name: "Resistance Movements", slug: "resistance-movements" },
      { name: "WWII Espionage", slug: "ww2-espionage" },
      { name: "Manhattan Project", slug: "manhattan-project" },
      { name: "Enigma & Codebreaking", slug: "enigma-codebreaking" },
    ],
    'naval-warfare': [
      { name: "Age of Sail", slug: "age-of-sail" },
      { name: "Battle of Salamis", slug: "battle-salamis" },
      { name: "Spanish Armada", slug: "spanish-armada" },
      { name: "British Royal Navy", slug: "british-royal-navy" },
      { name: "Battle of Jutland", slug: "battle-jutland" },
      { name: "Submarine Warfare", slug: "submarine-warfare" },
      { name: "Aircraft Carriers", slug: "aircraft-carriers" },
      { name: "Battleships", slug: "battleships" },
      { name: "Naval Strategy", slug: "naval-strategy" },
      { name: "Piracy Golden Age", slug: "piracy-golden-age" },
      { name: "Privateers", slug: "privateers" },
      { name: "Naval Blockades", slug: "naval-blockades" },
      { name: "Modern Naval Warfare", slug: "modern-naval-warfare" },
      { name: "US Navy History", slug: "us-navy-history" },
      { name: "Famous Naval Commanders", slug: "naval-commanders" },
    ],
    'air-warfare': [
      { name: "Wright Brothers to WWI", slug: "early-aviation-military" },
      { name: "WWI Dogfights", slug: "ww1-dogfights" },
      { name: "Red Baron", slug: "red-baron" },
      { name: "Strategic Bombing WWII", slug: "strategic-bombing-ww2" },
      { name: "Fighter Aces", slug: "fighter-aces" },
      { name: "Bombers", slug: "military-bombers" },
      { name: "Fighter Aircraft History", slug: "fighter-aircraft-history" },
      { name: "Jet Age Military", slug: "jet-age-military" },
      { name: "Stealth Technology", slug: "stealth-technology" },
      { name: "Drones & UAVs", slug: "drones-uavs" },
      { name: "Air Superiority", slug: "air-superiority" },
      { name: "Helicopter Warfare", slug: "helicopter-warfare" },
      { name: "US Air Force", slug: "us-air-force" },
      { name: "RAF History", slug: "raf-history" },
      { name: "Luftwaffe", slug: "luftwaffe" },
    ],
    'modern-conflicts': [
      { name: "Gulf War 1991", slug: "gulf-war-1991" },
      { name: "Iraq War 2003", slug: "iraq-war-2003" },
      { name: "War in Afghanistan", slug: "afghanistan-war" },
      { name: "Falklands War", slug: "falklands-war" },
      { name: "Six-Day War", slug: "six-day-war" },
      { name: "Yom Kippur War", slug: "yom-kippur-war" },
      { name: "Balkan Wars 1990s", slug: "balkan-wars-90s" },
      { name: "Chechen Wars", slug: "chechen-wars" },
      { name: "Congo Wars", slug: "congo-wars" },
      { name: "War on Terror", slug: "war-on-terror" },
      { name: "ISIS Conflict", slug: "isis-conflict" },
      { name: "Modern Military Technology", slug: "modern-military-tech" },
      { name: "Cyber Warfare", slug: "cyber-warfare" },
      { name: "Special Forces", slug: "special-forces" },
      { name: "UN Peacekeeping", slug: "un-peacekeeping" },
    ],
    'weapons': [
      { name: "Sword History", slug: "sword-history" },
      { name: "Bow & Arrow", slug: "bow-arrow-history" },
      { name: "Firearms Evolution", slug: "firearms-evolution" },
      { name: "Artillery History", slug: "artillery-history" },
      { name: "Tank Development", slug: "tank-development" },
      { name: "Nuclear Weapons", slug: "nuclear-weapons-history" },
      { name: "Chemical Weapons", slug: "chemical-weapons-history" },
      { name: "Biological Weapons", slug: "biological-weapons" },
      { name: "Missile Technology", slug: "missile-technology" },
      { name: "Armor & Shields", slug: "armor-shields" },
      { name: "Famous Weapons", slug: "famous-weapons" },
      { name: "Medieval Weapons", slug: "medieval-weapons" },
      { name: "Modern Infantry Weapons", slug: "infantry-weapons" },
      { name: "Naval Weapons", slug: "naval-weapons" },
      { name: "Aircraft Weapons", slug: "aircraft-weapons" },
    ],
  },

  'famous-people': {
    'scientists': [
      { name: "Albert Einstein", slug: "albert-einstein" },
      { name: "Isaac Newton", slug: "isaac-newton" },
      { name: "Galileo Galilei", slug: "galileo" },
      { name: "Charles Darwin", slug: "charles-darwin" },
      { name: "Marie Curie", slug: "marie-curie" },
      { name: "Nikola Tesla", slug: "nikola-tesla" },
      { name: "Stephen Hawking", slug: "stephen-hawking" },
      { name: "Richard Feynman", slug: "richard-feynman" },
      { name: "Niels Bohr", slug: "niels-bohr" },
      { name: "Michael Faraday", slug: "michael-faraday" },
      { name: "James Clerk Maxwell", slug: "james-maxwell" },
      { name: "Carl Sagan", slug: "carl-sagan" },
      { name: "Neil deGrasse Tyson", slug: "neil-degrasse-tyson" },
      { name: "Jane Goodall", slug: "jane-goodall" },
      { name: "Rosalind Franklin", slug: "rosalind-franklin" },
      { name: "Watson & Crick", slug: "watson-crick" },
    ],
    'inventors': [
      { name: "Thomas Edison", slug: "thomas-edison" },
      { name: "Alexander Graham Bell", slug: "alexander-graham-bell" },
      { name: "Wright Brothers", slug: "wright-brothers" },
      { name: "James Watt", slug: "james-watt" },
      { name: "Eli Whitney", slug: "eli-whitney" },
      { name: "Henry Ford", slug: "henry-ford" },
      { name: "George Westinghouse", slug: "george-westinghouse" },
      { name: "Samuel Morse", slug: "samuel-morse" },
      { name: "Guglielmo Marconi", slug: "guglielmo-marconi" },
      { name: "Johannes Gutenberg", slug: "johannes-gutenberg" },
      { name: "Tim Berners-Lee", slug: "tim-berners-lee" },
      { name: "Elon Musk", slug: "elon-musk" },
      { name: "Steve Jobs", slug: "steve-jobs" },
      { name: "Bill Gates", slug: "bill-gates" },
      { name: "Ada Lovelace", slug: "ada-lovelace" },
      { name: "Alan Turing", slug: "alan-turing" },
    ],
    'leaders': [
      { name: "Cleopatra", slug: "cleopatra" },
      { name: "Augustus Caesar", slug: "augustus-caesar" },
      { name: "Charlemagne", slug: "charlemagne" },
      { name: "Queen Elizabeth II", slug: "queen-elizabeth-ii" },
      { name: "Louis XIV", slug: "louis-xiv" },
      { name: "Frederick the Great", slug: "frederick-the-great" },
      { name: "Otto von Bismarck", slug: "otto-von-bismarck" },
      { name: "Theodore Roosevelt", slug: "theodore-roosevelt" },
      { name: "Indira Gandhi", slug: "indira-gandhi" },
      { name: "Margaret Thatcher", slug: "margaret-thatcher" },
      { name: "Nelson Mandela (Leader)", slug: "nelson-mandela-leader" },
      { name: "Angela Merkel", slug: "angela-merkel" },
      { name: "Deng Xiaoping", slug: "deng-xiaoping" },
      { name: "Lee Kuan Yew", slug: "lee-kuan-yew" },
      { name: "Barack Obama", slug: "barack-obama" },
    ],
    'artists': [
      { name: "Pablo Picasso", slug: "pablo-picasso" },
      { name: "Vincent van Gogh", slug: "vincent-van-gogh" },
      { name: "Claude Monet", slug: "claude-monet" },
      { name: "Rembrandt", slug: "rembrandt" },
      { name: "Salvador Dalí", slug: "salvador-dali" },
      { name: "Frida Kahlo", slug: "frida-kahlo" },
      { name: "Andy Warhol", slug: "andy-warhol" },
      { name: "Georgia O'Keeffe", slug: "georgia-okeeffe" },
      { name: "Banksy", slug: "banksy" },
      { name: "Raphael", slug: "raphael-artist" },
      { name: "Caravaggio", slug: "caravaggio" },
      { name: "Jackson Pollock", slug: "jackson-pollock" },
      { name: "Henri Matisse", slug: "henri-matisse" },
      { name: "Auguste Rodin", slug: "auguste-rodin" },
      { name: "M.C. Escher", slug: "mc-escher" },
    ],
    'writers': [
      { name: "William Shakespeare", slug: "william-shakespeare" },
      { name: "Jane Austen", slug: "jane-austen" },
      { name: "Charles Dickens", slug: "charles-dickens" },
      { name: "Mark Twain", slug: "mark-twain" },
      { name: "Ernest Hemingway", slug: "ernest-hemingway" },
      { name: "F. Scott Fitzgerald", slug: "f-scott-fitzgerald" },
      { name: "Leo Tolstoy", slug: "leo-tolstoy" },
      { name: "Fyodor Dostoevsky", slug: "fyodor-dostoevsky" },
      { name: "Virginia Woolf", slug: "virginia-woolf" },
      { name: "George Orwell", slug: "george-orwell" },
      { name: "Edgar Allan Poe", slug: "edgar-allan-poe" },
      { name: "Agatha Christie", slug: "agatha-christie" },
      { name: "J.R.R. Tolkien", slug: "jrr-tolkien" },
      { name: "Gabriel García Márquez", slug: "gabriel-garcia-marquez" },
      { name: "Rabindranath Tagore", slug: "rabindranath-tagore" },
    ],
    'musicians': [
      { name: "Ludwig van Beethoven", slug: "beethoven" },
      { name: "Wolfgang Amadeus Mozart", slug: "mozart" },
      { name: "Johann Sebastian Bach", slug: "js-bach" },
      { name: "The Beatles", slug: "the-beatles" },
      { name: "Elvis Presley", slug: "elvis-presley" },
      { name: "Michael Jackson", slug: "michael-jackson" },
      { name: "Madonna", slug: "madonna" },
      { name: "Bob Dylan", slug: "bob-dylan" },
      { name: "Freddie Mercury", slug: "freddie-mercury" },
      { name: "David Bowie", slug: "david-bowie" },
      { name: "Prince", slug: "prince-musician" },
      { name: "Whitney Houston", slug: "whitney-houston" },
      { name: "Beyoncé", slug: "beyonce" },
      { name: "Taylor Swift", slug: "taylor-swift" },
      { name: "A.R. Rahman", slug: "ar-rahman" },
    ],
    'actors': [
      { name: "Marilyn Monroe", slug: "marilyn-monroe" },
      { name: "Charlie Chaplin", slug: "charlie-chaplin" },
      { name: "Audrey Hepburn", slug: "audrey-hepburn" },
      { name: "Marlon Brando", slug: "marlon-brando" },
      { name: "Katharine Hepburn", slug: "katharine-hepburn" },
      { name: "Humphrey Bogart", slug: "humphrey-bogart" },
      { name: "Meryl Streep", slug: "meryl-streep" },
      { name: "Tom Hanks", slug: "tom-hanks" },
      { name: "Leonardo DiCaprio", slug: "leonardo-dicaprio" },
      { name: "Robert De Niro", slug: "robert-de-niro" },
      { name: "Al Pacino", slug: "al-pacino" },
      { name: "Denzel Washington", slug: "denzel-washington" },
      { name: "Cate Blanchett", slug: "cate-blanchett" },
      { name: "Shah Rukh Khan", slug: "shah-rukh-khan" },
      { name: "Amitabh Bachchan", slug: "amitabh-bachchan" },
    ],
    'activists': [
      { name: "Rosa Parks", slug: "rosa-parks" },
      { name: "Harriet Tubman", slug: "harriet-tubman" },
      { name: "Emmeline Pankhurst", slug: "emmeline-pankhurst" },
      { name: "Cesar Chavez", slug: "cesar-chavez" },
      { name: "Malala Yousafzai", slug: "malala-yousafzai" },
      { name: "Greta Thunberg", slug: "greta-thunberg" },
      { name: "Mother Teresa", slug: "mother-teresa" },
      { name: "Desmond Tutu", slug: "desmond-tutu" },
      { name: "Harvey Milk", slug: "harvey-milk" },
      { name: "Frederick Douglass", slug: "frederick-douglass" },
      { name: "Susan B. Anthony", slug: "susan-b-anthony" },
      { name: "Wangari Maathai", slug: "wangari-maathai" },
      { name: "Dalai Lama", slug: "dalai-lama" },
      { name: "Aung San Suu Kyi", slug: "aung-san-suu-kyi" },
      { name: "Helen Keller", slug: "helen-keller" },
    ],
    'entrepreneurs': [
      { name: "Andrew Carnegie", slug: "andrew-carnegie" },
      { name: "John D. Rockefeller", slug: "john-rockefeller" },
      { name: "J.P. Morgan", slug: "jp-morgan" },
      { name: "Walt Disney", slug: "walt-disney" },
      { name: "Oprah Winfrey", slug: "oprah-winfrey" },
      { name: "Warren Buffett", slug: "warren-buffett" },
      { name: "Jeff Bezos", slug: "jeff-bezos" },
      { name: "Mark Zuckerberg", slug: "mark-zuckerberg" },
      { name: "Jack Ma", slug: "jack-ma" },
      { name: "Richard Branson", slug: "richard-branson" },
      { name: "Ratan Tata", slug: "ratan-tata" },
      { name: "Mukesh Ambani", slug: "mukesh-ambani" },
      { name: "Coco Chanel", slug: "coco-chanel" },
      { name: "Estée Lauder", slug: "estee-lauder" },
      { name: "Sam Walton", slug: "sam-walton" },
    ],
    'athletes': [
      { name: "Jesse Owens", slug: "jesse-owens-bio" },
      { name: "Babe Ruth", slug: "babe-ruth-bio" },
      { name: "Muhammad Ali (Bio)", slug: "muhammad-ali-bio" },
      { name: "Pelé", slug: "pele-bio" },
      { name: "Roger Federer", slug: "roger-federer-bio" },
      { name: "Sachin Tendulkar", slug: "sachin-tendulkar-bio" },
      { name: "Don Bradman", slug: "don-bradman" },
      { name: "Babe Didrikson", slug: "babe-didrikson" },
      { name: "Jackie Robinson", slug: "jackie-robinson-bio" },
      { name: "Billie Jean King", slug: "billie-jean-king" },
      { name: "Jim Thorpe", slug: "jim-thorpe" },
      { name: "Nadia Comăneci", slug: "nadia-comaneci-bio" },
      { name: "Usain Bolt", slug: "usain-bolt-bio" },
      { name: "Simone Biles", slug: "simone-biles-bio" },
      { name: "Michael Phelps", slug: "michael-phelps-bio" },
    ],
  },

  'inventions': {
    'ancient': [
      { name: "The Wheel", slug: "the-wheel" },
      { name: "Writing Systems", slug: "writing-systems" },
      { name: "Paper", slug: "paper-invention" },
      { name: "Compass", slug: "compass-invention" },
      { name: "Gunpowder", slug: "gunpowder-invention" },
      { name: "Printing (Block)", slug: "block-printing" },
      { name: "Bronze & Iron Age", slug: "bronze-iron-age" },
      { name: "Roman Concrete", slug: "roman-concrete" },
      { name: "Aqueducts", slug: "aqueducts" },
      { name: "Arch & Dome", slug: "arch-dome" },
      { name: "Silk Production", slug: "silk-production" },
      { name: "Glass Making", slug: "glass-making" },
      { name: "Lever & Pulley", slug: "lever-pulley" },
      { name: "Astrolabe", slug: "astrolabe" },
      { name: "Abacus", slug: "abacus" },
    ],
    'industrial': [
      { name: "Steam Engine", slug: "steam-engine" },
      { name: "Spinning Jenny", slug: "spinning-jenny" },
      { name: "Power Loom", slug: "power-loom" },
      { name: "Cotton Gin", slug: "cotton-gin" },
      { name: "Bessemer Process", slug: "bessemer-process" },
      { name: "Locomotive", slug: "locomotive" },
      { name: "Telegraph", slug: "telegraph" },
      { name: "Sewing Machine", slug: "sewing-machine" },
      { name: "Photography", slug: "photography-invention" },
      { name: "Telephone", slug: "telephone-invention" },
      { name: "Light Bulb", slug: "light-bulb" },
      { name: "Phonograph", slug: "phonograph" },
      { name: "Internal Combustion Engine", slug: "internal-combustion-engine" },
      { name: "Dynamite", slug: "dynamite" },
      { name: "Typewriter", slug: "typewriter" },
    ],
    'modern': [
      { name: "Radio", slug: "radio-invention" },
      { name: "Television", slug: "television-invention" },
      { name: "Airplane", slug: "airplane-invention" },
      { name: "Radar", slug: "radar-invention" },
      { name: "Jet Engine", slug: "jet-engine" },
      { name: "Computer", slug: "computer-invention" },
      { name: "Transistor", slug: "transistor" },
      { name: "Integrated Circuit", slug: "integrated-circuit" },
      { name: "Internet", slug: "internet-invention" },
      { name: "World Wide Web", slug: "www-invention" },
      { name: "GPS", slug: "gps-invention" },
      { name: "Smartphone", slug: "smartphone-invention" },
      { name: "3D Printing", slug: "3d-printing-invention" },
      { name: "CRISPR", slug: "crispr-invention" },
      { name: "Electric Car", slug: "electric-car-invention" },
    ],
    'medical': [
      { name: "Vaccines (Jenner)", slug: "vaccines-jenner" },
      { name: "Anesthesia", slug: "anesthesia" },
      { name: "Antiseptic Surgery", slug: "antiseptic-surgery" },
      { name: "X-Ray", slug: "x-ray-invention" },
      { name: "Penicillin", slug: "penicillin" },
      { name: "Insulin", slug: "insulin-invention" },
      { name: "Blood Transfusion", slug: "blood-transfusion" },
      { name: "Pacemaker", slug: "pacemaker" },
      { name: "MRI", slug: "mri-invention" },
      { name: "Organ Transplants", slug: "organ-transplants" },
      { name: "Artificial Heart", slug: "artificial-heart" },
      { name: "IVF", slug: "ivf-invention" },
      { name: "mRNA Vaccines", slug: "mrna-vaccines" },
      { name: "Stethoscope", slug: "stethoscope" },
      { name: "Prosthetics", slug: "prosthetics" },
    ],
    'communication': [
      { name: "Postal System", slug: "postal-system" },
      { name: "Morse Code", slug: "morse-code" },
      { name: "Fax Machine", slug: "fax-machine" },
      { name: "Email", slug: "email-invention" },
      { name: "Mobile Phone", slug: "mobile-phone-invention" },
      { name: "Text Messaging", slug: "text-messaging" },
      { name: "Social Media", slug: "social-media-invention" },
      { name: "Satellite Communication", slug: "satellite-communication" },
      { name: "Fiber Optics", slug: "fiber-optics-invention" },
      { name: "Bluetooth", slug: "bluetooth-invention" },
      { name: "WiFi", slug: "wifi-invention" },
      { name: "5G Technology", slug: "5g-technology" },
      { name: "Video Conferencing", slug: "video-conferencing" },
      { name: "Instant Messaging", slug: "instant-messaging" },
    ],
    'transportation': [
      { name: "Wheel (Transport)", slug: "wheel-transport" },
      { name: "Sailboat", slug: "sailboat" },
      { name: "Steam Locomotive", slug: "steam-locomotive" },
      { name: "Bicycle", slug: "bicycle-invention" },
      { name: "Automobile", slug: "automobile-invention" },
      { name: "Airplane", slug: "airplane" },
      { name: "Helicopter", slug: "helicopter-invention" },
      { name: "Submarine", slug: "submarine-invention" },
      { name: "Rocket", slug: "rocket-invention" },
      { name: "High-Speed Rail", slug: "high-speed-rail" },
      { name: "Maglev Train", slug: "maglev-train" },
      { name: "Hyperloop", slug: "hyperloop" },
      { name: "Self-Driving Cars", slug: "self-driving-cars" },
      { name: "Electric Vehicles", slug: "electric-vehicles-history" },
    ],
    'scientific': [
      { name: "Telescope", slug: "telescope-invention" },
      { name: "Microscope", slug: "microscope-invention" },
      { name: "Thermometer", slug: "thermometer-invention" },
      { name: "Barometer", slug: "barometer-invention" },
      { name: "Battery", slug: "battery-invention" },
      { name: "Periodic Table", slug: "periodic-table-invention" },
      { name: "Theory of Relativity", slug: "relativity-discovery" },
      { name: "DNA Structure", slug: "dna-discovery" },
      { name: "Electron Discovery", slug: "electron-discovery" },
      { name: "Radioactivity Discovery", slug: "radioactivity-discovery" },
      { name: "Higgs Boson Discovery", slug: "higgs-discovery" },
      { name: "Gravitational Waves Detection", slug: "gravitational-waves-discovery" },
      { name: "LIGO", slug: "ligo" },
      { name: "Black Hole Image", slug: "black-hole-image" },
    ],
    'everyday': [
      { name: "Zipper", slug: "zipper" },
      { name: "Safety Pin", slug: "safety-pin" },
      { name: "Velcro", slug: "velcro" },
      { name: "Microwave Oven", slug: "microwave-oven" },
      { name: "Refrigerator", slug: "refrigerator-invention" },
      { name: "Air Conditioning", slug: "air-conditioning" },
      { name: "Washing Machine", slug: "washing-machine" },
      { name: "Vacuum Cleaner", slug: "vacuum-cleaner" },
      { name: "Ballpoint Pen", slug: "ballpoint-pen" },
      { name: "Post-it Notes", slug: "post-it-notes" },
      { name: "Bubble Wrap", slug: "bubble-wrap" },
      { name: "Duct Tape", slug: "duct-tape" },
      { name: "Bar Code", slug: "bar-code" },
      { name: "QR Code", slug: "qr-code" },
      { name: "Credit Card", slug: "credit-card" },
    ],
  },

  'world-cultures': {
    'festivals': [
      { name: "Diwali", slug: "diwali" },
      { name: "Chinese New Year", slug: "chinese-new-year" },
      { name: "Christmas Traditions", slug: "christmas-traditions" },
      { name: "Hanukkah", slug: "hanukkah" },
      { name: "Eid", slug: "eid" },
      { name: "Carnival (Brazil)", slug: "carnival-brazil" },
      { name: "Oktoberfest", slug: "oktoberfest" },
      { name: "Mardi Gras", slug: "mardi-gras" },
      { name: "Holi", slug: "holi" },
      { name: "Day of the Dead", slug: "day-of-dead" },
      { name: "Thanksgiving", slug: "thanksgiving" },
      { name: "Easter Traditions", slug: "easter-traditions" },
      { name: "Japanese Festivals", slug: "japanese-festivals" },
      { name: "La Tomatina", slug: "la-tomatina" },
      { name: "Running of the Bulls", slug: "running-of-bulls" },
    ],
    'traditions': [
      { name: "Wedding Traditions", slug: "wedding-traditions" },
      { name: "Funeral Customs", slug: "funeral-customs" },
      { name: "Coming of Age Rituals", slug: "coming-of-age" },
      { name: "Tea Ceremonies", slug: "tea-ceremonies" },
      { name: "Food Traditions", slug: "food-traditions" },
      { name: "Gift-Giving Customs", slug: "gift-giving-customs" },
      { name: "Religious Practices", slug: "religious-practices" },
      { name: "Ancestor Worship", slug: "ancestor-worship" },
      { name: "Naming Traditions", slug: "naming-traditions" },
      { name: "New Year Traditions", slug: "new-year-traditions" },
      { name: "Harvest Festivals", slug: "harvest-festivals" },
      { name: "Lunar Calendar Traditions", slug: "lunar-calendar-traditions" },
      { name: "Pilgrimage Traditions", slug: "pilgrimage-traditions" },
      { name: "Tribal Customs", slug: "tribal-customs" },
    ],
    'dance': [
      { name: "Ballet", slug: "ballet" },
      { name: "Flamenco", slug: "flamenco" },
      { name: "Tango", slug: "tango" },
      { name: "Salsa", slug: "salsa-dance" },
      { name: "Bharatanatyam", slug: "bharatanatyam" },
      { name: "Hip Hop Dance", slug: "hip-hop-dance" },
      { name: "Irish Dance", slug: "irish-dance" },
      { name: "Belly Dance", slug: "belly-dance" },
      { name: "Hula", slug: "hula" },
      { name: "Kathak", slug: "kathak" },
      { name: "Kabuki", slug: "kabuki" },
      { name: "Breakdancing", slug: "breakdancing" },
      { name: "Waltz", slug: "waltz" },
      { name: "Samba", slug: "samba" },
      { name: "Traditional African Dance", slug: "african-dance" },
    ],
    'clothing': [
      { name: "Kimono", slug: "kimono" },
      { name: "Sari", slug: "sari" },
      { name: "Hanbok", slug: "hanbok" },
      { name: "Kilt", slug: "kilt" },
      { name: "Dirndl & Lederhosen", slug: "dirndl-lederhosen" },
      { name: "Cheongsam/Qipao", slug: "cheongsam" },
      { name: "Ao Dai", slug: "ao-dai" },
      { name: "Dashiki", slug: "dashiki" },
      { name: "Poncho", slug: "poncho" },
      { name: "Thobe/Dishdasha", slug: "thobe" },
      { name: "Fez", slug: "fez" },
      { name: "Turban", slug: "turban" },
      { name: "Historical Fashion", slug: "historical-fashion" },
      { name: "Military Uniforms", slug: "military-uniforms" },
      { name: "Royal Regalia", slug: "royal-regalia" },
    ],
    'indigenous': [
      { name: "Native American Cultures", slug: "native-american-cultures" },
      { name: "Aboriginal Australians", slug: "aboriginal-australians" },
      { name: "Maori Culture", slug: "maori-culture" },
      { name: "Inuit Culture", slug: "inuit-culture" },
      { name: "Amazon Tribes", slug: "amazon-tribes" },
      { name: "African Tribal Cultures", slug: "african-tribal" },
      { name: "Sami People", slug: "sami-people" },
      { name: "Tibetan Culture", slug: "tibetan-culture" },
      { name: "Ainu People", slug: "ainu-people" },
      { name: "Native Hawaiian Culture", slug: "hawaiian-culture" },
      { name: "Māori Mythology", slug: "maori-mythology" },
      { name: "Indigenous Art", slug: "indigenous-art" },
      { name: "Dreamtime (Aboriginal)", slug: "dreamtime" },
      { name: "Totem Poles", slug: "totem-poles" },
    ],
    'heritage': [
      { name: "UNESCO World Heritage Sites", slug: "unesco-sites-culture" },
      { name: "Ancient Monuments", slug: "ancient-monuments" },
      { name: "Historic Cities", slug: "historic-cities" },
      { name: "Cultural Landscapes", slug: "cultural-landscapes" },
      { name: "Living Heritage", slug: "living-heritage" },
      { name: "Endangered Languages", slug: "endangered-languages" },
      { name: "Oral Traditions", slug: "oral-traditions" },
      { name: "Folk Music", slug: "folk-music-heritage" },
      { name: "Traditional Crafts", slug: "traditional-crafts" },
      { name: "Culinary Heritage", slug: "culinary-heritage" },
      { name: "Sacred Sites", slug: "sacred-sites" },
      { name: "Archaeological Sites", slug: "archaeological-sites" },
      { name: "Museum Collections", slug: "museum-collections" },
      { name: "Cultural Preservation", slug: "cultural-preservation" },
    ],
  },
};

let added = 0;
let skipped = 0;

for (const [category, subcategories] of Object.entries(history)) {
  console.log(`\n=== ${category.toUpperCase()} ===`);

  for (const [subcategory, topics] of Object.entries(subcategories)) {
    console.log(`\n${subcategory}:`);

    for (const topic of topics) {
      if (existingSlugs.has(topic.slug)) {
        skipped++;
        continue;
      }

      ensureTopic({
        category,
        subcategory,
        slug: topic.slug,
        name: topic.name,
        source_type: 'wikipedia',
      });

      console.log(`  + ${topic.name}`);
      added++;
      existingSlugs.add(topic.slug);
    }
  }
}

console.log(`\n✓ Added: ${added} topics`);
console.log(`- Skipped: ${skipped} (already exist)`);

// Final counts
const allHistoryTopics = [
  ...getTopics('history'),
  ...getTopics('regional-history'),
  ...getTopics('military'),
  ...getTopics('famous-people'),
  ...getTopics('inventions'),
  ...getTopics('world-cultures'),
];
console.log(`\nTotal history topics: ${allHistoryTopics.length}`);
