/**
 * Seed topics for Music, Literature, Art, Food & Geography
 */

import { ensureTopic, getTopics, initRegistry } from '../src/lib/registry';

initRegistry();

const existingTopics = [
  ...getTopics('music'),
  ...getTopics('literature'),
  ...getTopics('art'),
  ...getTopics('food'),
  ...getTopics('geography'),
];
const existingSlugs = new Set(existingTopics.map(t => t.slug));

const topics: Record<string, Record<string, Array<{ name: string; slug: string }>>> = {
  'music': {
    'classical': [
      { name: "Johann Sebastian Bach", slug: "bach" },
      { name: "Wolfgang Amadeus Mozart", slug: "mozart-composer" },
      { name: "Ludwig van Beethoven", slug: "beethoven-composer" },
      { name: "Frédéric Chopin", slug: "chopin" },
      { name: "Pyotr Tchaikovsky", slug: "tchaikovsky" },
      { name: "Johannes Brahms", slug: "brahms" },
      { name: "Antonio Vivaldi", slug: "vivaldi" },
      { name: "Franz Schubert", slug: "schubert" },
      { name: "Claude Debussy", slug: "debussy" },
      { name: "Igor Stravinsky", slug: "stravinsky" },
      { name: "Famous Symphonies", slug: "famous-symphonies" },
      { name: "Opera Classics", slug: "opera-classics" },
      { name: "Classical Conductors", slug: "classical-conductors" },
      { name: "Classical Music Eras", slug: "classical-eras" },
    ],
    'rock': [
      { name: "The Beatles", slug: "beatles-band" },
      { name: "The Rolling Stones", slug: "rolling-stones" },
      { name: "Led Zeppelin", slug: "led-zeppelin" },
      { name: "Pink Floyd", slug: "pink-floyd" },
      { name: "Queen", slug: "queen-band" },
      { name: "AC/DC", slug: "acdc" },
      { name: "Nirvana", slug: "nirvana" },
      { name: "Guns N' Roses", slug: "guns-n-roses" },
      { name: "Metallica", slug: "metallica" },
      { name: "U2", slug: "u2-band" },
      { name: "The Who", slug: "the-who" },
      { name: "Aerosmith", slug: "aerosmith" },
      { name: "Foo Fighters", slug: "foo-fighters" },
      { name: "Red Hot Chili Peppers", slug: "red-hot-chili-peppers" },
      { name: "Radiohead", slug: "radiohead" },
      { name: "History of Rock", slug: "rock-history" },
    ],
    'pop': [
      { name: "Michael Jackson", slug: "mj-music" },
      { name: "Madonna", slug: "madonna-music" },
      { name: "Prince", slug: "prince-music" },
      { name: "Whitney Houston", slug: "whitney-music" },
      { name: "Britney Spears", slug: "britney-spears" },
      { name: "Taylor Swift", slug: "taylor-swift-music" },
      { name: "Beyoncé", slug: "beyonce-music" },
      { name: "Lady Gaga", slug: "lady-gaga" },
      { name: "Rihanna", slug: "rihanna" },
      { name: "Adele", slug: "adele" },
      { name: "Ed Sheeran", slug: "ed-sheeran" },
      { name: "Bruno Mars", slug: "bruno-mars" },
      { name: "Ariana Grande", slug: "ariana-grande" },
      { name: "Justin Bieber", slug: "justin-bieber" },
      { name: "One Direction", slug: "one-direction" },
      { name: "BTS", slug: "bts" },
    ],
    'hip-hop': [
      { name: "Tupac Shakur", slug: "tupac" },
      { name: "The Notorious B.I.G.", slug: "notorious-big" },
      { name: "Jay-Z", slug: "jay-z" },
      { name: "Eminem", slug: "eminem" },
      { name: "Kanye West", slug: "kanye-west" },
      { name: "Kendrick Lamar", slug: "kendrick-lamar" },
      { name: "Drake", slug: "drake-rapper" },
      { name: "Snoop Dogg", slug: "snoop-dogg" },
      { name: "Dr. Dre", slug: "dr-dre" },
      { name: "Nas", slug: "nas" },
      { name: "Lil Wayne", slug: "lil-wayne" },
      { name: "Travis Scott", slug: "travis-scott" },
      { name: "Cardi B", slug: "cardi-b" },
      { name: "Nicki Minaj", slug: "nicki-minaj" },
      { name: "History of Hip Hop", slug: "hip-hop-history" },
      { name: "East Coast vs West Coast", slug: "east-west-hip-hop" },
    ],
    'jazz': [
      { name: "Louis Armstrong", slug: "louis-armstrong" },
      { name: "Miles Davis", slug: "miles-davis" },
      { name: "John Coltrane", slug: "john-coltrane" },
      { name: "Duke Ellington", slug: "duke-ellington" },
      { name: "Charlie Parker", slug: "charlie-parker" },
      { name: "Ella Fitzgerald", slug: "ella-fitzgerald" },
      { name: "Billie Holiday", slug: "billie-holiday" },
      { name: "Thelonious Monk", slug: "thelonious-monk" },
      { name: "Dizzy Gillespie", slug: "dizzy-gillespie" },
      { name: "B.B. King", slug: "bb-king" },
      { name: "Muddy Waters", slug: "muddy-waters" },
      { name: "Robert Johnson", slug: "robert-johnson" },
      { name: "Jazz History", slug: "jazz-history" },
      { name: "Blues Origins", slug: "blues-origins" },
    ],
    'electronic': [
      { name: "Daft Punk", slug: "daft-punk" },
      { name: "Deadmau5", slug: "deadmau5" },
      { name: "Skrillex", slug: "skrillex" },
      { name: "Calvin Harris", slug: "calvin-harris" },
      { name: "David Guetta", slug: "david-guetta" },
      { name: "Avicii", slug: "avicii" },
      { name: "Tiësto", slug: "tiesto" },
      { name: "The Chemical Brothers", slug: "chemical-brothers" },
      { name: "Kraftwerk", slug: "kraftwerk" },
      { name: "Aphex Twin", slug: "aphex-twin" },
      { name: "EDM Festivals", slug: "edm-festivals" },
      { name: "History of Electronic Music", slug: "electronic-music-history" },
      { name: "Techno & House", slug: "techno-house" },
      { name: "Dubstep", slug: "dubstep" },
    ],
    'country': [
      { name: "Johnny Cash", slug: "johnny-cash" },
      { name: "Dolly Parton", slug: "dolly-parton" },
      { name: "Willie Nelson", slug: "willie-nelson" },
      { name: "Garth Brooks", slug: "garth-brooks" },
      { name: "Shania Twain", slug: "shania-twain" },
      { name: "Taylor Swift (Country)", slug: "taylor-swift-country" },
      { name: "Carrie Underwood", slug: "carrie-underwood" },
      { name: "Tim McGraw", slug: "tim-mcgraw" },
      { name: "Blake Shelton", slug: "blake-shelton" },
      { name: "Hank Williams", slug: "hank-williams" },
      { name: "Grand Ole Opry", slug: "grand-ole-opry" },
      { name: "Country Music History", slug: "country-music-history" },
      { name: "Folk Music", slug: "folk-music" },
      { name: "Bluegrass", slug: "bluegrass" },
    ],
    'world-music': [
      { name: "Bob Marley", slug: "bob-marley" },
      { name: "Reggae Music", slug: "reggae-music" },
      { name: "Latin Music", slug: "latin-music" },
      { name: "K-Pop", slug: "k-pop" },
      { name: "J-Pop", slug: "j-pop" },
      { name: "Afrobeats", slug: "afrobeats" },
      { name: "Flamenco Music", slug: "flamenco-music" },
      { name: "Celtic Music", slug: "celtic-music" },
      { name: "Indian Classical Music", slug: "indian-classical-music" },
      { name: "Fado", slug: "fado" },
      { name: "Bossa Nova", slug: "bossa-nova" },
      { name: "Ska & Dancehall", slug: "ska-dancehall" },
      { name: "World Music Instruments", slug: "world-music-instruments" },
    ],
    'bollywood': [
      { name: "Lata Mangeshkar", slug: "lata-mangeshkar" },
      { name: "Kishore Kumar", slug: "kishore-kumar" },
      { name: "Mohammed Rafi", slug: "mohammed-rafi" },
      { name: "A.R. Rahman", slug: "ar-rahman-music" },
      { name: "R.D. Burman", slug: "rd-burman" },
      { name: "Arijit Singh", slug: "arijit-singh" },
      { name: "Shreya Ghoshal", slug: "shreya-ghoshal" },
      { name: "Sonu Nigam", slug: "sonu-nigam" },
      { name: "Asha Bhosle", slug: "asha-bhosle" },
      { name: "Bollywood Playback Singing", slug: "playback-singing" },
      { name: "Bollywood Music History", slug: "bollywood-music-history" },
      { name: "Indian Film Composers", slug: "indian-film-composers" },
    ],
    'instruments': [
      { name: "Piano", slug: "piano" },
      { name: "Guitar", slug: "guitar" },
      { name: "Violin", slug: "violin" },
      { name: "Drums", slug: "drums" },
      { name: "Saxophone", slug: "saxophone" },
      { name: "Trumpet", slug: "trumpet" },
      { name: "Flute", slug: "flute" },
      { name: "Cello", slug: "cello" },
      { name: "Harp", slug: "harp" },
      { name: "Sitar", slug: "sitar" },
      { name: "Tabla", slug: "tabla" },
      { name: "Synthesizer", slug: "synthesizer" },
      { name: "Organ", slug: "organ" },
      { name: "Ukulele", slug: "ukulele" },
    ],
    'awards': [
      { name: "Grammy Awards", slug: "grammy-awards-music" },
      { name: "MTV Video Music Awards", slug: "mtv-vmas" },
      { name: "Billboard Music Awards", slug: "billboard-awards" },
      { name: "American Music Awards", slug: "american-music-awards" },
      { name: "Brit Awards", slug: "brit-awards" },
      { name: "Rock and Roll Hall of Fame", slug: "rock-hall-of-fame" },
      { name: "Grammy Album of the Year", slug: "grammy-album-year" },
      { name: "Eurovision", slug: "eurovision" },
      { name: "Filmfare Music Awards", slug: "filmfare-music-awards" },
      { name: "Best-Selling Artists Ever", slug: "best-selling-artists" },
    ],
  },

  'literature': {
    'classics': [
      { name: "Pride and Prejudice", slug: "pride-and-prejudice" },
      { name: "Jane Eyre", slug: "jane-eyre" },
      { name: "Wuthering Heights", slug: "wuthering-heights" },
      { name: "Great Expectations", slug: "great-expectations" },
      { name: "Oliver Twist", slug: "oliver-twist" },
      { name: "War and Peace", slug: "war-and-peace" },
      { name: "Anna Karenina", slug: "anna-karenina" },
      { name: "Crime and Punishment", slug: "crime-and-punishment" },
      { name: "The Brothers Karamazov", slug: "brothers-karamazov" },
      { name: "Don Quixote", slug: "don-quixote" },
      { name: "Moby-Dick", slug: "moby-dick" },
      { name: "The Scarlet Letter", slug: "scarlet-letter" },
      { name: "Les Misérables", slug: "les-miserables" },
      { name: "The Count of Monte Cristo", slug: "count-of-monte-cristo" },
      { name: "1984", slug: "1984-orwell" },
      { name: "Brave New World", slug: "brave-new-world" },
    ],
    'authors': [
      { name: "William Shakespeare", slug: "shakespeare-author" },
      { name: "Jane Austen", slug: "jane-austen-author" },
      { name: "Charles Dickens", slug: "charles-dickens-author" },
      { name: "Mark Twain", slug: "mark-twain-author" },
      { name: "Ernest Hemingway", slug: "hemingway-author" },
      { name: "Virginia Woolf", slug: "virginia-woolf-author" },
      { name: "Franz Kafka", slug: "franz-kafka" },
      { name: "James Joyce", slug: "james-joyce" },
      { name: "Oscar Wilde", slug: "oscar-wilde" },
      { name: "Emily Dickinson", slug: "emily-dickinson" },
      { name: "Toni Morrison", slug: "toni-morrison" },
      { name: "Gabriel García Márquez", slug: "garcia-marquez-author" },
      { name: "Haruki Murakami", slug: "haruki-murakami" },
      { name: "Stephen King", slug: "stephen-king" },
      { name: "J.K. Rowling", slug: "jk-rowling" },
    ],
    'fantasy-scifi': [
      { name: "The Lord of the Rings", slug: "lotr-books" },
      { name: "Harry Potter Series", slug: "harry-potter-books" },
      { name: "A Song of Ice and Fire", slug: "asoiaf" },
      { name: "The Chronicles of Narnia", slug: "narnia-books" },
      { name: "Dune", slug: "dune-books" },
      { name: "Foundation Series", slug: "foundation-books" },
      { name: "The Hitchhiker's Guide", slug: "hitchhikers-guide" },
      { name: "Ender's Game", slug: "enders-game" },
      { name: "The Wheel of Time", slug: "wheel-of-time" },
      { name: "Discworld", slug: "discworld" },
      { name: "The Witcher Books", slug: "witcher-books" },
      { name: "Mistborn", slug: "mistborn" },
      { name: "Neuromancer", slug: "neuromancer" },
      { name: "2001: A Space Odyssey (Book)", slug: "2001-book" },
      { name: "I, Robot", slug: "i-robot" },
    ],
    'mystery': [
      { name: "Sherlock Holmes", slug: "sherlock-holmes-books" },
      { name: "Agatha Christie Novels", slug: "agatha-christie-novels" },
      { name: "Hercule Poirot", slug: "hercule-poirot" },
      { name: "Miss Marple", slug: "miss-marple" },
      { name: "The Girl with the Dragon Tattoo", slug: "girl-dragon-tattoo" },
      { name: "Gone Girl", slug: "gone-girl-book" },
      { name: "The Da Vinci Code", slug: "da-vinci-code" },
      { name: "In Cold Blood", slug: "in-cold-blood" },
      { name: "The Maltese Falcon", slug: "maltese-falcon" },
      { name: "Raymond Chandler Novels", slug: "raymond-chandler" },
      { name: "James Patterson Books", slug: "james-patterson" },
      { name: "Lee Child (Jack Reacher)", slug: "jack-reacher-books" },
      { name: "Nordic Noir", slug: "nordic-noir" },
    ],
    'poetry': [
      { name: "William Wordsworth", slug: "wordsworth" },
      { name: "John Keats", slug: "john-keats" },
      { name: "Percy Bysshe Shelley", slug: "percy-shelley" },
      { name: "Lord Byron", slug: "lord-byron" },
      { name: "Robert Frost", slug: "robert-frost" },
      { name: "Walt Whitman", slug: "walt-whitman" },
      { name: "Emily Dickinson (Poetry)", slug: "dickinson-poetry" },
      { name: "T.S. Eliot", slug: "ts-eliot" },
      { name: "Maya Angelou", slug: "maya-angelou" },
      { name: "Sylvia Plath", slug: "sylvia-plath" },
      { name: "Pablo Neruda", slug: "pablo-neruda" },
      { name: "Rumi", slug: "rumi" },
      { name: "Rabindranath Tagore (Poetry)", slug: "tagore-poetry" },
      { name: "Haiku Masters", slug: "haiku-masters" },
      { name: "Sonnets", slug: "sonnets" },
    ],
    'non-fiction': [
      { name: "Sapiens", slug: "sapiens" },
      { name: "A Brief History of Time", slug: "brief-history-time" },
      { name: "The Diary of Anne Frank", slug: "anne-frank" },
      { name: "Autobiography of Malcolm X", slug: "malcolm-x-autobiography" },
      { name: "Long Walk to Freedom", slug: "long-walk-freedom" },
      { name: "The Art of War", slug: "art-of-war-book" },
      { name: "Thinking, Fast and Slow", slug: "thinking-fast-slow" },
      { name: "Outliers", slug: "outliers" },
      { name: "Freakonomics", slug: "freakonomics" },
      { name: "The Power of Habit", slug: "power-of-habit" },
      { name: "Atomic Habits", slug: "atomic-habits" },
      { name: "Silent Spring", slug: "silent-spring" },
      { name: "The Origin of Species", slug: "origin-of-species" },
      { name: "Guns, Germs, and Steel", slug: "guns-germs-steel" },
    ],
    'childrens': [
      { name: "Alice's Adventures in Wonderland", slug: "alice-wonderland" },
      { name: "The Adventures of Tom Sawyer", slug: "tom-sawyer" },
      { name: "Charlotte's Web", slug: "charlottes-web" },
      { name: "Winnie-the-Pooh", slug: "winnie-the-pooh" },
      { name: "The Little Prince", slug: "little-prince" },
      { name: "Roald Dahl Books", slug: "roald-dahl" },
      { name: "Dr. Seuss Books", slug: "dr-seuss" },
      { name: "Diary of a Wimpy Kid", slug: "wimpy-kid" },
      { name: "Percy Jackson Series", slug: "percy-jackson-books" },
      { name: "Goosebumps", slug: "goosebumps" },
      { name: "The Hunger Games Books", slug: "hunger-games-books" },
      { name: "Matilda", slug: "matilda" },
      { name: "The BFG", slug: "the-bfg" },
      { name: "Where the Wild Things Are", slug: "wild-things" },
    ],
    'awards': [
      { name: "Nobel Prize in Literature", slug: "nobel-literature-award" },
      { name: "Pulitzer Prize (Fiction)", slug: "pulitzer-fiction" },
      { name: "Booker Prize", slug: "booker-prize" },
      { name: "National Book Award", slug: "national-book-award" },
      { name: "Hugo Awards", slug: "hugo-awards" },
      { name: "Nebula Awards", slug: "nebula-awards" },
      { name: "Newbery Medal", slug: "newbery-medal" },
      { name: "Caldecott Medal", slug: "caldecott-medal" },
      { name: "Edgar Awards", slug: "edgar-awards" },
      { name: "PEN Awards", slug: "pen-awards" },
    ],
    'literary-movements': [
      { name: "Romanticism", slug: "romanticism-literature" },
      { name: "Victorian Literature", slug: "victorian-literature" },
      { name: "Modernism", slug: "modernism-literature" },
      { name: "Postmodernism", slug: "postmodernism-literature" },
      { name: "Realism", slug: "realism-literature" },
      { name: "Naturalism", slug: "naturalism-literature" },
      { name: "Beat Generation", slug: "beat-generation" },
      { name: "Harlem Renaissance", slug: "harlem-renaissance" },
      { name: "Magical Realism", slug: "magical-realism" },
      { name: "Gothic Literature", slug: "gothic-literature" },
      { name: "Existentialism in Literature", slug: "existentialism-lit" },
      { name: "Transcendentalism", slug: "transcendentalism" },
    ],
  },

  'art': {
    'painting': [
      { name: "Mona Lisa", slug: "mona-lisa" },
      { name: "The Starry Night", slug: "starry-night" },
      { name: "The Last Supper", slug: "last-supper" },
      { name: "The Scream", slug: "the-scream" },
      { name: "Girl with a Pearl Earring", slug: "girl-pearl-earring" },
      { name: "The Birth of Venus", slug: "birth-of-venus" },
      { name: "Guernica", slug: "guernica" },
      { name: "The Persistence of Memory", slug: "persistence-of-memory" },
      { name: "American Gothic", slug: "american-gothic" },
      { name: "The Night Watch", slug: "night-watch" },
      { name: "Water Lilies", slug: "water-lilies" },
      { name: "The Kiss (Klimt)", slug: "the-kiss-klimt" },
      { name: "Las Meninas", slug: "las-meninas" },
      { name: "The Creation of Adam", slug: "creation-of-adam" },
    ],
    'artists': [
      { name: "Leonardo da Vinci", slug: "da-vinci-artist" },
      { name: "Michelangelo", slug: "michelangelo-artist" },
      { name: "Vincent van Gogh", slug: "van-gogh-artist" },
      { name: "Pablo Picasso", slug: "picasso-artist" },
      { name: "Claude Monet", slug: "monet-artist" },
      { name: "Rembrandt", slug: "rembrandt-artist" },
      { name: "Salvador Dalí", slug: "dali-artist" },
      { name: "Frida Kahlo", slug: "frida-kahlo-artist" },
      { name: "Andy Warhol", slug: "warhol-artist" },
      { name: "Georgia O'Keeffe", slug: "okeeffe-artist" },
      { name: "Jackson Pollock", slug: "pollock-artist" },
      { name: "Henri Matisse", slug: "matisse-artist" },
      { name: "Gustav Klimt", slug: "klimt-artist" },
      { name: "Johannes Vermeer", slug: "vermeer-artist" },
    ],
    'art-movements': [
      { name: "Renaissance Art", slug: "renaissance-art-movement" },
      { name: "Baroque", slug: "baroque-art" },
      { name: "Impressionism", slug: "impressionism" },
      { name: "Post-Impressionism", slug: "post-impressionism" },
      { name: "Expressionism", slug: "expressionism" },
      { name: "Cubism", slug: "cubism" },
      { name: "Surrealism", slug: "surrealism" },
      { name: "Abstract Expressionism", slug: "abstract-expressionism" },
      { name: "Pop Art", slug: "pop-art" },
      { name: "Minimalism", slug: "minimalism-art" },
      { name: "Art Nouveau", slug: "art-nouveau" },
      { name: "Art Deco", slug: "art-deco" },
      { name: "Dadaism", slug: "dadaism" },
      { name: "Romanticism (Art)", slug: "romanticism-art" },
    ],
    'sculpture': [
      { name: "David (Michelangelo)", slug: "david-sculpture" },
      { name: "The Thinker", slug: "the-thinker" },
      { name: "Venus de Milo", slug: "venus-de-milo" },
      { name: "Pietà", slug: "pieta" },
      { name: "Statue of Liberty", slug: "statue-of-liberty" },
      { name: "Christ the Redeemer", slug: "christ-redeemer" },
      { name: "Terracotta Warriors", slug: "terracotta-warriors" },
      { name: "Mount Rushmore", slug: "mount-rushmore" },
      { name: "Auguste Rodin", slug: "rodin-sculptor" },
      { name: "Greek Sculpture", slug: "greek-sculpture" },
      { name: "Roman Sculpture", slug: "roman-sculpture" },
      { name: "Modern Sculpture", slug: "modern-sculpture" },
    ],
    'architecture': [
      { name: "Gothic Architecture", slug: "gothic-architecture" },
      { name: "Romanesque Architecture", slug: "romanesque-architecture" },
      { name: "Baroque Architecture", slug: "baroque-architecture" },
      { name: "Art Deco Architecture", slug: "art-deco-architecture" },
      { name: "Modernist Architecture", slug: "modernist-architecture" },
      { name: "Frank Lloyd Wright", slug: "frank-lloyd-wright" },
      { name: "Le Corbusier", slug: "le-corbusier" },
      { name: "Zaha Hadid", slug: "zaha-hadid" },
      { name: "Famous Cathedrals", slug: "famous-cathedrals" },
      { name: "Skyscrapers", slug: "skyscrapers" },
      { name: "Ancient Architecture", slug: "ancient-architecture" },
      { name: "Islamic Architecture", slug: "islamic-architecture" },
      { name: "Japanese Architecture", slug: "japanese-architecture" },
      { name: "Pyramids of Giza", slug: "pyramids-giza" },
    ],
    'museums': [
      { name: "The Louvre", slug: "the-louvre" },
      { name: "Metropolitan Museum of Art", slug: "met-museum" },
      { name: "British Museum", slug: "british-museum" },
      { name: "Vatican Museums", slug: "vatican-museums" },
      { name: "Uffizi Gallery", slug: "uffizi-gallery" },
      { name: "Hermitage Museum", slug: "hermitage-museum" },
      { name: "MoMA", slug: "moma" },
      { name: "Guggenheim", slug: "guggenheim" },
      { name: "Rijksmuseum", slug: "rijksmuseum" },
      { name: "Prado Museum", slug: "prado-museum" },
      { name: "National Gallery London", slug: "national-gallery-london" },
      { name: "Smithsonian Museums", slug: "smithsonian" },
    ],
    'photography': [
      { name: "Ansel Adams", slug: "ansel-adams" },
      { name: "Henri Cartier-Bresson", slug: "cartier-bresson" },
      { name: "Dorothea Lange", slug: "dorothea-lange" },
      { name: "Annie Leibovitz", slug: "annie-leibovitz" },
      { name: "Steve McCurry", slug: "steve-mccurry" },
      { name: "History of Photography", slug: "photography-history" },
      { name: "Street Photography", slug: "street-photography" },
      { name: "Portrait Photography", slug: "portrait-photography" },
      { name: "Landscape Photography", slug: "landscape-photography" },
      { name: "War Photography", slug: "war-photography" },
      { name: "National Geographic Photos", slug: "natgeo-photos" },
      { name: "Iconic Photographs", slug: "iconic-photographs" },
    ],
    'digital-art': [
      { name: "Digital Painting", slug: "digital-painting" },
      { name: "3D Art & Modeling", slug: "3d-art-modeling" },
      { name: "NFT Art", slug: "nft-art" },
      { name: "Concept Art", slug: "concept-art" },
      { name: "Game Art", slug: "game-art" },
      { name: "Pixel Art", slug: "pixel-art" },
      { name: "Digital Illustration", slug: "digital-illustration" },
      { name: "AI-Generated Art", slug: "ai-generated-art" },
      { name: "Motion Graphics", slug: "motion-graphics" },
      { name: "VFX & CGI", slug: "vfx-cgi" },
      { name: "Digital Art Tools", slug: "digital-art-tools" },
      { name: "Famous Digital Artists", slug: "digital-artists" },
    ],
  },

  'food': {
    'cuisines': [
      { name: "Italian Cuisine", slug: "italian-cuisine" },
      { name: "French Cuisine", slug: "french-cuisine" },
      { name: "Chinese Cuisine", slug: "chinese-cuisine" },
      { name: "Japanese Cuisine", slug: "japanese-cuisine" },
      { name: "Indian Cuisine", slug: "indian-cuisine" },
      { name: "Mexican Cuisine", slug: "mexican-cuisine" },
      { name: "Thai Cuisine", slug: "thai-cuisine" },
      { name: "Mediterranean Cuisine", slug: "mediterranean-cuisine" },
      { name: "Korean Cuisine", slug: "korean-cuisine" },
      { name: "Vietnamese Cuisine", slug: "vietnamese-cuisine" },
      { name: "Spanish Cuisine", slug: "spanish-cuisine" },
      { name: "Greek Cuisine", slug: "greek-cuisine" },
      { name: "Middle Eastern Cuisine", slug: "middle-eastern-cuisine" },
      { name: "American Cuisine", slug: "american-cuisine" },
      { name: "African Cuisines", slug: "african-cuisines" },
    ],
    'cooking': [
      { name: "Baking Basics", slug: "baking-basics" },
      { name: "Grilling & BBQ", slug: "grilling-bbq" },
      { name: "Sous Vide", slug: "sous-vide" },
      { name: "Fermentation", slug: "fermentation-cooking" },
      { name: "Knife Skills", slug: "knife-skills" },
      { name: "Sauces & Stocks", slug: "sauces-stocks" },
      { name: "Pastry Techniques", slug: "pastry-techniques" },
      { name: "Smoking & Curing", slug: "smoking-curing" },
      { name: "Molecular Gastronomy", slug: "molecular-gastronomy" },
      { name: "Wok Cooking", slug: "wok-cooking" },
      { name: "Bread Making", slug: "bread-making" },
      { name: "Sushi Making", slug: "sushi-making" },
    ],
    'famous-chefs': [
      { name: "Gordon Ramsay", slug: "gordon-ramsay" },
      { name: "Julia Child", slug: "julia-child" },
      { name: "Anthony Bourdain", slug: "anthony-bourdain" },
      { name: "Jamie Oliver", slug: "jamie-oliver" },
      { name: "Wolfgang Puck", slug: "wolfgang-puck" },
      { name: "Thomas Keller", slug: "thomas-keller" },
      { name: "Massimo Bottura", slug: "massimo-bottura" },
      { name: "René Redzepi", slug: "rene-redzepi" },
      { name: "Heston Blumenthal", slug: "heston-blumenthal" },
      { name: "Ferran Adrià", slug: "ferran-adria" },
      { name: "Alice Waters", slug: "alice-waters" },
      { name: "Sanjeev Kapoor", slug: "sanjeev-kapoor" },
    ],
    'beverages': [
      { name: "Coffee", slug: "coffee" },
      { name: "Tea Varieties", slug: "tea-varieties" },
      { name: "Wine", slug: "wine" },
      { name: "Beer", slug: "beer" },
      { name: "Whiskey & Bourbon", slug: "whiskey-bourbon" },
      { name: "Cocktails", slug: "cocktails" },
      { name: "Sake", slug: "sake" },
      { name: "Champagne", slug: "champagne" },
      { name: "Tequila & Mezcal", slug: "tequila-mezcal" },
      { name: "Non-Alcoholic Drinks", slug: "non-alcoholic-drinks" },
      { name: "Smoothies & Juices", slug: "smoothies-juices" },
      { name: "History of Alcohol", slug: "alcohol-history" },
    ],
    'desserts': [
      { name: "Chocolate", slug: "chocolate" },
      { name: "Ice Cream", slug: "ice-cream" },
      { name: "Cakes", slug: "cakes" },
      { name: "Pastries", slug: "pastries" },
      { name: "Cookies & Biscuits", slug: "cookies-biscuits" },
      { name: "Pies & Tarts", slug: "pies-tarts" },
      { name: "French Desserts", slug: "french-desserts" },
      { name: "Italian Desserts", slug: "italian-desserts" },
      { name: "Asian Desserts", slug: "asian-desserts" },
      { name: "Indian Sweets", slug: "indian-sweets" },
      { name: "Candy & Confectionery", slug: "candy-confectionery" },
      { name: "Cheesecake", slug: "cheesecake" },
    ],
    'street-food': [
      { name: "Street Food of India", slug: "indian-street-food" },
      { name: "Street Food of Thailand", slug: "thai-street-food" },
      { name: "Street Food of Mexico", slug: "mexican-street-food" },
      { name: "Street Food of Japan", slug: "japanese-street-food" },
      { name: "Street Food of Vietnam", slug: "vietnamese-street-food" },
      { name: "Street Food of Korea", slug: "korean-street-food" },
      { name: "American Street Food", slug: "american-street-food" },
      { name: "Middle Eastern Street Food", slug: "middle-eastern-street-food" },
      { name: "Night Markets", slug: "night-markets" },
      { name: "Food Trucks", slug: "food-trucks" },
      { name: "Hawker Centres", slug: "hawker-centres" },
    ],
    'food-history': [
      { name: "History of Pizza", slug: "pizza-history" },
      { name: "History of Sushi", slug: "sushi-history" },
      { name: "History of Bread", slug: "bread-history" },
      { name: "History of Spices", slug: "spices-history" },
      { name: "History of Chocolate", slug: "chocolate-history" },
      { name: "History of Coffee", slug: "coffee-history" },
      { name: "History of Tea", slug: "tea-history" },
      { name: "History of Wine", slug: "wine-history" },
      { name: "Medieval Food", slug: "medieval-food" },
      { name: "Ancient Roman Food", slug: "roman-food" },
      { name: "Food in World Wars", slug: "food-world-wars" },
      { name: "Evolution of Fast Food", slug: "fast-food-history" },
    ],
    'restaurants': [
      { name: "Michelin Star Restaurants", slug: "michelin-restaurants" },
      { name: "World's Best Restaurants", slug: "worlds-best-restaurants" },
      { name: "Famous Restaurant Chains", slug: "restaurant-chains" },
      { name: "Historic Restaurants", slug: "historic-restaurants" },
      { name: "Fine Dining", slug: "fine-dining" },
      { name: "Celebrity Chef Restaurants", slug: "celebrity-chef-restaurants" },
      { name: "Fast Food Giants", slug: "fast-food-giants" },
      { name: "McDonald's History", slug: "mcdonalds-history" },
      { name: "Starbucks History", slug: "starbucks-history" },
      { name: "Restaurant Industry", slug: "restaurant-industry" },
    ],
  },

  'geography': {
    'countries': [
      { name: "United States", slug: "usa-geography" },
      { name: "China", slug: "china-geography" },
      { name: "India", slug: "india-geography" },
      { name: "Russia", slug: "russia-geography" },
      { name: "Brazil", slug: "brazil-geography" },
      { name: "Australia", slug: "australia-geography" },
      { name: "Canada", slug: "canada-geography" },
      { name: "United Kingdom", slug: "uk-geography" },
      { name: "Japan", slug: "japan-geography" },
      { name: "Germany", slug: "germany-geography" },
      { name: "France", slug: "france-geography" },
      { name: "Italy", slug: "italy-geography" },
      { name: "South Africa", slug: "south-africa-geography" },
      { name: "Mexico", slug: "mexico-geography" },
      { name: "Indonesia", slug: "indonesia-geography" },
    ],
    'capitals': [
      { name: "European Capitals", slug: "european-capitals" },
      { name: "Asian Capitals", slug: "asian-capitals" },
      { name: "African Capitals", slug: "african-capitals" },
      { name: "South American Capitals", slug: "south-american-capitals" },
      { name: "North American Capitals", slug: "north-american-capitals" },
      { name: "Middle Eastern Capitals", slug: "middle-eastern-capitals" },
      { name: "Most Populous Cities", slug: "most-populous-cities" },
      { name: "Global Financial Centers", slug: "financial-centers" },
      { name: "Historic Capital Cities", slug: "historic-capitals" },
      { name: "City Nicknames", slug: "city-nicknames" },
      { name: "Megacities", slug: "megacities" },
      { name: "World's Oldest Cities", slug: "oldest-cities" },
    ],
    'continents': [
      { name: "Africa", slug: "africa-continent" },
      { name: "Asia", slug: "asia-continent" },
      { name: "Europe", slug: "europe-continent" },
      { name: "North America", slug: "north-america-continent" },
      { name: "South America", slug: "south-america-continent" },
      { name: "Australia/Oceania", slug: "oceania-continent" },
      { name: "Antarctica", slug: "antarctica" },
      { name: "Continental Drift", slug: "continental-drift-geo" },
      { name: "Tectonic Plates", slug: "tectonic-plates-geo" },
      { name: "Supercontinents", slug: "supercontinents" },
    ],
    'mountains': [
      { name: "Mount Everest", slug: "mount-everest" },
      { name: "K2", slug: "k2" },
      { name: "The Himalayas", slug: "himalayas" },
      { name: "The Alps", slug: "alps" },
      { name: "The Andes", slug: "andes" },
      { name: "Rocky Mountains", slug: "rocky-mountains" },
      { name: "Mount Kilimanjaro", slug: "kilimanjaro" },
      { name: "Mount Fuji", slug: "mount-fuji" },
      { name: "Matterhorn", slug: "matterhorn" },
      { name: "Seven Summits", slug: "seven-summits" },
      { name: "Mountain Climbing", slug: "mountain-climbing" },
      { name: "Volcanic Mountains", slug: "volcanic-mountains" },
    ],
    'rivers-lakes': [
      { name: "The Nile", slug: "nile-river" },
      { name: "The Amazon", slug: "amazon-river" },
      { name: "The Ganges", slug: "ganges-river" },
      { name: "The Mississippi", slug: "mississippi-river" },
      { name: "The Yangtze", slug: "yangtze-river" },
      { name: "The Danube", slug: "danube-river" },
      { name: "The Congo", slug: "congo-river" },
      { name: "Great Lakes", slug: "great-lakes" },
      { name: "Lake Baikal", slug: "lake-baikal" },
      { name: "Caspian Sea", slug: "caspian-sea" },
      { name: "Dead Sea", slug: "dead-sea" },
      { name: "Victoria Falls", slug: "victoria-falls" },
      { name: "Niagara Falls", slug: "niagara-falls" },
    ],
    'oceans-seas': [
      { name: "Pacific Ocean", slug: "pacific-ocean" },
      { name: "Atlantic Ocean", slug: "atlantic-ocean" },
      { name: "Indian Ocean", slug: "indian-ocean" },
      { name: "Arctic Ocean", slug: "arctic-ocean" },
      { name: "Southern Ocean", slug: "southern-ocean" },
      { name: "Mediterranean Sea", slug: "mediterranean-sea" },
      { name: "Caribbean Sea", slug: "caribbean-sea" },
      { name: "South China Sea", slug: "south-china-sea" },
      { name: "Red Sea", slug: "red-sea" },
      { name: "Black Sea", slug: "black-sea" },
      { name: "Baltic Sea", slug: "baltic-sea" },
      { name: "Ocean Trenches", slug: "ocean-trenches" },
    ],
    'islands': [
      { name: "Greenland", slug: "greenland" },
      { name: "Madagascar", slug: "madagascar" },
      { name: "New Zealand", slug: "new-zealand" },
      { name: "Hawaii", slug: "hawaii" },
      { name: "Caribbean Islands", slug: "caribbean-islands" },
      { name: "Greek Islands", slug: "greek-islands" },
      { name: "Indonesian Islands", slug: "indonesian-islands" },
      { name: "Philippine Islands", slug: "philippine-islands" },
      { name: "Maldives", slug: "maldives" },
      { name: "Galápagos Islands", slug: "galapagos" },
      { name: "Iceland", slug: "iceland" },
      { name: "British Isles", slug: "british-isles" },
    ],
    'deserts': [
      { name: "Sahara Desert", slug: "sahara-desert" },
      { name: "Arabian Desert", slug: "arabian-desert" },
      { name: "Gobi Desert", slug: "gobi-desert" },
      { name: "Kalahari Desert", slug: "kalahari-desert" },
      { name: "Atacama Desert", slug: "atacama-desert" },
      { name: "Mojave Desert", slug: "mojave-desert" },
      { name: "Sonoran Desert", slug: "sonoran-desert" },
      { name: "Thar Desert", slug: "thar-desert" },
      { name: "Antarctic Desert", slug: "antarctic-desert" },
      { name: "Australian Outback", slug: "australian-outback" },
      { name: "Death Valley", slug: "death-valley" },
    ],
    'landmarks': [
      { name: "Eiffel Tower", slug: "eiffel-tower" },
      { name: "Great Wall of China", slug: "great-wall" },
      { name: "Taj Mahal", slug: "taj-mahal" },
      { name: "Colosseum", slug: "colosseum" },
      { name: "Machu Picchu", slug: "machu-picchu" },
      { name: "Petra", slug: "petra" },
      { name: "Angkor Wat", slug: "angkor-wat" },
      { name: "Stonehenge", slug: "stonehenge" },
      { name: "Great Barrier Reef", slug: "great-barrier-reef" },
      { name: "Grand Canyon", slug: "grand-canyon" },
      { name: "Golden Gate Bridge", slug: "golden-gate-bridge" },
      { name: "Burj Khalifa", slug: "burj-khalifa" },
      { name: "Sydney Opera House", slug: "sydney-opera-house" },
      { name: "Big Ben", slug: "big-ben" },
    ],
    'physical': [
      { name: "Rainforests", slug: "rainforests" },
      { name: "Tundra", slug: "tundra" },
      { name: "Grasslands", slug: "grasslands" },
      { name: "Wetlands", slug: "wetlands" },
      { name: "Caves & Caverns", slug: "caves-caverns" },
      { name: "Canyons", slug: "canyons" },
      { name: "Glaciers", slug: "glaciers" },
      { name: "Volcanoes", slug: "volcanoes-geo" },
      { name: "Geysers", slug: "geysers" },
      { name: "Fjords", slug: "fjords" },
      { name: "Deltas", slug: "deltas" },
      { name: "Atolls", slug: "atolls" },
    ],
  },
};

let added = 0;
let skipped = 0;

for (const [category, subcategories] of Object.entries(topics)) {
  console.log(`\n=== ${category.toUpperCase()} ===`);

  for (const [subcategory, topicList] of Object.entries(subcategories)) {
    console.log(`\n${subcategory}:`);

    for (const topic of topicList) {
      if (existingSlugs.has(topic.slug)) {
        skipped++;
        continue;
      }

      ensureTopic({
        category,
        subcategory,
        slug: topic.slug,
        name: topic.name,
        source_type: 'wikipedia',
      });

      console.log(`  + ${topic.name}`);
      added++;
      existingSlugs.add(topic.slug);
    }
  }
}

console.log(`\n✓ Added: ${added} topics`);
console.log(`- Skipped: ${skipped} (already exist)`);

const allTopics = [
  ...getTopics('music'),
  ...getTopics('literature'),
  ...getTopics('art'),
  ...getTopics('food'),
  ...getTopics('geography'),
];
console.log(`\nTotal topics in these categories: ${allTopics.length}`);
