/**
 * Seed sports topics for all sports categories
 */

import { ensureTopic, getTopics, initRegistry } from '../src/lib/registry';

initRegistry();

// Get existing topics to avoid duplicates
const existingTopics = [
  ...getTopics('american-sports'),
  ...getTopics('combat-sports'),
  ...getTopics('cricket'),
  ...getTopics('football'),
  ...getTopics('olympics'),
  ...getTopics('other-sports'),
];
const existingSlugs = new Set(existingTopics.map(t => t.slug));

const sports: Record<string, Record<string, Array<{ name: string; slug: string }>>> = {
  'american-sports': {
    'mlb': [
      { name: "New York Yankees", slug: "yankees" },
      { name: "Boston Red Sox", slug: "red-sox" },
      { name: "Los Angeles Dodgers", slug: "dodgers" },
      { name: "Chicago Cubs", slug: "cubs" },
      { name: "San Francisco Giants", slug: "giants-mlb" },
      { name: "St. Louis Cardinals", slug: "cardinals-mlb" },
      { name: "Atlanta Braves", slug: "braves" },
      { name: "World Series History", slug: "world-series" },
      { name: "MLB All-Star Game", slug: "mlb-all-star" },
      { name: "Baseball Hall of Fame", slug: "baseball-hall-of-fame" },
      { name: "Babe Ruth", slug: "babe-ruth" },
      { name: "Jackie Robinson", slug: "jackie-robinson" },
      { name: "MLB Records", slug: "mlb-records" },
      { name: "Baseball Rules & Strategy", slug: "baseball-rules" },
      { name: "Home Run Records", slug: "home-run-records" },
    ],
    'nba': [
      { name: "Los Angeles Lakers", slug: "lakers" },
      { name: "Boston Celtics", slug: "celtics" },
      { name: "Chicago Bulls", slug: "bulls" },
      { name: "Golden State Warriors", slug: "warriors" },
      { name: "Miami Heat", slug: "heat" },
      { name: "San Antonio Spurs", slug: "spurs-nba" },
      { name: "NBA Finals History", slug: "nba-finals" },
      { name: "NBA All-Star Weekend", slug: "nba-all-star" },
      { name: "Michael Jordan", slug: "michael-jordan" },
      { name: "LeBron James", slug: "lebron-james" },
      { name: "Kobe Bryant", slug: "kobe-bryant" },
      { name: "NBA Draft History", slug: "nba-draft" },
      { name: "NBA Records", slug: "nba-records" },
      { name: "Basketball Hall of Fame", slug: "basketball-hall-of-fame" },
      { name: "WNBA", slug: "wnba" },
    ],
    'nfl': [
      { name: "New England Patriots", slug: "patriots" },
      { name: "Dallas Cowboys", slug: "cowboys" },
      { name: "Green Bay Packers", slug: "packers" },
      { name: "Pittsburgh Steelers", slug: "steelers" },
      { name: "San Francisco 49ers", slug: "49ers" },
      { name: "Kansas City Chiefs", slug: "chiefs" },
      { name: "Tom Brady", slug: "tom-brady" },
      { name: "NFL Draft", slug: "nfl-draft" },
      { name: "NFL Records", slug: "nfl-records" },
      { name: "Pro Football Hall of Fame", slug: "pro-football-hof" },
      { name: "Monday Night Football", slug: "monday-night-football" },
      { name: "NFL Playoffs", slug: "nfl-playoffs" },
      { name: "Quarterback Legends", slug: "qb-legends" },
      { name: "NFL Rules & Strategy", slug: "nfl-rules" },
      { name: "College Football", slug: "college-football" },
    ],
    'nhl': [
      { name: "Montreal Canadiens", slug: "canadiens" },
      { name: "Toronto Maple Leafs", slug: "maple-leafs" },
      { name: "Detroit Red Wings", slug: "red-wings" },
      { name: "Boston Bruins", slug: "bruins" },
      { name: "Chicago Blackhawks", slug: "blackhawks" },
      { name: "Pittsburgh Penguins", slug: "penguins" },
      { name: "Stanley Cup History", slug: "stanley-cup" },
      { name: "Wayne Gretzky", slug: "wayne-gretzky" },
      { name: "NHL Records", slug: "nhl-records" },
      { name: "Hockey Hall of Fame", slug: "hockey-hall-of-fame" },
      { name: "NHL Playoffs", slug: "nhl-playoffs" },
      { name: "NHL Draft", slug: "nhl-draft" },
      { name: "Olympic Hockey", slug: "olympic-hockey" },
      { name: "Goaltender Legends", slug: "goaltender-legends" },
      { name: "NHL Rivalries", slug: "nhl-rivalries" },
    ],
    'super-bowl': [
      { name: "Super Bowl I-X", slug: "super-bowl-1-10" },
      { name: "Super Bowl XI-XX", slug: "super-bowl-11-20" },
      { name: "Super Bowl XXI-XXX", slug: "super-bowl-21-30" },
      { name: "Super Bowl XXXI-XL", slug: "super-bowl-31-40" },
      { name: "Super Bowl XLI-L", slug: "super-bowl-41-50" },
      { name: "Super Bowl LI-LX", slug: "super-bowl-51-60" },
      { name: "Super Bowl MVPs", slug: "super-bowl-mvps" },
      { name: "Super Bowl Halftime Shows", slug: "super-bowl-halftime" },
      { name: "Super Bowl Commercials", slug: "super-bowl-commercials" },
      { name: "Super Bowl Records", slug: "super-bowl-records" },
      { name: "Greatest Super Bowls", slug: "greatest-super-bowls" },
      { name: "Super Bowl Upsets", slug: "super-bowl-upsets" },
    ],
    'college': [
      { name: "College Football Playoff", slug: "college-football-playoff" },
      { name: "March Madness", slug: "march-madness" },
      { name: "NCAA Basketball", slug: "ncaa-basketball" },
      { name: "Heisman Trophy", slug: "heisman-trophy" },
      { name: "Rose Bowl", slug: "rose-bowl" },
      { name: "College Football Rivalries", slug: "college-football-rivalries" },
      { name: "Duke Basketball", slug: "duke-basketball" },
      { name: "Kentucky Basketball", slug: "kentucky-basketball" },
      { name: "Alabama Football", slug: "alabama-football" },
      { name: "Ohio State Football", slug: "ohio-state-football" },
      { name: "NCAA Records", slug: "ncaa-records" },
      { name: "College Sports Traditions", slug: "college-traditions" },
    ],
    'history': [
      { name: "1920s-1940s American Sports", slug: "early-american-sports" },
      { name: "1950s-1960s American Sports", slug: "50s-60s-american-sports" },
      { name: "1970s-1980s American Sports", slug: "70s-80s-american-sports" },
      { name: "1990s American Sports", slug: "90s-american-sports" },
      { name: "2000s American Sports", slug: "2000s-american-sports" },
      { name: "Sports Integration History", slug: "sports-integration" },
      { name: "ABA History", slug: "aba-history" },
      { name: "AFL-NFL Merger", slug: "afl-nfl-merger" },
      { name: "Defunct Teams", slug: "defunct-teams" },
      { name: "Stadium History", slug: "stadium-history-us" },
    ],
    'legends': [
      { name: "Muhammad Ali", slug: "muhammad-ali-sports" },
      { name: "Jim Brown", slug: "jim-brown" },
      { name: "Joe Montana", slug: "joe-montana" },
      { name: "Magic Johnson", slug: "magic-johnson" },
      { name: "Larry Bird", slug: "larry-bird" },
      { name: "Willie Mays", slug: "willie-mays" },
      { name: "Hank Aaron", slug: "hank-aaron" },
      { name: "Ted Williams", slug: "ted-williams" },
      { name: "Bill Russell", slug: "bill-russell" },
      { name: "Jerry Rice", slug: "jerry-rice" },
      { name: "Walter Payton", slug: "walter-payton" },
      { name: "Kareem Abdul-Jabbar", slug: "kareem-abdul-jabbar" },
      { name: "Shaquille O'Neal", slug: "shaquille-oneal" },
      { name: "Derek Jeter", slug: "derek-jeter" },
      { name: "Serena Williams", slug: "serena-williams-american" },
    ],
    'records': [
      { name: "Scoring Records", slug: "scoring-records-us" },
      { name: "Championship Records", slug: "championship-records" },
      { name: "Single Game Records", slug: "single-game-records" },
      { name: "Career Records", slug: "career-records-us" },
      { name: "Rookie Records", slug: "rookie-records" },
      { name: "Playoff Records", slug: "playoff-records-us" },
      { name: "Attendance Records", slug: "attendance-records" },
      { name: "Contract Records", slug: "contract-records" },
      { name: "Draft Records", slug: "draft-records" },
      { name: "Unbreakable Records", slug: "unbreakable-records" },
    ],
    'teams': [
      { name: "Most Valuable Franchises", slug: "valuable-franchises" },
      { name: "Dynasty Teams", slug: "dynasty-teams" },
      { name: "Expansion Teams", slug: "expansion-teams" },
      { name: "Team Relocations", slug: "team-relocations" },
      { name: "Iconic Team Rivalries", slug: "team-rivalries-us" },
      { name: "Championship Droughts", slug: "championship-droughts" },
      { name: "Team Name Origins", slug: "team-name-origins" },
      { name: "Historic Seasons", slug: "historic-seasons" },
      { name: "Worst Teams Ever", slug: "worst-teams-ever" },
      { name: "Team Owners", slug: "team-owners" },
    ],
  },

  'combat-sports': {
    'boxing': [
      { name: "Muhammad Ali", slug: "muhammad-ali" },
      { name: "Mike Tyson", slug: "mike-tyson" },
      { name: "Floyd Mayweather Jr.", slug: "floyd-mayweather" },
      { name: "Manny Pacquiao", slug: "manny-pacquiao" },
      { name: "Sugar Ray Leonard", slug: "sugar-ray-leonard" },
      { name: "Sugar Ray Robinson", slug: "sugar-ray-robinson" },
      { name: "Joe Louis", slug: "joe-louis" },
      { name: "Rocky Marciano", slug: "rocky-marciano" },
      { name: "Heavyweight Champions", slug: "heavyweight-champions" },
      { name: "Greatest Fights Ever", slug: "greatest-boxing-fights" },
      { name: "Boxing Weight Classes", slug: "boxing-weight-classes" },
      { name: "Boxing Hall of Fame", slug: "boxing-hall-of-fame" },
      { name: "Legendary Boxing Rivalries", slug: "boxing-rivalries" },
      { name: "Canelo Alvarez", slug: "canelo-alvarez" },
      { name: "Tyson Fury", slug: "tyson-fury" },
    ],
    'mma': [
      { name: "UFC History", slug: "ufc-history" },
      { name: "Conor McGregor", slug: "conor-mcgregor" },
      { name: "Khabib Nurmagomedov", slug: "khabib-nurmagomedov" },
      { name: "Jon Jones", slug: "jon-jones" },
      { name: "Anderson Silva", slug: "anderson-silva" },
      { name: "Georges St-Pierre", slug: "gsp" },
      { name: "Ronda Rousey", slug: "ronda-rousey" },
      { name: "Amanda Nunes", slug: "amanda-nunes" },
      { name: "UFC Weight Classes", slug: "ufc-weight-classes" },
      { name: "Greatest UFC Fights", slug: "greatest-ufc-fights" },
      { name: "UFC Champions History", slug: "ufc-champions" },
      { name: "Bellator MMA", slug: "bellator" },
      { name: "ONE Championship", slug: "one-championship" },
      { name: "Pride FC History", slug: "pride-fc" },
      { name: "UFC Hall of Fame", slug: "ufc-hall-of-fame" },
    ],
    'wwe': [
      { name: "The Rock", slug: "the-rock-wwe" },
      { name: "Stone Cold Steve Austin", slug: "stone-cold" },
      { name: "John Cena", slug: "john-cena" },
      { name: "The Undertaker", slug: "the-undertaker" },
      { name: "Hulk Hogan", slug: "hulk-hogan" },
      { name: "Ric Flair", slug: "ric-flair" },
      { name: "Shawn Michaels", slug: "shawn-michaels" },
      { name: "Triple H", slug: "triple-h" },
      { name: "WWE Championship History", slug: "wwe-championship" },
      { name: "WWE Women's Division", slug: "wwe-womens" },
      { name: "NXT", slug: "nxt" },
      { name: "Tag Team Wrestling", slug: "tag-team-wrestling" },
      { name: "WWE Attitude Era", slug: "attitude-era" },
      { name: "WWE Ruthless Aggression Era", slug: "ruthless-aggression" },
      { name: "Roman Reigns", slug: "roman-reigns" },
    ],
    'aew': [
      { name: "AEW History", slug: "aew-history" },
      { name: "AEW Champions", slug: "aew-champions" },
      { name: "Chris Jericho", slug: "chris-jericho" },
      { name: "Kenny Omega", slug: "kenny-omega" },
      { name: "The Young Bucks", slug: "young-bucks" },
      { name: "MJF", slug: "mjf" },
      { name: "Jon Moxley", slug: "jon-moxley" },
      { name: "AEW Dynamite", slug: "aew-dynamite" },
      { name: "AEW Pay-Per-Views", slug: "aew-ppvs" },
      { name: "AEW Women's Division", slug: "aew-womens" },
      { name: "AEW Tag Teams", slug: "aew-tag-teams" },
      { name: "AEW vs WWE", slug: "aew-vs-wwe" },
    ],
    'events': [
      { name: "WrestleMania History", slug: "wrestlemania-history" },
      { name: "Royal Rumble History", slug: "royal-rumble-history" },
      { name: "SummerSlam History", slug: "summerslam-history" },
      { name: "Survivor Series History", slug: "survivor-series-history" },
      { name: "Money in the Bank", slug: "money-in-the-bank" },
      { name: "Hell in a Cell Matches", slug: "hell-in-a-cell" },
      { name: "Elimination Chamber", slug: "elimination-chamber" },
      { name: "TLC Matches", slug: "tlc-matches" },
      { name: "Greatest PPV Moments", slug: "greatest-ppv-moments" },
      { name: "Historic Boxing Events", slug: "historic-boxing-events" },
      { name: "UFC PPV Events", slug: "ufc-ppv-events" },
      { name: "Combat Sports Upsets", slug: "combat-sports-upsets" },
    ],
    'championships': [
      { name: "WWE World Heavyweight Title", slug: "wwe-world-title" },
      { name: "WWE Universal Title", slug: "wwe-universal-title" },
      { name: "Intercontinental Championship", slug: "intercontinental-title" },
      { name: "United States Championship", slug: "us-championship" },
      { name: "WCW Championship History", slug: "wcw-championship" },
      { name: "ECW Championship History", slug: "ecw-championship" },
      { name: "Boxing World Titles", slug: "boxing-world-titles" },
      { name: "UFC Title History", slug: "ufc-title-history" },
      { name: "Longest Title Reigns", slug: "longest-title-reigns" },
      { name: "Title Unifications", slug: "title-unifications" },
    ],
    'classic-wrestling': [
      { name: "Bruno Sammartino", slug: "bruno-sammartino" },
      { name: "Andre the Giant", slug: "andre-the-giant" },
      { name: "Macho Man Randy Savage", slug: "randy-savage" },
      { name: "Ultimate Warrior", slug: "ultimate-warrior" },
      { name: "Bret Hart", slug: "bret-hart" },
      { name: "WCW Monday Nitro", slug: "wcw-nitro" },
      { name: "NWO", slug: "nwo" },
      { name: "ECW Original", slug: "ecw-original" },
      { name: "Monday Night Wars", slug: "monday-night-wars" },
      { name: "Territory Era Wrestling", slug: "territory-era" },
      { name: "AWA History", slug: "awa-history" },
      { name: "Wrestling Legends", slug: "wrestling-legends" },
    ],
    'boxers': [
      { name: "Oscar De La Hoya", slug: "oscar-de-la-hoya" },
      { name: "Lennox Lewis", slug: "lennox-lewis" },
      { name: "Evander Holyfield", slug: "evander-holyfield" },
      { name: "George Foreman", slug: "george-foreman" },
      { name: "Joe Frazier", slug: "joe-frazier" },
      { name: "Marvin Hagler", slug: "marvin-hagler" },
      { name: "Roberto Duran", slug: "roberto-duran" },
      { name: "Thomas Hearns", slug: "thomas-hearns" },
      { name: "Roy Jones Jr.", slug: "roy-jones-jr" },
      { name: "Bernard Hopkins", slug: "bernard-hopkins" },
      { name: "Wladimir Klitschko", slug: "wladimir-klitschko" },
      { name: "Anthony Joshua", slug: "anthony-joshua" },
      { name: "Deontay Wilder", slug: "deontay-wilder" },
      { name: "Gennady Golovkin", slug: "gennady-golovkin" },
      { name: "Terence Crawford", slug: "terence-crawford" },
    ],
    'wrestlers': [
      { name: "CM Punk", slug: "cm-punk" },
      { name: "Randy Orton", slug: "randy-orton" },
      { name: "Edge", slug: "edge-wrestler" },
      { name: "Kurt Angle", slug: "kurt-angle" },
      { name: "Eddie Guerrero", slug: "eddie-guerrero" },
      { name: "Rey Mysterio", slug: "rey-mysterio" },
      { name: "Batista", slug: "batista" },
      { name: "AJ Styles", slug: "aj-styles" },
      { name: "Seth Rollins", slug: "seth-rollins" },
      { name: "Becky Lynch", slug: "becky-lynch" },
      { name: "Charlotte Flair", slug: "charlotte-flair" },
      { name: "Sasha Banks", slug: "sasha-banks" },
      { name: "Brock Lesnar", slug: "brock-lesnar" },
      { name: "Daniel Bryan", slug: "daniel-bryan" },
      { name: "Cody Rhodes", slug: "cody-rhodes" },
    ],
    'martial-arts': [
      { name: "Brazilian Jiu-Jitsu", slug: "bjj" },
      { name: "Muay Thai", slug: "muay-thai" },
      { name: "Judo", slug: "judo" },
      { name: "Karate", slug: "karate" },
      { name: "Taekwondo", slug: "taekwondo" },
      { name: "Wrestling (Freestyle)", slug: "freestyle-wrestling" },
      { name: "Greco-Roman Wrestling", slug: "greco-roman" },
      { name: "Kickboxing", slug: "kickboxing" },
      { name: "Sambo", slug: "sambo" },
      { name: "Kung Fu", slug: "kung-fu" },
      { name: "Aikido", slug: "aikido" },
      { name: "Krav Maga", slug: "krav-maga" },
      { name: "Martial Arts Legends", slug: "martial-arts-legends" },
      { name: "Bruce Lee", slug: "bruce-lee" },
      { name: "Combat Sports History", slug: "combat-sports-history" },
    ],
  },

  'cricket': {
    'test-cricket': [
      { name: "Test Cricket Records", slug: "test-cricket-records" },
      { name: "Greatest Test Matches", slug: "greatest-test-matches" },
      { name: "Test Cricket Venues", slug: "test-cricket-venues" },
      { name: "Ashes History", slug: "ashes-history" },
      { name: "Border-Gavaskar Trophy", slug: "border-gavaskar" },
      { name: "Test Cricket Legends", slug: "test-cricket-legends" },
      { name: "Test Batting Records", slug: "test-batting-records" },
      { name: "Test Bowling Records", slug: "test-bowling-records" },
      { name: "Test Double Centuries", slug: "test-double-centuries" },
      { name: "Test Wicket Milestones", slug: "test-wicket-milestones" },
      { name: "Historic Test Series", slug: "historic-test-series" },
      { name: "Test Cricket Rivalries", slug: "test-rivalries" },
    ],
    'odi': [
      { name: "ODI Records", slug: "odi-records" },
      { name: "ODI World Cup History", slug: "odi-world-cup-history" },
      { name: "Greatest ODI Matches", slug: "greatest-odi-matches" },
      { name: "ODI Batting Records", slug: "odi-batting-records" },
      { name: "ODI Bowling Records", slug: "odi-bowling-records" },
      { name: "ODI Double Centuries", slug: "odi-double-centuries" },
      { name: "ODI Highest Totals", slug: "odi-highest-totals" },
      { name: "Champions Trophy", slug: "champions-trophy" },
      { name: "Asia Cup", slug: "asia-cup" },
      { name: "ODI Legends", slug: "odi-legends" },
    ],
    't20': [
      { name: "T20 World Cup History", slug: "t20-world-cup-history" },
      { name: "T20 Records", slug: "t20-records" },
      { name: "Fastest T20 Centuries", slug: "fastest-t20-centuries" },
      { name: "T20 Bowling Records", slug: "t20-bowling-records" },
      { name: "Greatest T20 Matches", slug: "greatest-t20-matches" },
      { name: "T20 League Cricket", slug: "t20-leagues" },
      { name: "Big Bash League", slug: "big-bash" },
      { name: "Caribbean Premier League", slug: "cpl" },
      { name: "Pakistan Super League", slug: "psl" },
      { name: "T20 Blast", slug: "t20-blast" },
      { name: "SA20", slug: "sa20" },
      { name: "T20 Power Hitters", slug: "t20-power-hitters" },
    ],
    'ipl': [
      { name: "IPL History", slug: "ipl-history" },
      { name: "Mumbai Indians", slug: "mumbai-indians" },
      { name: "Chennai Super Kings", slug: "csk" },
      { name: "Royal Challengers Bangalore", slug: "rcb" },
      { name: "Kolkata Knight Riders", slug: "kkr" },
      { name: "Delhi Capitals", slug: "delhi-capitals" },
      { name: "IPL Records", slug: "ipl-records" },
      { name: "IPL MVPs", slug: "ipl-mvps" },
      { name: "IPL Auctions", slug: "ipl-auctions" },
      { name: "Orange Cap Winners", slug: "orange-cap" },
      { name: "Purple Cap Winners", slug: "purple-cap" },
      { name: "IPL Finals", slug: "ipl-finals" },
      { name: "Most IPL Titles", slug: "most-ipl-titles" },
      { name: "IPL Controversies", slug: "ipl-controversies" },
    ],
    'world-cup': [
      { name: "1975 World Cup", slug: "wc-1975" },
      { name: "1983 World Cup", slug: "wc-1983" },
      { name: "1987 World Cup", slug: "wc-1987" },
      { name: "1992 World Cup", slug: "wc-1992" },
      { name: "1996 World Cup", slug: "wc-1996" },
      { name: "1999 World Cup", slug: "wc-1999" },
      { name: "2003 World Cup", slug: "wc-2003" },
      { name: "2007 World Cup", slug: "wc-2007" },
      { name: "2011 World Cup", slug: "wc-2011" },
      { name: "2015 World Cup", slug: "wc-2015" },
      { name: "2019 World Cup", slug: "wc-2019" },
      { name: "2023 World Cup", slug: "wc-2023" },
      { name: "World Cup Records", slug: "world-cup-records" },
      { name: "World Cup Finals", slug: "world-cup-finals" },
    ],
    'players': [
      { name: "Sachin Tendulkar", slug: "sachin-tendulkar" },
      { name: "Brian Lara", slug: "brian-lara" },
      { name: "Ricky Ponting", slug: "ricky-ponting" },
      { name: "Jacques Kallis", slug: "jacques-kallis" },
      { name: "Kumar Sangakkara", slug: "kumar-sangakkara" },
      { name: "Virat Kohli", slug: "virat-kohli" },
      { name: "MS Dhoni", slug: "ms-dhoni" },
      { name: "Rohit Sharma", slug: "rohit-sharma" },
      { name: "AB de Villiers", slug: "ab-de-villiers" },
      { name: "Shane Warne", slug: "shane-warne" },
      { name: "Muttiah Muralitharan", slug: "muttiah-muralitharan" },
      { name: "Glenn McGrath", slug: "glenn-mcgrath" },
      { name: "Wasim Akram", slug: "wasim-akram" },
      { name: "Jasprit Bumrah", slug: "jasprit-bumrah" },
      { name: "Pat Cummins", slug: "pat-cummins" },
      { name: "Kane Williamson", slug: "kane-williamson" },
      { name: "Steve Smith", slug: "steve-smith" },
      { name: "Joe Root", slug: "joe-root" },
      { name: "Babar Azam", slug: "babar-azam" },
      { name: "Ben Stokes", slug: "ben-stokes" },
    ],
    'cricket-history': [
      { name: "Origins of Cricket", slug: "origins-of-cricket" },
      { name: "Cricket in the 1800s", slug: "cricket-1800s" },
      { name: "Bodyline Series", slug: "bodyline-series" },
      { name: "Kerry Packer's World Series", slug: "world-series-cricket" },
      { name: "Cricket World Cup History", slug: "cwc-history" },
      { name: "Evolution of Cricket Rules", slug: "cricket-rules-evolution" },
      { name: "Cricket Match Fixing Scandals", slug: "cricket-scandals" },
      { name: "Women's Cricket History", slug: "womens-cricket-history" },
      { name: "Cricket's Greatest Moments", slug: "cricket-greatest-moments" },
      { name: "ICC History", slug: "icc-history" },
      { name: "Cricket Broadcasting History", slug: "cricket-broadcasting" },
      { name: "DRS and Technology in Cricket", slug: "cricket-technology" },
    ],
    'records': [
      { name: "Most International Runs", slug: "most-international-runs" },
      { name: "Most International Wickets", slug: "most-international-wickets" },
      { name: "Highest Individual Scores", slug: "highest-individual-scores" },
      { name: "Best Bowling Figures", slug: "best-bowling-figures" },
      { name: "Most Centuries", slug: "most-centuries" },
      { name: "Fastest Centuries", slug: "fastest-centuries" },
      { name: "Most Catches", slug: "most-catches-cricket" },
      { name: "Most Stumpings", slug: "most-stumpings" },
      { name: "Partnership Records", slug: "partnership-records" },
      { name: "Youngest/Oldest Records", slug: "age-records-cricket" },
      { name: "Most Matches Played", slug: "most-matches-cricket" },
      { name: "Consecutive Records", slug: "consecutive-records-cricket" },
    ],
    'venues': [
      { name: "Lord's Cricket Ground", slug: "lords" },
      { name: "Melbourne Cricket Ground", slug: "mcg" },
      { name: "Eden Gardens", slug: "eden-gardens" },
      { name: "The Oval", slug: "the-oval" },
      { name: "Sydney Cricket Ground", slug: "scg" },
      { name: "Wankhede Stadium", slug: "wankhede" },
      { name: "Adelaide Oval", slug: "adelaide-oval" },
      { name: "Headingley", slug: "headingley" },
      { name: "Newlands", slug: "newlands" },
      { name: "Galle International Stadium", slug: "galle" },
      { name: "Dubai International Stadium", slug: "dubai-stadium" },
      { name: "Historic Cricket Venues", slug: "historic-cricket-venues" },
    ],
    'teams': [
      { name: "India Cricket Team", slug: "india-cricket" },
      { name: "Australia Cricket Team", slug: "australia-cricket" },
      { name: "England Cricket Team", slug: "england-cricket" },
      { name: "Pakistan Cricket Team", slug: "pakistan-cricket" },
      { name: "South Africa Cricket Team", slug: "south-africa-cricket" },
      { name: "New Zealand Cricket Team", slug: "new-zealand-cricket" },
      { name: "West Indies Cricket Team", slug: "west-indies-cricket" },
      { name: "Sri Lanka Cricket Team", slug: "sri-lanka-cricket" },
      { name: "Bangladesh Cricket Team", slug: "bangladesh-cricket" },
      { name: "Afghanistan Cricket Team", slug: "afghanistan-cricket" },
      { name: "Ireland Cricket Team", slug: "ireland-cricket" },
      { name: "Associate Nations", slug: "associate-nations-cricket" },
    ],
  },

  'football': {
    'premier-league': [
      { name: "Manchester United", slug: "manchester-united" },
      { name: "Liverpool FC", slug: "liverpool-fc" },
      { name: "Arsenal", slug: "arsenal" },
      { name: "Chelsea", slug: "chelsea" },
      { name: "Manchester City", slug: "manchester-city" },
      { name: "Tottenham Hotspur", slug: "tottenham" },
      { name: "Premier League History", slug: "premier-league-history" },
      { name: "Premier League Records", slug: "premier-league-records" },
      { name: "Golden Boot Winners", slug: "golden-boot-winners" },
      { name: "Premier League Managers", slug: "premier-league-managers" },
      { name: "Premier League Rivalries", slug: "premier-league-rivalries" },
      { name: "Invincibles (Arsenal 2003-04)", slug: "arsenal-invincibles" },
      { name: "Premier League Title Races", slug: "pl-title-races" },
      { name: "Relegated Teams History", slug: "relegated-teams" },
      { name: "Sir Alex Ferguson Era", slug: "sir-alex-ferguson" },
    ],
    'la-liga': [
      { name: "Real Madrid", slug: "real-madrid" },
      { name: "FC Barcelona", slug: "barcelona" },
      { name: "Atletico Madrid", slug: "atletico-madrid" },
      { name: "El Clasico History", slug: "el-clasico" },
      { name: "La Liga Records", slug: "la-liga-records" },
      { name: "La Liga History", slug: "la-liga-history" },
      { name: "Pichichi Trophy Winners", slug: "pichichi-trophy" },
      { name: "Sevilla FC", slug: "sevilla-fc" },
      { name: "Valencia CF", slug: "valencia-cf" },
      { name: "Athletic Bilbao", slug: "athletic-bilbao" },
      { name: "La Liga Managers", slug: "la-liga-managers" },
      { name: "Barcelona's Tiki-Taka Era", slug: "tiki-taka" },
      { name: "Galacticos Era", slug: "galacticos" },
      { name: "La Masia Academy", slug: "la-masia" },
    ],
    'champions-league': [
      { name: "Champions League History", slug: "ucl-history" },
      { name: "Champions League Finals", slug: "ucl-finals" },
      { name: "Most UCL Titles", slug: "most-ucl-titles" },
      { name: "UCL Top Scorers", slug: "ucl-top-scorers" },
      { name: "Greatest UCL Matches", slug: "greatest-ucl-matches" },
      { name: "UCL Comebacks", slug: "ucl-comebacks" },
      { name: "European Cup Era", slug: "european-cup-era" },
      { name: "UCL Group Stage Drama", slug: "ucl-group-stage" },
      { name: "UCL Records", slug: "ucl-records" },
      { name: "English Clubs in Europe", slug: "english-clubs-europe" },
      { name: "Spanish Clubs in Europe", slug: "spanish-clubs-europe" },
      { name: "UCL Underdogs", slug: "ucl-underdogs" },
    ],
    'world-cup': [
      { name: "FIFA World Cup History", slug: "fifa-wc-history" },
      { name: "World Cup 2022 Qatar", slug: "wc-2022" },
      { name: "World Cup 2018 Russia", slug: "wc-2018" },
      { name: "World Cup 2014 Brazil", slug: "wc-2014" },
      { name: "World Cup 2010 South Africa", slug: "wc-2010" },
      { name: "World Cup Finals History", slug: "wc-finals-history" },
      { name: "World Cup Golden Ball Winners", slug: "wc-golden-ball" },
      { name: "World Cup Top Scorers", slug: "wc-top-scorers" },
      { name: "World Cup Host Nations", slug: "wc-hosts" },
      { name: "World Cup Upsets", slug: "wc-upsets" },
      { name: "Brazil World Cup Legacy", slug: "brazil-wc-legacy" },
      { name: "Germany World Cup Legacy", slug: "germany-wc-legacy" },
      { name: "Italy World Cup Legacy", slug: "italy-wc-legacy" },
      { name: "Argentina World Cup Legacy", slug: "argentina-wc-legacy" },
    ],
    'players': [
      { name: "Lionel Messi", slug: "lionel-messi" },
      { name: "Cristiano Ronaldo", slug: "cristiano-ronaldo" },
      { name: "Diego Maradona", slug: "diego-maradona" },
      { name: "Pele", slug: "pele" },
      { name: "Johan Cruyff", slug: "johan-cruyff" },
      { name: "Zinedine Zidane", slug: "zinedine-zidane" },
      { name: "Ronaldo Nazario", slug: "ronaldo-nazario" },
      { name: "Ronaldinho", slug: "ronaldinho" },
      { name: "Thierry Henry", slug: "thierry-henry" },
      { name: "Kylian Mbappe", slug: "kylian-mbappe" },
      { name: "Erling Haaland", slug: "erling-haaland" },
      { name: "Neymar", slug: "neymar" },
      { name: "Luka Modric", slug: "luka-modric" },
      { name: "Ballon d'Or Winners", slug: "ballon-dor-winners" },
      { name: "Greatest Goalkeepers", slug: "greatest-goalkeepers" },
      { name: "Greatest Defenders", slug: "greatest-defenders" },
    ],
    'clubs': [
      { name: "Bayern Munich", slug: "bayern-munich" },
      { name: "Juventus", slug: "juventus" },
      { name: "AC Milan", slug: "ac-milan" },
      { name: "Inter Milan", slug: "inter-milan" },
      { name: "Paris Saint-Germain", slug: "psg" },
      { name: "Borussia Dortmund", slug: "borussia-dortmund" },
      { name: "Ajax Amsterdam", slug: "ajax" },
      { name: "Benfica", slug: "benfica" },
      { name: "Porto", slug: "porto" },
      { name: "Celtic vs Rangers", slug: "old-firm" },
      { name: "Boca Juniors vs River Plate", slug: "superclasico" },
      { name: "Greatest Club Teams Ever", slug: "greatest-club-teams" },
      { name: "Club World Cup", slug: "club-world-cup" },
      { name: "Europa League", slug: "europa-league" },
    ],
    'history': [
      { name: "Origins of Football", slug: "football-origins" },
      { name: "Football in the 1900s", slug: "football-1900s" },
      { name: "Total Football", slug: "total-football" },
      { name: "Catenaccio", slug: "catenaccio" },
      { name: "Football Hooliganism", slug: "football-hooliganism" },
      { name: "Heysel & Hillsborough", slug: "heysel-hillsborough" },
      { name: "Munich Air Disaster", slug: "munich-air-disaster" },
      { name: "Hand of God", slug: "hand-of-god" },
      { name: "Miracle of Istanbul", slug: "istanbul-2005" },
      { name: "VAR Introduction", slug: "var-football" },
      { name: "Women's Football History", slug: "womens-football-history" },
      { name: "Football Rule Changes", slug: "football-rules-history" },
    ],
    'managers': [
      { name: "Pep Guardiola", slug: "pep-guardiola" },
      { name: "Jose Mourinho", slug: "jose-mourinho" },
      { name: "Jurgen Klopp", slug: "jurgen-klopp" },
      { name: "Carlo Ancelotti", slug: "carlo-ancelotti" },
      { name: "Arsene Wenger", slug: "arsene-wenger" },
      { name: "Alex Ferguson", slug: "alex-ferguson" },
      { name: "Marcello Lippi", slug: "marcello-lippi" },
      { name: "Johan Cruyff (Manager)", slug: "cruyff-manager" },
      { name: "Greatest Managers Ever", slug: "greatest-managers" },
      { name: "Manager Rivalries", slug: "manager-rivalries" },
      { name: "Managerial Records", slug: "managerial-records" },
      { name: "Sacked Managers", slug: "sacked-managers" },
    ],
    'tactics': [
      { name: "4-4-2 Formation", slug: "4-4-2" },
      { name: "4-3-3 Formation", slug: "4-3-3" },
      { name: "3-5-2 Formation", slug: "3-5-2" },
      { name: "False Nine", slug: "false-nine" },
      { name: "Gegenpressing", slug: "gegenpressing" },
      { name: "Parking the Bus", slug: "parking-the-bus" },
      { name: "Wing Play", slug: "wing-play" },
      { name: "Set Piece Specialists", slug: "set-pieces" },
      { name: "Tactical Evolution", slug: "tactical-evolution" },
      { name: "Defensive Systems", slug: "defensive-systems" },
      { name: "Pressing Triggers", slug: "pressing-triggers" },
      { name: "Position Revolution", slug: "position-revolution" },
    ],
    'transfers': [
      { name: "Most Expensive Transfers", slug: "expensive-transfers" },
      { name: "Free Transfer Bargains", slug: "free-transfers" },
      { name: "Biggest Transfer Flops", slug: "transfer-flops" },
      { name: "Best Transfer Windows", slug: "best-transfer-windows" },
      { name: "Loan System", slug: "loan-system" },
      { name: "Youth Academy Products", slug: "academy-products" },
      { name: "Transfer Deadline Drama", slug: "deadline-day" },
      { name: "Agent Influence", slug: "football-agents" },
      { name: "Transfer Records by Position", slug: "transfer-records-position" },
      { name: "Bosman Ruling Impact", slug: "bosman-ruling" },
    ],
  },

  'olympics': {
    'summer-olympics': [
      { name: "Olympics 2024 Paris", slug: "olympics-2024" },
      { name: "Olympics 2020 Tokyo", slug: "olympics-2020" },
      { name: "Olympics 2016 Rio", slug: "olympics-2016" },
      { name: "Olympics 2012 London", slug: "olympics-2012" },
      { name: "Olympics 2008 Beijing", slug: "olympics-2008" },
      { name: "Historic Summer Olympics", slug: "historic-summer-olympics" },
      { name: "Summer Olympics Records", slug: "summer-olympics-records" },
      { name: "Opening Ceremonies", slug: "opening-ceremonies" },
      { name: "Olympic Controversies", slug: "olympic-controversies" },
      { name: "Olympic Boycotts", slug: "olympic-boycotts" },
      { name: "Greatest Olympic Moments", slug: "greatest-olympic-moments" },
      { name: "Olympic Medal Counts", slug: "olympic-medal-counts" },
    ],
    'winter-olympics': [
      { name: "Winter Olympics 2022 Beijing", slug: "winter-2022" },
      { name: "Winter Olympics 2018 PyeongChang", slug: "winter-2018" },
      { name: "Winter Olympics 2014 Sochi", slug: "winter-2014" },
      { name: "Historic Winter Olympics", slug: "historic-winter-olympics" },
      { name: "Figure Skating", slug: "figure-skating" },
      { name: "Ice Hockey Olympics", slug: "ice-hockey-olympics" },
      { name: "Alpine Skiing", slug: "alpine-skiing" },
      { name: "Snowboarding", slug: "snowboarding-olympics" },
      { name: "Cross-Country Skiing", slug: "cross-country-skiing" },
      { name: "Bobsled & Luge", slug: "bobsled-luge" },
      { name: "Speed Skating", slug: "speed-skating" },
      { name: "Winter Olympics Records", slug: "winter-olympics-records" },
    ],
    'olympians': [
      { name: "Michael Phelps", slug: "michael-phelps" },
      { name: "Usain Bolt", slug: "usain-bolt" },
      { name: "Carl Lewis", slug: "carl-lewis" },
      { name: "Jesse Owens", slug: "jesse-owens" },
      { name: "Simone Biles", slug: "simone-biles" },
      { name: "Nadia Comaneci", slug: "nadia-comaneci" },
      { name: "Mark Spitz", slug: "mark-spitz" },
      { name: "Katie Ledecky", slug: "katie-ledecky" },
      { name: "Allyson Felix", slug: "allyson-felix" },
      { name: "Mo Farah", slug: "mo-farah" },
      { name: "Eliud Kipchoge", slug: "eliud-kipchoge" },
      { name: "Jackie Joyner-Kersee", slug: "jackie-joyner-kersee" },
      { name: "Shaun White", slug: "shaun-white" },
      { name: "Lindsey Vonn", slug: "lindsey-vonn" },
      { name: "Most Decorated Olympians", slug: "most-decorated-olympians" },
    ],
    'track-field': [
      { name: "100m Sprint History", slug: "100m-history" },
      { name: "200m Sprint History", slug: "200m-history" },
      { name: "400m History", slug: "400m-history" },
      { name: "Marathon History", slug: "marathon-history" },
      { name: "Long Jump Records", slug: "long-jump-records" },
      { name: "High Jump Records", slug: "high-jump-records" },
      { name: "Pole Vault", slug: "pole-vault" },
      { name: "Shot Put & Discus", slug: "throwing-events" },
      { name: "Relay Races", slug: "relay-races" },
      { name: "Decathlon/Heptathlon", slug: "combined-events" },
      { name: "World Athletics Championships", slug: "world-athletics" },
      { name: "Diamond League", slug: "diamond-league" },
      { name: "Track & Field Legends", slug: "track-field-legends" },
      { name: "Sprinting Rivalries", slug: "sprinting-rivalries" },
    ],
    'swimming': [
      { name: "Freestyle Swimming", slug: "freestyle-swimming" },
      { name: "Butterfly Stroke", slug: "butterfly-stroke" },
      { name: "Backstroke", slug: "backstroke" },
      { name: "Breaststroke", slug: "breaststroke" },
      { name: "Individual Medley", slug: "individual-medley" },
      { name: "Swimming World Records", slug: "swimming-world-records" },
      { name: "Swimming Rivalries", slug: "swimming-rivalries" },
      { name: "Open Water Swimming", slug: "open-water-swimming" },
      { name: "Swimming Legends", slug: "swimming-legends" },
      { name: "FINA World Championships", slug: "fina-worlds" },
      { name: "Swimming Technology", slug: "swimming-technology" },
      { name: "Paralympic Swimming", slug: "paralympic-swimming" },
    ],
    'gymnastics': [
      { name: "Artistic Gymnastics", slug: "artistic-gymnastics" },
      { name: "Rhythmic Gymnastics", slug: "rhythmic-gymnastics" },
      { name: "Gymnastics Legends", slug: "gymnastics-legends" },
      { name: "Floor Exercise", slug: "floor-exercise" },
      { name: "Vault", slug: "vault-gymnastics" },
      { name: "Uneven Bars", slug: "uneven-bars" },
      { name: "Balance Beam", slug: "balance-beam" },
      { name: "Men's Gymnastics", slug: "mens-gymnastics" },
      { name: "Perfect 10 Moments", slug: "perfect-10" },
      { name: "Gymnastics Scandals", slug: "gymnastics-scandals" },
      { name: "World Gymnastics Championships", slug: "gymnastics-worlds" },
      { name: "Gymnastics Moves Named After Athletes", slug: "named-gymnastics-moves" },
    ],
    'records': [
      { name: "Most Olympic Golds", slug: "most-olympic-golds" },
      { name: "Most Olympic Medals", slug: "most-olympic-medals" },
      { name: "Youngest Olympic Champions", slug: "youngest-olympic-champions" },
      { name: "Oldest Olympic Medalists", slug: "oldest-olympic-medalists" },
      { name: "Olympic World Records", slug: "olympic-world-records" },
      { name: "Country Medal Records", slug: "country-medal-records" },
      { name: "Single Olympics Records", slug: "single-olympics-records" },
      { name: "Consecutive Gold Medals", slug: "consecutive-golds" },
      { name: "Paralympic Records", slug: "paralympic-records" },
      { name: "Olympic Firsts", slug: "olympic-firsts" },
    ],
    'sports': [
      { name: "Basketball (Olympics)", slug: "basketball-olympics" },
      { name: "Volleyball (Olympics)", slug: "volleyball-olympics" },
      { name: "Tennis (Olympics)", slug: "tennis-olympics" },
      { name: "Football (Olympics)", slug: "football-olympics" },
      { name: "Boxing (Olympics)", slug: "boxing-olympics" },
      { name: "Wrestling (Olympics)", slug: "wrestling-olympics" },
      { name: "Judo (Olympics)", slug: "judo-olympics" },
      { name: "Cycling (Olympics)", slug: "cycling-olympics" },
      { name: "Rowing (Olympics)", slug: "rowing-olympics" },
      { name: "Archery (Olympics)", slug: "archery-olympics" },
      { name: "New Olympic Sports", slug: "new-olympic-sports" },
      { name: "Removed Olympic Sports", slug: "removed-olympic-sports" },
    ],
    'host-cities': [
      { name: "Future Olympic Hosts", slug: "future-olympic-hosts" },
      { name: "Athens Olympics", slug: "athens-olympics" },
      { name: "Sydney 2000", slug: "sydney-2000" },
      { name: "Barcelona 1992", slug: "barcelona-1992" },
      { name: "Los Angeles Olympics", slug: "la-olympics" },
      { name: "Berlin 1936", slug: "berlin-1936" },
      { name: "Olympic Venue Legacy", slug: "olympic-venue-legacy" },
      { name: "Olympic Bid Process", slug: "olympic-bid-process" },
      { name: "Olympic Village", slug: "olympic-village" },
      { name: "Olympic Economics", slug: "olympic-economics" },
    ],
    'paralympics': [
      { name: "Paralympic History", slug: "paralympic-history" },
      { name: "Paralympic Legends", slug: "paralympic-legends" },
      { name: "Wheelchair Basketball", slug: "wheelchair-basketball" },
      { name: "Wheelchair Tennis", slug: "wheelchair-tennis" },
      { name: "Paralympic Swimming", slug: "paralympic-swimming-events" },
      { name: "Paralympic Athletics", slug: "paralympic-athletics" },
      { name: "Sitting Volleyball", slug: "sitting-volleyball" },
      { name: "Boccia", slug: "boccia" },
      { name: "Goalball", slug: "goalball" },
      { name: "Winter Paralympics", slug: "winter-paralympics" },
    ],
  },

  'other-sports': {
    'tennis': [
      { name: "Roger Federer", slug: "roger-federer" },
      { name: "Rafael Nadal", slug: "rafael-nadal" },
      { name: "Novak Djokovic", slug: "novak-djokovic" },
      { name: "Serena Williams", slug: "serena-williams" },
      { name: "Wimbledon History", slug: "wimbledon-history" },
      { name: "US Open History", slug: "us-open-history" },
      { name: "French Open History", slug: "french-open-history" },
      { name: "Australian Open History", slug: "australian-open-history" },
      { name: "Grand Slam Records", slug: "grand-slam-records" },
      { name: "Tennis Rivalries", slug: "tennis-rivalries" },
      { name: "ATP Tour", slug: "atp-tour" },
      { name: "WTA Tour", slug: "wta-tour" },
      { name: "Davis Cup", slug: "davis-cup" },
      { name: "Tennis Legends", slug: "tennis-legends-history" },
      { name: "Carlos Alcaraz", slug: "carlos-alcaraz" },
      { name: "Iga Swiatek", slug: "iga-swiatek" },
    ],
    'golf': [
      { name: "Tiger Woods", slug: "tiger-woods" },
      { name: "Jack Nicklaus", slug: "jack-nicklaus" },
      { name: "The Masters", slug: "the-masters" },
      { name: "The Open Championship", slug: "the-open" },
      { name: "US Open (Golf)", slug: "us-open-golf" },
      { name: "PGA Championship", slug: "pga-championship" },
      { name: "Ryder Cup", slug: "ryder-cup" },
      { name: "PGA Tour", slug: "pga-tour" },
      { name: "LIV Golf", slug: "liv-golf" },
      { name: "Golf Legends", slug: "golf-legends" },
      { name: "Major Championship Records", slug: "golf-major-records" },
      { name: "Golf Courses", slug: "famous-golf-courses" },
      { name: "Women's Golf (LPGA)", slug: "lpga" },
      { name: "Golf Rules & Etiquette", slug: "golf-rules" },
    ],
    'motorsport': [
      { name: "Formula 1 History", slug: "f1-history" },
      { name: "F1 Champions", slug: "f1-champions" },
      { name: "Lewis Hamilton", slug: "lewis-hamilton" },
      { name: "Michael Schumacher", slug: "michael-schumacher" },
      { name: "Ayrton Senna", slug: "ayrton-senna" },
      { name: "Max Verstappen", slug: "max-verstappen" },
      { name: "F1 Teams", slug: "f1-teams" },
      { name: "F1 Circuits", slug: "f1-circuits" },
      { name: "Monaco Grand Prix", slug: "monaco-gp" },
      { name: "NASCAR History", slug: "nascar-history" },
      { name: "IndyCar & Indy 500", slug: "indycar" },
      { name: "MotoGP History", slug: "motogp-history" },
      { name: "Le Mans 24 Hours", slug: "le-mans" },
      { name: "Rally World Championship", slug: "wrc" },
      { name: "Motorsport Legends", slug: "motorsport-legends" },
      { name: "F1 Records", slug: "f1-records" },
    ],
    'cycling': [
      { name: "Tour de France", slug: "tour-de-france" },
      { name: "Giro d'Italia", slug: "giro-ditalia" },
      { name: "Vuelta a Espana", slug: "vuelta" },
      { name: "Cycling Legends", slug: "cycling-legends" },
      { name: "Lance Armstrong Controversy", slug: "armstrong-controversy" },
      { name: "Grand Tour Records", slug: "grand-tour-records" },
      { name: "Spring Classics", slug: "spring-classics" },
      { name: "Track Cycling", slug: "track-cycling" },
      { name: "Mountain Biking", slug: "mountain-biking" },
      { name: "BMX Racing", slug: "bmx-racing" },
      { name: "Tour de France Stages", slug: "tdf-stages" },
      { name: "Cycling Teams", slug: "cycling-teams" },
    ],
    'rugby': [
      { name: "Rugby World Cup", slug: "rugby-world-cup" },
      { name: "Six Nations", slug: "six-nations" },
      { name: "Rugby Championship", slug: "rugby-championship" },
      { name: "New Zealand All Blacks", slug: "all-blacks" },
      { name: "South Africa Springboks", slug: "springboks" },
      { name: "England Rugby", slug: "england-rugby" },
      { name: "Rugby Legends", slug: "rugby-legends" },
      { name: "Rugby Sevens", slug: "rugby-sevens" },
      { name: "British & Irish Lions", slug: "lions-tour" },
      { name: "Super Rugby", slug: "super-rugby" },
      { name: "Rugby League", slug: "rugby-league" },
      { name: "NRL", slug: "nrl" },
    ],
    'badminton': [
      { name: "Badminton World Championships", slug: "badminton-worlds" },
      { name: "All England Open", slug: "all-england-badminton" },
      { name: "Thomas & Uber Cup", slug: "thomas-uber-cup" },
      { name: "Badminton Legends", slug: "badminton-legends" },
      { name: "Lin Dan", slug: "lin-dan" },
      { name: "PV Sindhu", slug: "pv-sindhu" },
      { name: "BWF Tour", slug: "bwf-tour" },
      { name: "Table Tennis World Championships", slug: "table-tennis-worlds" },
      { name: "Table Tennis Legends", slug: "table-tennis-legends" },
      { name: "Ma Long", slug: "ma-long" },
      { name: "Table Tennis Olympics", slug: "table-tennis-olympics" },
      { name: "ITTF Tour", slug: "ittf-tour" },
    ],
    'esports': [
      { name: "League of Legends Esports", slug: "lol-esports" },
      { name: "Dota 2 The International", slug: "dota-ti" },
      { name: "CS:GO/CS2 Majors", slug: "csgo-majors" },
      { name: "Valorant Champions", slug: "valorant-esports" },
      { name: "Overwatch League", slug: "overwatch-league" },
      { name: "Call of Duty League", slug: "cod-league" },
      { name: "FIFA/EA FC Esports", slug: "fifa-esports" },
      { name: "Fighting Game Community (FGC)", slug: "fgc" },
      { name: "Esports Organizations", slug: "esports-orgs" },
      { name: "Esports Legends", slug: "esports-legends" },
      { name: "Esports Prize Pools", slug: "esports-prize-pools" },
      { name: "Streaming & Content Creation", slug: "streaming-esports" },
    ],
    'extreme': [
      { name: "X Games", slug: "x-games" },
      { name: "Skateboarding", slug: "skateboarding" },
      { name: "Surfing", slug: "surfing" },
      { name: "Snowboarding", slug: "snowboarding" },
      { name: "BMX", slug: "bmx" },
      { name: "Motocross", slug: "motocross" },
      { name: "Rock Climbing", slug: "rock-climbing" },
      { name: "Parkour", slug: "parkour" },
      { name: "Base Jumping", slug: "base-jumping" },
      { name: "Extreme Sports Legends", slug: "extreme-sports-legends" },
      { name: "Tony Hawk", slug: "tony-hawk" },
      { name: "Red Bull Events", slug: "red-bull-events" },
    ],
    'horse-racing': [
      { name: "Kentucky Derby", slug: "kentucky-derby" },
      { name: "Preakness Stakes", slug: "preakness" },
      { name: "Belmont Stakes", slug: "belmont" },
      { name: "Triple Crown Winners", slug: "triple-crown" },
      { name: "Grand National", slug: "grand-national" },
      { name: "Melbourne Cup", slug: "melbourne-cup" },
      { name: "Dubai World Cup", slug: "dubai-world-cup" },
      { name: "Legendary Racehorses", slug: "legendary-racehorses" },
      { name: "Famous Jockeys", slug: "famous-jockeys" },
      { name: "Horse Racing History", slug: "horse-racing-history" },
      { name: "Secretariat", slug: "secretariat" },
      { name: "Breeders' Cup", slug: "breeders-cup" },
    ],
    'skiing': [
      { name: "Alpine Skiing World Cup", slug: "alpine-world-cup" },
      { name: "Downhill Skiing", slug: "downhill-skiing" },
      { name: "Slalom & Giant Slalom", slug: "slalom-skiing" },
      { name: "Skiing Legends", slug: "skiing-legends" },
      { name: "Lindsey Vonn", slug: "lindsey-vonn-skiing" },
      { name: "Marcel Hirscher", slug: "marcel-hirscher" },
      { name: "Mikaela Shiffrin", slug: "mikaela-shiffrin" },
      { name: "Cross-Country World Cup", slug: "cross-country-wc" },
      { name: "Ski Jumping", slug: "ski-jumping" },
      { name: "Nordic Combined", slug: "nordic-combined" },
      { name: "Biathlon", slug: "biathlon" },
      { name: "FIS World Championships", slug: "fis-worlds" },
    ],
  },
};

let added = 0;
let skipped = 0;

for (const [category, subcategories] of Object.entries(sports)) {
  console.log(`\n=== ${category.toUpperCase()} ===`);

  for (const [subcategory, topics] of Object.entries(subcategories)) {
    console.log(`\n${subcategory}:`);

    for (const topic of topics) {
      if (existingSlugs.has(topic.slug)) {
        console.log(`  - ${topic.name} (exists)`);
        skipped++;
        continue;
      }

      ensureTopic({
        category,
        subcategory,
        slug: topic.slug,
        name: topic.name,
        source_type: 'wikipedia',
      });

      console.log(`  + ${topic.name}`);
      added++;
      existingSlugs.add(topic.slug);
    }
  }
}

console.log(`\n✓ Added: ${added} topics`);
console.log(`- Skipped: ${skipped} (already exist)`);

// Final counts
const allSportsTopics = [
  ...getTopics('american-sports'),
  ...getTopics('combat-sports'),
  ...getTopics('cricket'),
  ...getTopics('football'),
  ...getTopics('olympics'),
  ...getTopics('other-sports'),
];
console.log(`\nTotal sports topics: ${allSportsTopics.length}`);
