/**
 * Seed topics for remaining categories:
 * Automobiles, Business, Health, Philosophy, Psychology, Travel,
 * Languages, Mythology, Religion, Economics, Politics, Epics, Mathematics
 */

import { ensureTopic, getTopics, initRegistry } from '../src/lib/registry';

initRegistry();

const categories = [
  'automobiles', 'business', 'health', 'philosophy', 'psychology', 'travel',
  'languages', 'mythology', 'religion', 'economics', 'politics', 'epics', 'mathematics'
];
const existingTopics = categories.flatMap(c => getTopics(c));
const existingSlugs = new Set(existingTopics.map(t => t.slug));

const topics: Record<string, Record<string, Array<{ name: string; slug: string }>>> = {
  'automobiles': {
    'manufacturers': [
      { name: "Toyota", slug: "toyota" },
      { name: "Ford", slug: "ford" },
      { name: "General Motors", slug: "general-motors" },
      { name: "Volkswagen", slug: "volkswagen" },
      { name: "BMW", slug: "bmw" },
      { name: "Mercedes-Benz", slug: "mercedes-benz" },
      { name: "Honda", slug: "honda" },
      { name: "Nissan", slug: "nissan" },
      { name: "Hyundai", slug: "hyundai" },
      { name: "Tesla", slug: "tesla-auto" },
      { name: "Audi", slug: "audi" },
      { name: "Porsche", slug: "porsche" },
    ],
    'sports-cars': [
      { name: "Ferrari", slug: "ferrari" },
      { name: "Lamborghini", slug: "lamborghini" },
      { name: "McLaren", slug: "mclaren" },
      { name: "Bugatti", slug: "bugatti" },
      { name: "Aston Martin", slug: "aston-martin" },
      { name: "Maserati", slug: "maserati" },
      { name: "Corvette", slug: "corvette" },
      { name: "Mustang", slug: "mustang" },
      { name: "Nissan GT-R", slug: "nissan-gtr" },
      { name: "Pagani", slug: "pagani" },
    ],
    'classic': [
      { name: "Classic Cars History", slug: "classic-cars-history" },
      { name: "Muscle Cars", slug: "muscle-cars" },
      { name: "Vintage Rolls-Royce", slug: "vintage-rolls-royce" },
      { name: "Classic Ferrari", slug: "classic-ferrari" },
      { name: "Classic Porsche", slug: "classic-porsche" },
      { name: "1960s Cars", slug: "1960s-cars" },
      { name: "Car Restoration", slug: "car-restoration" },
      { name: "Classic American Cars", slug: "classic-american" },
    ],
    'electric': [
      { name: "Tesla History", slug: "tesla-history" },
      { name: "Electric Vehicle Technology", slug: "ev-technology" },
      { name: "EV Charging", slug: "ev-charging" },
      { name: "Electric Car History", slug: "electric-car-history" },
      { name: "Rivian", slug: "rivian" },
      { name: "Lucid Motors", slug: "lucid-motors" },
      { name: "BYD", slug: "byd" },
      { name: "Hybrid Vehicles", slug: "hybrid-vehicles" },
    ],
    'motorsport': [
      { name: "Formula 1", slug: "formula-1" },
      { name: "NASCAR", slug: "nascar" },
      { name: "IndyCar", slug: "indycar" },
      { name: "Le Mans", slug: "le-mans" },
      { name: "Rally Racing", slug: "rally-racing" },
      { name: "MotoGP", slug: "motogp" },
      { name: "Drag Racing", slug: "drag-racing" },
      { name: "F1 Drivers", slug: "f1-drivers" },
      { name: "F1 Teams", slug: "f1-teams" },
      { name: "Racing Legends", slug: "racing-legends" },
    ],
    'motorcycles': [
      { name: "Harley-Davidson", slug: "harley-davidson" },
      { name: "Ducati", slug: "ducati" },
      { name: "Kawasaki", slug: "kawasaki" },
      { name: "Yamaha Motorcycles", slug: "yamaha-motorcycles" },
      { name: "Honda Motorcycles", slug: "honda-motorcycles" },
      { name: "Triumph", slug: "triumph-motorcycles" },
      { name: "Indian Motorcycle", slug: "indian-motorcycle" },
      { name: "Motorcycle History", slug: "motorcycle-history" },
    ],
    'auto-history': [
      { name: "History of the Automobile", slug: "automobile-history" },
      { name: "Henry Ford", slug: "henry-ford" },
      { name: "Karl Benz", slug: "karl-benz" },
      { name: "Model T Ford", slug: "model-t" },
      { name: "Automotive Pioneers", slug: "automotive-pioneers" },
      { name: "Japanese Auto Industry", slug: "japanese-auto" },
      { name: "American Auto Industry", slug: "american-auto" },
      { name: "German Auto Industry", slug: "german-auto" },
    ],
    'technology': [
      { name: "Autonomous Vehicles", slug: "autonomous-vehicles" },
      { name: "Car Safety Technology", slug: "car-safety-tech" },
      { name: "Engine Technology", slug: "engine-technology" },
      { name: "Aerodynamics", slug: "car-aerodynamics" },
      { name: "GPS & Navigation", slug: "gps-navigation" },
      { name: "Car Infotainment", slug: "car-infotainment" },
      { name: "Fuel Efficiency", slug: "fuel-efficiency" },
      { name: "Turbocharging", slug: "turbocharging" },
    ],
    'trucks': [
      { name: "Pickup Trucks", slug: "pickup-trucks" },
      { name: "Ford F-150", slug: "ford-f150" },
      { name: "Ram Trucks", slug: "ram-trucks" },
      { name: "Chevrolet Silverado", slug: "chevy-silverado" },
      { name: "Electric Trucks", slug: "electric-trucks" },
      { name: "Commercial Trucks", slug: "commercial-trucks" },
      { name: "Off-Road Vehicles", slug: "off-road-vehicles" },
    ],
    'cars': [
      { name: "SUVs", slug: "suvs" },
      { name: "Sedans", slug: "sedans" },
      { name: "Hatchbacks", slug: "hatchbacks" },
      { name: "Luxury Cars", slug: "luxury-cars" },
      { name: "Economy Cars", slug: "economy-cars" },
      { name: "Minivans", slug: "minivans" },
      { name: "Compact Cars", slug: "compact-cars" },
    ],
  },
  'business': {
    'entrepreneurs': [
      { name: "Warren Buffett", slug: "warren-buffett" },
      { name: "Richard Branson", slug: "richard-branson" },
      { name: "Oprah Winfrey", slug: "oprah-winfrey" },
      { name: "Ray Kroc", slug: "ray-kroc" },
      { name: "Sam Walton", slug: "sam-walton" },
      { name: "Andrew Carnegie", slug: "andrew-carnegie" },
      { name: "John D. Rockefeller", slug: "john-rockefeller" },
      { name: "Henry Ford (Business)", slug: "henry-ford-business" },
      { name: "Ratan Tata", slug: "ratan-tata" },
      { name: "Mukesh Ambani", slug: "mukesh-ambani" },
      { name: "Jack Welch", slug: "jack-welch" },
      { name: "Howard Schultz", slug: "howard-schultz" },
    ],
    'tech-giants': [
      { name: "Apple Business", slug: "apple-business" },
      { name: "Google Business", slug: "google-business" },
      { name: "Amazon Business", slug: "amazon-business" },
      { name: "Microsoft Business", slug: "microsoft-business" },
      { name: "Meta Business", slug: "meta-business" },
      { name: "Netflix Business", slug: "netflix-business" },
      { name: "Uber", slug: "uber" },
      { name: "Airbnb", slug: "airbnb" },
      { name: "Alibaba Business", slug: "alibaba-business" },
      { name: "TikTok / ByteDance", slug: "bytedance" },
    ],
    'retail': [
      { name: "Walmart", slug: "walmart" },
      { name: "Amazon Retail", slug: "amazon-retail" },
      { name: "Target", slug: "target" },
      { name: "Costco", slug: "costco" },
      { name: "IKEA", slug: "ikea" },
      { name: "Best Buy", slug: "best-buy" },
      { name: "Home Depot", slug: "home-depot" },
      { name: "Zara / Inditex", slug: "zara" },
      { name: "H&M", slug: "h-and-m" },
      { name: "E-Commerce Giants", slug: "ecommerce-giants" },
    ],
    'brands': [
      { name: "Coca-Cola", slug: "coca-cola" },
      { name: "Pepsi", slug: "pepsi" },
      { name: "Nike", slug: "nike" },
      { name: "Adidas", slug: "adidas" },
      { name: "McDonald's", slug: "mcdonalds-business" },
      { name: "Starbucks", slug: "starbucks-business" },
      { name: "Disney", slug: "disney-business" },
      { name: "Louis Vuitton", slug: "louis-vuitton" },
      { name: "Rolex", slug: "rolex" },
      { name: "Gucci", slug: "gucci" },
    ],
    'startups': [
      { name: "Startup Ecosystem", slug: "startup-ecosystem" },
      { name: "Unicorn Startups", slug: "unicorn-startups" },
      { name: "Venture Capital", slug: "venture-capital" },
      { name: "Y Combinator", slug: "y-combinator" },
      { name: "Silicon Valley Startups", slug: "silicon-valley-startups" },
      { name: "Indian Startups", slug: "indian-startups" },
      { name: "Startup Failures", slug: "startup-failures" },
      { name: "IPO History", slug: "ipo-history" },
    ],
    'management': [
      { name: "Leadership Principles", slug: "leadership-principles" },
      { name: "Business Strategy", slug: "business-strategy" },
      { name: "Corporate Culture", slug: "corporate-culture" },
      { name: "Management Theories", slug: "management-theories" },
      { name: "Organizational Behavior", slug: "organizational-behavior" },
      { name: "Harvard Business School", slug: "harvard-business" },
      { name: "MBA Programs", slug: "mba-programs" },
    ],
    'marketing': [
      { name: "Digital Marketing", slug: "digital-marketing" },
      { name: "Social Media Marketing", slug: "social-media-marketing" },
      { name: "Advertising History", slug: "advertising-history" },
      { name: "Famous Ad Campaigns", slug: "famous-ads" },
      { name: "Brand Building", slug: "brand-building" },
      { name: "Marketing Strategies", slug: "marketing-strategies" },
      { name: "Influencer Marketing", slug: "influencer-marketing" },
    ],
    'business-history': [
      { name: "Industrial Revolution", slug: "industrial-revolution-business" },
      { name: "Great Depression Business", slug: "great-depression-business" },
      { name: "Post-War Economic Boom", slug: "post-war-boom" },
      { name: "Globalization", slug: "globalization" },
      { name: "Business Scandals", slug: "business-scandals" },
      { name: "Enron Scandal", slug: "enron" },
      { name: "Corporate History", slug: "corporate-history" },
    ],
    'mergers': [
      { name: "Famous Mergers", slug: "famous-mergers" },
      { name: "Tech Acquisitions", slug: "tech-acquisitions-business" },
      { name: "Hostile Takeovers", slug: "hostile-takeovers" },
      { name: "Disney Acquisitions", slug: "disney-acquisitions" },
      { name: "Failed Mergers", slug: "failed-mergers" },
      { name: "Antitrust Cases", slug: "antitrust-cases" },
    ],
    'automotive': [
      { name: "Auto Industry Business", slug: "auto-industry-business" },
      { name: "Car Manufacturing", slug: "car-manufacturing" },
      { name: "Supply Chain", slug: "supply-chain" },
      { name: "Dealerships", slug: "dealerships" },
    ],
  },
  'health': {
    'diseases': [
      { name: "Cancer", slug: "cancer" },
      { name: "Heart Disease", slug: "heart-disease" },
      { name: "Diabetes", slug: "diabetes" },
      { name: "Alzheimer's Disease", slug: "alzheimers" },
      { name: "COVID-19", slug: "covid-19" },
      { name: "HIV/AIDS", slug: "hiv-aids" },
      { name: "Malaria", slug: "malaria" },
      { name: "Tuberculosis", slug: "tuberculosis" },
      { name: "Influenza", slug: "influenza" },
      { name: "Autoimmune Diseases", slug: "autoimmune-diseases" },
      { name: "Genetic Disorders", slug: "genetic-disorders" },
    ],
    'anatomy': [
      { name: "Human Heart", slug: "human-heart" },
      { name: "Human Brain", slug: "human-brain" },
      { name: "Digestive System", slug: "digestive-system" },
      { name: "Respiratory System", slug: "respiratory-system" },
      { name: "Skeletal System", slug: "skeletal-system" },
      { name: "Muscular System", slug: "muscular-system" },
      { name: "Nervous System", slug: "nervous-system" },
      { name: "Circulatory System", slug: "circulatory-system" },
      { name: "Immune System", slug: "immune-system" },
      { name: "Endocrine System", slug: "endocrine-system" },
    ],
    'nutrition': [
      { name: "Vitamins & Minerals", slug: "vitamins-minerals" },
      { name: "Proteins & Amino Acids", slug: "proteins-amino-acids" },
      { name: "Carbohydrates", slug: "carbohydrates" },
      { name: "Fats & Lipids", slug: "fats-lipids" },
      { name: "Hydration", slug: "hydration" },
      { name: "Dietary Fiber", slug: "dietary-fiber" },
      { name: "Superfoods", slug: "superfoods" },
      { name: "Diet Plans", slug: "diet-plans" },
      { name: "Vegetarian & Vegan Nutrition", slug: "vegetarian-nutrition" },
    ],
    'mental-health': [
      { name: "Depression", slug: "depression" },
      { name: "Anxiety Disorders", slug: "anxiety-disorders" },
      { name: "PTSD", slug: "ptsd" },
      { name: "Bipolar Disorder", slug: "bipolar-disorder" },
      { name: "Schizophrenia", slug: "schizophrenia" },
      { name: "OCD", slug: "ocd" },
      { name: "ADHD", slug: "adhd" },
      { name: "Eating Disorders", slug: "eating-disorders" },
      { name: "Addiction", slug: "addiction" },
      { name: "Stress Management", slug: "stress-management" },
    ],
    'medical-history': [
      { name: "History of Medicine", slug: "medicine-history" },
      { name: "Hippocrates", slug: "hippocrates" },
      { name: "Discovery of Penicillin", slug: "penicillin" },
      { name: "Vaccination History", slug: "vaccination-history" },
      { name: "Germ Theory", slug: "germ-theory" },
      { name: "Anesthesia History", slug: "anesthesia-history" },
      { name: "X-Ray Discovery", slug: "x-ray-discovery" },
      { name: "DNA Discovery", slug: "dna-discovery" },
      { name: "Nobel Prize in Medicine", slug: "nobel-medicine" },
    ],
    'treatments': [
      { name: "Surgery", slug: "surgery" },
      { name: "Chemotherapy", slug: "chemotherapy" },
      { name: "Radiation Therapy", slug: "radiation-therapy" },
      { name: "Immunotherapy", slug: "immunotherapy" },
      { name: "Physical Therapy", slug: "physical-therapy" },
      { name: "Gene Therapy", slug: "gene-therapy" },
      { name: "Stem Cell Therapy", slug: "stem-cell-therapy" },
      { name: "Organ Transplants", slug: "organ-transplants" },
    ],
    'pharmaceuticals': [
      { name: "Drug Discovery", slug: "drug-discovery" },
      { name: "Antibiotics", slug: "antibiotics" },
      { name: "Vaccines", slug: "vaccines" },
      { name: "Pain Medication", slug: "pain-medication" },
      { name: "Pharmaceutical Companies", slug: "pharma-companies" },
      { name: "Clinical Trials", slug: "clinical-trials" },
      { name: "FDA Approval Process", slug: "fda-approval" },
    ],
    'famous-doctors': [
      { name: "Louis Pasteur", slug: "louis-pasteur" },
      { name: "Alexander Fleming", slug: "alexander-fleming" },
      { name: "Jonas Salk", slug: "jonas-salk" },
      { name: "Florence Nightingale", slug: "florence-nightingale" },
      { name: "William Harvey", slug: "william-harvey" },
      { name: "Joseph Lister", slug: "joseph-lister" },
      { name: "Marie Curie (Medical)", slug: "marie-curie-medical" },
      { name: "Elizabeth Blackwell", slug: "elizabeth-blackwell" },
    ],
    'public-health': [
      { name: "Epidemics & Pandemics", slug: "epidemics-pandemics" },
      { name: "WHO", slug: "who" },
      { name: "CDC", slug: "cdc" },
      { name: "Global Health", slug: "global-health" },
      { name: "Sanitation History", slug: "sanitation-history" },
      { name: "Water Safety", slug: "water-safety" },
      { name: "Health Insurance", slug: "health-insurance" },
    ],
    'first-aid': [
      { name: "CPR", slug: "cpr" },
      { name: "Wound Care", slug: "wound-care" },
      { name: "Burn Treatment", slug: "burn-treatment" },
      { name: "Choking Response", slug: "choking-response" },
      { name: "Emergency Response", slug: "emergency-response" },
    ],
  },
  'philosophy': {
    'western': [
      { name: "Plato", slug: "plato" },
      { name: "Aristotle", slug: "aristotle" },
      { name: "Socrates", slug: "socrates" },
      { name: "Descartes", slug: "descartes" },
      { name: "Kant", slug: "kant" },
      { name: "Hegel", slug: "hegel" },
      { name: "Nietzsche", slug: "nietzsche" },
      { name: "Hume", slug: "hume" },
      { name: "Locke", slug: "locke" },
      { name: "Rousseau", slug: "rousseau" },
      { name: "Spinoza", slug: "spinoza" },
      { name: "Leibniz", slug: "leibniz" },
    ],
    'eastern': [
      { name: "Confucius", slug: "confucius" },
      { name: "Lao Tzu", slug: "lao-tzu" },
      { name: "Buddha Philosophy", slug: "buddha-philosophy" },
      { name: "Zen Buddhism", slug: "zen-buddhism" },
      { name: "Taoism", slug: "taoism-philosophy" },
      { name: "Hindu Philosophy", slug: "hindu-philosophy" },
      { name: "Vedanta", slug: "vedanta" },
      { name: "Yoga Philosophy", slug: "yoga-philosophy" },
      { name: "Sun Tzu", slug: "sun-tzu" },
      { name: "Chanakya", slug: "chanakya" },
    ],
    'ethics': [
      { name: "Utilitarianism", slug: "utilitarianism" },
      { name: "Deontology", slug: "deontology" },
      { name: "Virtue Ethics", slug: "virtue-ethics" },
      { name: "Moral Relativism", slug: "moral-relativism" },
      { name: "Consequentialism", slug: "consequentialism" },
      { name: "Social Contract", slug: "social-contract" },
      { name: "Ethics in AI", slug: "ethics-in-ai" },
      { name: "Bioethics", slug: "bioethics" },
      { name: "Environmental Ethics", slug: "environmental-ethics" },
    ],
    'existentialism': [
      { name: "Jean-Paul Sartre", slug: "sartre" },
      { name: "Albert Camus", slug: "camus" },
      { name: "Simone de Beauvoir", slug: "simone-de-beauvoir" },
      { name: "Martin Heidegger", slug: "heidegger" },
      { name: "Søren Kierkegaard", slug: "kierkegaard" },
      { name: "Absurdism", slug: "absurdism" },
      { name: "Nihilism", slug: "nihilism" },
      { name: "Phenomenology", slug: "phenomenology" },
    ],
    'metaphysics': [
      { name: "Free Will", slug: "free-will" },
      { name: "Determinism", slug: "determinism" },
      { name: "Consciousness", slug: "consciousness-philosophy" },
      { name: "Mind-Body Problem", slug: "mind-body-problem" },
      { name: "Personal Identity", slug: "personal-identity" },
      { name: "Time & Space", slug: "time-space-philosophy" },
      { name: "Reality & Existence", slug: "reality-existence" },
      { name: "Dualism", slug: "dualism" },
    ],
    'epistemology': [
      { name: "Knowledge & Belief", slug: "knowledge-belief" },
      { name: "Skepticism", slug: "skepticism" },
      { name: "Rationalism", slug: "rationalism" },
      { name: "Empiricism", slug: "empiricism" },
      { name: "Truth Theories", slug: "truth-theories" },
      { name: "Justification", slug: "justification" },
    ],
    'logic': [
      { name: "Formal Logic", slug: "formal-logic" },
      { name: "Logical Fallacies", slug: "logical-fallacies" },
      { name: "Propositional Logic", slug: "propositional-logic" },
      { name: "Syllogisms", slug: "syllogisms" },
      { name: "Paradoxes", slug: "paradoxes" },
      { name: "Boolean Logic", slug: "boolean-logic" },
    ],
    'political': [
      { name: "Political Philosophy", slug: "political-philosophy" },
      { name: "Justice Theory", slug: "justice-theory" },
      { name: "John Rawls", slug: "john-rawls" },
      { name: "Thomas Hobbes", slug: "thomas-hobbes" },
      { name: "Karl Marx Philosophy", slug: "marx-philosophy" },
      { name: "Libertarianism", slug: "libertarianism" },
      { name: "Democracy Philosophy", slug: "democracy-philosophy" },
    ],
    'modern': [
      { name: "Ludwig Wittgenstein", slug: "wittgenstein" },
      { name: "Bertrand Russell", slug: "bertrand-russell" },
      { name: "Michel Foucault", slug: "foucault" },
      { name: "Jacques Derrida", slug: "derrida" },
      { name: "Noam Chomsky", slug: "chomsky-philosophy" },
      { name: "Peter Singer", slug: "peter-singer" },
      { name: "Postmodernism", slug: "postmodernism-philosophy" },
      { name: "Analytic Philosophy", slug: "analytic-philosophy" },
    ],
    'philosophers': [
      { name: "Ancient Greek Philosophers", slug: "greek-philosophers" },
      { name: "Enlightenment Philosophers", slug: "enlightenment-philosophers" },
      { name: "20th Century Philosophers", slug: "20th-century-philosophers" },
      { name: "Women Philosophers", slug: "women-philosophers" },
      { name: "Philosophy of Science", slug: "philosophy-of-science" },
    ],
  },
  'psychology': {
    'cognitive': [
      { name: "Memory", slug: "memory-psychology" },
      { name: "Perception", slug: "perception" },
      { name: "Attention", slug: "attention-psychology" },
      { name: "Problem Solving", slug: "problem-solving" },
      { name: "Decision Making", slug: "decision-making" },
      { name: "Language & Thought", slug: "language-thought" },
      { name: "Intelligence", slug: "intelligence-psychology" },
      { name: "Cognitive Biases", slug: "cognitive-biases" },
      { name: "Heuristics", slug: "heuristics" },
    ],
    'behavioral': [
      { name: "Classical Conditioning", slug: "classical-conditioning" },
      { name: "Operant Conditioning", slug: "operant-conditioning" },
      { name: "Behaviorism", slug: "behaviorism" },
      { name: "Pavlov's Experiments", slug: "pavlov" },
      { name: "B.F. Skinner", slug: "bf-skinner" },
      { name: "Behavior Modification", slug: "behavior-modification" },
      { name: "Learned Helplessness", slug: "learned-helplessness" },
    ],
    'developmental': [
      { name: "Child Development", slug: "child-development" },
      { name: "Jean Piaget", slug: "piaget" },
      { name: "Erik Erikson", slug: "erikson" },
      { name: "Attachment Theory", slug: "attachment-theory" },
      { name: "Adolescent Psychology", slug: "adolescent-psychology" },
      { name: "Aging Psychology", slug: "aging-psychology" },
      { name: "Moral Development", slug: "moral-development" },
      { name: "Cognitive Development", slug: "cognitive-development" },
    ],
    'social': [
      { name: "Social Influence", slug: "social-influence" },
      { name: "Conformity", slug: "conformity" },
      { name: "Obedience", slug: "obedience" },
      { name: "Milgram Experiment", slug: "milgram-experiment" },
      { name: "Stanford Prison Experiment", slug: "stanford-prison" },
      { name: "Group Dynamics", slug: "group-dynamics" },
      { name: "Prejudice & Stereotypes", slug: "prejudice-stereotypes" },
      { name: "Persuasion", slug: "persuasion" },
    ],
    'personality': [
      { name: "Big Five Personality Traits", slug: "big-five" },
      { name: "Myers-Briggs", slug: "myers-briggs" },
      { name: "Freud's Theories", slug: "freud-theories" },
      { name: "Carl Jung", slug: "carl-jung" },
      { name: "Maslow's Hierarchy", slug: "maslow-hierarchy" },
      { name: "Trait Theory", slug: "trait-theory" },
      { name: "Psychoanalysis", slug: "psychoanalysis" },
    ],
    'clinical': [
      { name: "DSM-5", slug: "dsm-5" },
      { name: "Diagnosis & Assessment", slug: "diagnosis-assessment" },
      { name: "Psychopathology", slug: "psychopathology" },
      { name: "Mood Disorders", slug: "mood-disorders" },
      { name: "Personality Disorders", slug: "personality-disorders" },
      { name: "Anxiety Treatment", slug: "anxiety-treatment" },
      { name: "Depression Treatment", slug: "depression-treatment" },
    ],
    'therapies': [
      { name: "Cognitive Behavioral Therapy", slug: "cbt" },
      { name: "Psychotherapy", slug: "psychotherapy" },
      { name: "Group Therapy", slug: "group-therapy" },
      { name: "Family Therapy", slug: "family-therapy" },
      { name: "Humanistic Therapy", slug: "humanistic-therapy" },
      { name: "Mindfulness Therapy", slug: "mindfulness-therapy" },
      { name: "Art Therapy", slug: "art-therapy" },
    ],
    'neuroscience': [
      { name: "Brain Structure", slug: "brain-structure" },
      { name: "Neurotransmitters", slug: "neurotransmitters" },
      { name: "Neuroplasticity", slug: "neuroplasticity" },
      { name: "Brain Imaging", slug: "brain-imaging" },
      { name: "Sleep & Dreams", slug: "sleep-dreams" },
      { name: "Memory & the Brain", slug: "memory-brain" },
      { name: "Emotions & the Brain", slug: "emotions-brain" },
    ],
    'disorders': [
      { name: "Phobias", slug: "phobias" },
      { name: "Panic Disorder", slug: "panic-disorder" },
      { name: "Social Anxiety", slug: "social-anxiety" },
      { name: "Autism Spectrum", slug: "autism-spectrum" },
      { name: "Learning Disabilities", slug: "learning-disabilities" },
      { name: "Dissociative Disorders", slug: "dissociative-disorders" },
    ],
    'psychologists': [
      { name: "Sigmund Freud", slug: "sigmund-freud" },
      { name: "Carl Rogers", slug: "carl-rogers" },
      { name: "Abraham Maslow", slug: "abraham-maslow" },
      { name: "William James", slug: "william-james" },
      { name: "Ivan Pavlov", slug: "ivan-pavlov" },
      { name: "Albert Bandura", slug: "albert-bandura" },
      { name: "Daniel Kahneman", slug: "daniel-kahneman" },
      { name: "Philip Zimbardo", slug: "philip-zimbardo" },
    ],
  },
  'travel': {
    'destinations': [
      { name: "Paris", slug: "paris" },
      { name: "New York City", slug: "new-york-city" },
      { name: "Tokyo", slug: "tokyo-travel" },
      { name: "London", slug: "london-travel" },
      { name: "Rome", slug: "rome-travel" },
      { name: "Dubai", slug: "dubai" },
      { name: "Sydney", slug: "sydney-travel" },
      { name: "Barcelona", slug: "barcelona-travel" },
      { name: "Bangkok", slug: "bangkok" },
      { name: "Singapore", slug: "singapore-travel" },
      { name: "Hong Kong", slug: "hong-kong" },
      { name: "Istanbul", slug: "istanbul" },
    ],
    'wonders': [
      { name: "Seven Wonders of the Ancient World", slug: "ancient-wonders" },
      { name: "New Seven Wonders", slug: "new-seven-wonders" },
      { name: "Great Wall of China", slug: "great-wall" },
      { name: "Machu Picchu", slug: "machu-picchu-travel" },
      { name: "Taj Mahal", slug: "taj-mahal-travel" },
      { name: "Petra", slug: "petra-travel" },
      { name: "Colosseum", slug: "colosseum-travel" },
      { name: "Chichen Itza", slug: "chichen-itza" },
      { name: "Christ the Redeemer", slug: "christ-redeemer-travel" },
    ],
    'national-parks': [
      { name: "Yellowstone", slug: "yellowstone" },
      { name: "Yosemite", slug: "yosemite" },
      { name: "Grand Canyon", slug: "grand-canyon-travel" },
      { name: "Kruger National Park", slug: "kruger" },
      { name: "Serengeti", slug: "serengeti" },
      { name: "Galápagos Islands", slug: "galapagos-travel" },
      { name: "Amazon Rainforest", slug: "amazon-rainforest-travel" },
      { name: "Great Barrier Reef", slug: "great-barrier-reef-travel" },
      { name: "Banff National Park", slug: "banff" },
      { name: "Swiss Alps", slug: "swiss-alps" },
    ],
    'landmarks': [
      { name: "Eiffel Tower", slug: "eiffel-tower-travel" },
      { name: "Statue of Liberty", slug: "statue-liberty-travel" },
      { name: "Big Ben", slug: "big-ben-travel" },
      { name: "Sydney Opera House", slug: "sydney-opera-travel" },
      { name: "Burj Khalifa", slug: "burj-khalifa-travel" },
      { name: "Golden Gate Bridge", slug: "golden-gate-travel" },
      { name: "Mount Rushmore", slug: "mount-rushmore-travel" },
      { name: "Stonehenge", slug: "stonehenge-travel" },
    ],
    'airlines': [
      { name: "Emirates", slug: "emirates" },
      { name: "Singapore Airlines", slug: "singapore-airlines" },
      { name: "Qatar Airways", slug: "qatar-airways" },
      { name: "Delta Airlines", slug: "delta-airlines" },
      { name: "American Airlines", slug: "american-airlines" },
      { name: "British Airways", slug: "british-airways" },
      { name: "Lufthansa", slug: "lufthansa" },
      { name: "Air India", slug: "air-india" },
      { name: "Aviation History", slug: "aviation-history" },
    ],
    'hotels': [
      { name: "Marriott", slug: "marriott" },
      { name: "Hilton", slug: "hilton" },
      { name: "Hyatt", slug: "hyatt" },
      { name: "Four Seasons", slug: "four-seasons" },
      { name: "Ritz-Carlton", slug: "ritz-carlton" },
      { name: "Airbnb Travel", slug: "airbnb-travel" },
      { name: "Famous Hotels", slug: "famous-hotels" },
      { name: "Boutique Hotels", slug: "boutique-hotels" },
    ],
    'cruises': [
      { name: "Cruise Lines", slug: "cruise-lines" },
      { name: "Caribbean Cruises", slug: "caribbean-cruises" },
      { name: "Mediterranean Cruises", slug: "mediterranean-cruises" },
      { name: "Alaska Cruises", slug: "alaska-cruises" },
      { name: "River Cruises", slug: "river-cruises" },
      { name: "Cruise Ship History", slug: "cruise-history" },
    ],
    'adventure': [
      { name: "Safari Travel", slug: "safari-travel" },
      { name: "Mountain Climbing", slug: "mountain-climbing-travel" },
      { name: "Scuba Diving Destinations", slug: "scuba-destinations" },
      { name: "Skiing Destinations", slug: "skiing-destinations" },
      { name: "Backpacking", slug: "backpacking" },
      { name: "Road Trips", slug: "road-trips" },
      { name: "Train Travel", slug: "train-travel" },
    ],
    'cultural': [
      { name: "UNESCO World Heritage Sites", slug: "unesco-sites" },
      { name: "Religious Tourism", slug: "religious-tourism" },
      { name: "Archaeological Sites", slug: "archaeological-sites" },
      { name: "Museum Travel", slug: "museum-travel" },
      { name: "Festival Travel", slug: "festival-travel" },
      { name: "Food Tourism", slug: "food-tourism" },
    ],
    'travel-tips': [
      { name: "Travel Safety", slug: "travel-safety" },
      { name: "Packing Tips", slug: "packing-tips" },
      { name: "Budget Travel", slug: "budget-travel" },
      { name: "Solo Travel", slug: "solo-travel" },
      { name: "Family Travel", slug: "family-travel" },
      { name: "Travel Photography", slug: "travel-photography" },
    ],
  },
  'languages': {
    'english': [
      { name: "English Grammar", slug: "english-grammar" },
      { name: "English Vocabulary", slug: "english-vocabulary" },
      { name: "History of English", slug: "english-history" },
      { name: "American vs British English", slug: "american-british-english" },
      { name: "English Idioms", slug: "english-idioms" },
      { name: "English Literature Language", slug: "english-lit-language" },
      { name: "Shakespeare's English", slug: "shakespeare-english" },
    ],
    'spanish': [
      { name: "Spanish Grammar", slug: "spanish-grammar" },
      { name: "Spanish Vocabulary", slug: "spanish-vocabulary" },
      { name: "Latin American Spanish", slug: "latin-american-spanish" },
      { name: "Spanish History", slug: "spanish-language-history" },
      { name: "Spanish Dialects", slug: "spanish-dialects" },
    ],
    'french': [
      { name: "French Grammar", slug: "french-grammar" },
      { name: "French Vocabulary", slug: "french-vocabulary" },
      { name: "History of French", slug: "french-history" },
      { name: "French Dialects", slug: "french-dialects" },
      { name: "French in Africa", slug: "french-africa" },
    ],
    'german': [
      { name: "German Grammar", slug: "german-grammar" },
      { name: "German Vocabulary", slug: "german-vocabulary" },
      { name: "History of German", slug: "german-history" },
      { name: "German Dialects", slug: "german-dialects" },
    ],
    'asian': [
      { name: "Mandarin Chinese", slug: "mandarin-chinese" },
      { name: "Japanese Language", slug: "japanese-language" },
      { name: "Korean Language", slug: "korean-language" },
      { name: "Cantonese", slug: "cantonese" },
      { name: "Vietnamese Language", slug: "vietnamese-language" },
      { name: "Thai Language", slug: "thai-language" },
    ],
    'indian': [
      { name: "Hindi", slug: "hindi" },
      { name: "Sanskrit", slug: "sanskrit" },
      { name: "Tamil", slug: "tamil" },
      { name: "Bengali", slug: "bengali" },
      { name: "Telugu", slug: "telugu" },
      { name: "Urdu", slug: "urdu" },
      { name: "Marathi", slug: "marathi" },
      { name: "Gujarati", slug: "gujarati" },
    ],
    'arabic': [
      { name: "Arabic Language", slug: "arabic-language" },
      { name: "Modern Standard Arabic", slug: "modern-standard-arabic" },
      { name: "Arabic Dialects", slug: "arabic-dialects" },
      { name: "Arabic Script", slug: "arabic-script" },
      { name: "Quranic Arabic", slug: "quranic-arabic" },
    ],
    'ancient': [
      { name: "Latin", slug: "latin" },
      { name: "Ancient Greek", slug: "ancient-greek-language" },
      { name: "Hebrew", slug: "hebrew" },
      { name: "Egyptian Hieroglyphics", slug: "hieroglyphics" },
      { name: "Sumerian", slug: "sumerian" },
      { name: "Proto-Indo-European", slug: "proto-indo-european" },
    ],
    'linguistics': [
      { name: "Phonetics", slug: "phonetics" },
      { name: "Syntax", slug: "syntax" },
      { name: "Semantics", slug: "semantics" },
      { name: "Morphology", slug: "morphology" },
      { name: "Sociolinguistics", slug: "sociolinguistics" },
      { name: "Language Acquisition", slug: "language-acquisition" },
      { name: "Bilingualism", slug: "bilingualism" },
      { name: "Sign Languages", slug: "sign-languages" },
    ],
    'etymology': [
      { name: "Word Origins", slug: "word-origins" },
      { name: "Language Evolution", slug: "language-evolution" },
      { name: "Borrowed Words", slug: "borrowed-words" },
      { name: "Eponyms", slug: "eponyms" },
      { name: "Neologisms", slug: "neologisms" },
    ],
    'world-languages': [
      { name: "Portuguese", slug: "portuguese" },
      { name: "Italian", slug: "italian" },
      { name: "Russian", slug: "russian" },
      { name: "Polish", slug: "polish" },
      { name: "Dutch", slug: "dutch" },
      { name: "Swedish", slug: "swedish" },
      { name: "Turkish", slug: "turkish" },
      { name: "Indonesian", slug: "indonesian" },
      { name: "Swahili", slug: "swahili" },
    ],
  },
  'mythology': {
    'greek': [
      { name: "Greek Gods & Goddesses", slug: "greek-gods" },
      { name: "Zeus", slug: "zeus" },
      { name: "Athena", slug: "athena" },
      { name: "Apollo", slug: "apollo" },
      { name: "Poseidon", slug: "poseidon" },
      { name: "Hercules", slug: "hercules" },
      { name: "Odysseus", slug: "odysseus" },
      { name: "Greek Heroes", slug: "greek-heroes" },
      { name: "Greek Monsters", slug: "greek-monsters" },
      { name: "Trojan War", slug: "trojan-war" },
      { name: "Mount Olympus", slug: "mount-olympus" },
    ],
    'norse': [
      { name: "Norse Gods", slug: "norse-gods" },
      { name: "Odin", slug: "odin" },
      { name: "Thor", slug: "thor-mythology" },
      { name: "Loki", slug: "loki-mythology" },
      { name: "Ragnarok", slug: "ragnarok" },
      { name: "Valhalla", slug: "valhalla" },
      { name: "Viking Mythology", slug: "viking-mythology" },
      { name: "Norse Creatures", slug: "norse-creatures" },
    ],
    'egyptian': [
      { name: "Egyptian Gods", slug: "egyptian-gods" },
      { name: "Ra", slug: "ra" },
      { name: "Osiris", slug: "osiris" },
      { name: "Isis", slug: "isis-goddess" },
      { name: "Anubis", slug: "anubis" },
      { name: "Horus", slug: "horus" },
      { name: "Egyptian Afterlife", slug: "egyptian-afterlife" },
      { name: "Book of the Dead", slug: "book-of-dead" },
    ],
    'roman': [
      { name: "Roman Gods", slug: "roman-gods" },
      { name: "Jupiter", slug: "jupiter-god" },
      { name: "Mars", slug: "mars-god" },
      { name: "Venus", slug: "venus-goddess" },
      { name: "Roman vs Greek Gods", slug: "roman-vs-greek" },
      { name: "Romulus & Remus", slug: "romulus-remus" },
    ],
    'hindu': [
      { name: "Hindu Gods", slug: "hindu-gods" },
      { name: "Brahma", slug: "brahma" },
      { name: "Vishnu", slug: "vishnu" },
      { name: "Shiva", slug: "shiva" },
      { name: "Krishna", slug: "krishna" },
      { name: "Ganesh", slug: "ganesh" },
      { name: "Durga", slug: "durga" },
      { name: "Hanuman", slug: "hanuman" },
      { name: "Hindu Demons", slug: "hindu-demons" },
    ],
    'celtic': [
      { name: "Celtic Gods", slug: "celtic-gods" },
      { name: "Celtic Mythology", slug: "celtic-mythology" },
      { name: "Irish Mythology", slug: "irish-mythology" },
      { name: "King Arthur", slug: "king-arthur" },
      { name: "Druids", slug: "druids" },
      { name: "Faeries & Sidhe", slug: "faeries" },
    ],
    'chinese': [
      { name: "Chinese Dragons", slug: "chinese-dragons" },
      { name: "Chinese Gods", slug: "chinese-gods" },
      { name: "Journey to the West", slug: "journey-to-west" },
      { name: "Chinese Mythology", slug: "chinese-mythology" },
      { name: "Jade Emperor", slug: "jade-emperor" },
      { name: "Chinese Legends", slug: "chinese-legends" },
    ],
    'japanese': [
      { name: "Japanese Mythology", slug: "japanese-mythology" },
      { name: "Shinto Gods", slug: "shinto-gods" },
      { name: "Amaterasu", slug: "amaterasu" },
      { name: "Japanese Yokai", slug: "yokai" },
      { name: "Japanese Folklore", slug: "japanese-folklore" },
      { name: "Kitsune", slug: "kitsune" },
    ],
    'native-american': [
      { name: "Native American Mythology", slug: "native-american-myths" },
      { name: "Creation Stories", slug: "creation-stories" },
      { name: "Spirit Animals", slug: "spirit-animals" },
      { name: "Thunderbird", slug: "thunderbird" },
      { name: "Coyote Legends", slug: "coyote-legends" },
    ],
    'african': [
      { name: "African Mythology", slug: "african-mythology" },
      { name: "Anansi", slug: "anansi" },
      { name: "Egyptian Mythology", slug: "egypt-mythology" },
      { name: "Yoruba Mythology", slug: "yoruba-mythology" },
      { name: "African Folklore", slug: "african-folklore" },
    ],
    'world-mythology': [
      { name: "Mesopotamian Mythology", slug: "mesopotamian-mythology" },
      { name: "Persian Mythology", slug: "persian-mythology" },
      { name: "Slavic Mythology", slug: "slavic-mythology" },
      { name: "Aztec Mythology", slug: "aztec-mythology" },
      { name: "Mayan Mythology", slug: "mayan-mythology" },
      { name: "Polynesian Mythology", slug: "polynesian-mythology" },
      { name: "Flood Myths", slug: "flood-myths" },
      { name: "Creation Myths", slug: "creation-myths" },
    ],
  },
  'religion': {
    'christianity': [
      { name: "Jesus Christ", slug: "jesus-christ" },
      { name: "The Bible", slug: "the-bible" },
      { name: "Christian History", slug: "christian-history" },
      { name: "Catholic Church", slug: "catholic-church" },
      { name: "Protestant Reformation", slug: "protestant-reformation" },
      { name: "Orthodox Christianity", slug: "orthodox-christianity" },
      { name: "Christian Saints", slug: "christian-saints" },
      { name: "Christian Holidays", slug: "christian-holidays" },
      { name: "Pope History", slug: "pope-history" },
    ],
    'islam': [
      { name: "Prophet Muhammad", slug: "prophet-muhammad" },
      { name: "The Quran", slug: "the-quran" },
      { name: "Five Pillars of Islam", slug: "five-pillars" },
      { name: "Islamic History", slug: "islamic-history" },
      { name: "Sunni & Shia", slug: "sunni-shia" },
      { name: "Mecca & Medina", slug: "mecca-medina" },
      { name: "Islamic Holidays", slug: "islamic-holidays" },
      { name: "Islamic Caliphates", slug: "islamic-caliphates" },
    ],
    'hinduism': [
      { name: "Hindu Scriptures", slug: "hindu-scriptures" },
      { name: "Vedas", slug: "vedas" },
      { name: "Upanishads", slug: "upanishads" },
      { name: "Hindu Rituals", slug: "hindu-rituals" },
      { name: "Hindu Festivals", slug: "hindu-festivals" },
      { name: "Karma & Dharma", slug: "karma-dharma" },
      { name: "Reincarnation", slug: "reincarnation" },
      { name: "Hindu Temples", slug: "hindu-temples" },
    ],
    'buddhism': [
      { name: "Buddha", slug: "buddha" },
      { name: "Buddhist Teachings", slug: "buddhist-teachings" },
      { name: "Four Noble Truths", slug: "four-noble-truths" },
      { name: "Eightfold Path", slug: "eightfold-path" },
      { name: "Nirvana", slug: "nirvana" },
      { name: "Theravada Buddhism", slug: "theravada" },
      { name: "Mahayana Buddhism", slug: "mahayana" },
      { name: "Buddhist Monasteries", slug: "buddhist-monasteries" },
    ],
    'judaism': [
      { name: "Torah", slug: "torah" },
      { name: "Jewish History", slug: "jewish-history" },
      { name: "Jewish Holidays", slug: "jewish-holidays" },
      { name: "Synagogues", slug: "synagogues" },
      { name: "Kabbalah", slug: "kabbalah" },
      { name: "Holocaust", slug: "holocaust-religion" },
      { name: "Israel History", slug: "israel-history" },
    ],
    'sikhism': [
      { name: "Guru Nanak", slug: "guru-nanak" },
      { name: "Sikh Gurus", slug: "sikh-gurus" },
      { name: "Guru Granth Sahib", slug: "guru-granth-sahib" },
      { name: "Sikh History", slug: "sikh-history" },
      { name: "Golden Temple", slug: "golden-temple" },
      { name: "Sikh Practices", slug: "sikh-practices" },
    ],
    'jainism': [
      { name: "Mahavira", slug: "mahavira" },
      { name: "Jain Philosophy", slug: "jain-philosophy" },
      { name: "Ahimsa", slug: "ahimsa" },
      { name: "Jain Practices", slug: "jain-practices" },
      { name: "Jain Temples", slug: "jain-temples" },
    ],
    'taoism': [
      { name: "Tao Te Ching", slug: "tao-te-ching" },
      { name: "Taoist Philosophy", slug: "taoist-philosophy" },
      { name: "Yin & Yang", slug: "yin-yang" },
      { name: "Taoist Practices", slug: "taoist-practices" },
    ],
    'ancient-religions': [
      { name: "Ancient Egyptian Religion", slug: "ancient-egyptian-religion" },
      { name: "Ancient Greek Religion", slug: "ancient-greek-religion" },
      { name: "Roman Religion", slug: "roman-religion" },
      { name: "Mesopotamian Religion", slug: "mesopotamian-religion" },
      { name: "Zoroastrianism", slug: "zoroastrianism" },
    ],
    'comparative': [
      { name: "Comparative Religion", slug: "comparative-religion" },
      { name: "Religious Symbolism", slug: "religious-symbolism" },
      { name: "Interfaith Dialogue", slug: "interfaith-dialogue" },
      { name: "Atheism & Agnosticism", slug: "atheism-agnosticism" },
      { name: "Religion & Science", slug: "religion-science" },
    ],
    'world-religions': [
      { name: "Shinto", slug: "shinto" },
      { name: "Confucianism", slug: "confucianism" },
      { name: "Baha'i Faith", slug: "bahai" },
      { name: "Indigenous Religions", slug: "indigenous-religions" },
      { name: "New Religious Movements", slug: "new-religious-movements" },
    ],
  },
  'economics': {
    'economists': [
      { name: "Adam Smith", slug: "adam-smith" },
      { name: "John Maynard Keynes", slug: "keynes" },
      { name: "Milton Friedman", slug: "milton-friedman" },
      { name: "Karl Marx (Economics)", slug: "marx-economics" },
      { name: "Paul Krugman", slug: "paul-krugman" },
      { name: "Friedrich Hayek", slug: "hayek" },
      { name: "Thomas Piketty", slug: "piketty" },
      { name: "Amartya Sen", slug: "amartya-sen" },
      { name: "Nobel Prize Economics", slug: "nobel-economics" },
    ],
    'macroeconomics': [
      { name: "GDP", slug: "gdp" },
      { name: "Inflation", slug: "inflation" },
      { name: "Unemployment", slug: "unemployment" },
      { name: "Interest Rates", slug: "interest-rates" },
      { name: "Monetary Policy", slug: "monetary-policy" },
      { name: "Fiscal Policy", slug: "fiscal-policy" },
      { name: "Recession", slug: "recession" },
      { name: "Economic Growth", slug: "economic-growth" },
    ],
    'microeconomics': [
      { name: "Supply & Demand", slug: "supply-demand" },
      { name: "Market Structures", slug: "market-structures" },
      { name: "Price Theory", slug: "price-theory" },
      { name: "Consumer Behavior", slug: "consumer-behavior" },
      { name: "Production Theory", slug: "production-theory" },
      { name: "Game Theory Economics", slug: "game-theory-economics" },
    ],
    'stock-market': [
      { name: "Stock Market History", slug: "stock-market-history" },
      { name: "Wall Street", slug: "wall-street" },
      { name: "NASDAQ", slug: "nasdaq" },
      { name: "NYSE", slug: "nyse" },
      { name: "Stock Market Crashes", slug: "stock-crashes" },
      { name: "Index Funds", slug: "index-funds" },
      { name: "Famous Investors", slug: "famous-investors" },
    ],
    'economic-history': [
      { name: "Great Depression", slug: "great-depression" },
      { name: "2008 Financial Crisis", slug: "2008-crisis" },
      { name: "Bretton Woods", slug: "bretton-woods" },
      { name: "Economic History", slug: "economic-history" },
      { name: "Industrial Revolution Economics", slug: "industrial-economics" },
      { name: "Post-War Economy", slug: "post-war-economy" },
    ],
    'international-trade': [
      { name: "Free Trade", slug: "free-trade" },
      { name: "Globalization Economics", slug: "globalization-economics" },
      { name: "Trade Agreements", slug: "trade-agreements" },
      { name: "WTO", slug: "wto" },
      { name: "Tariffs", slug: "tariffs" },
      { name: "Trade Wars", slug: "trade-wars" },
    ],
    'finance': [
      { name: "Banking", slug: "banking" },
      { name: "Central Banks", slug: "central-banks" },
      { name: "Federal Reserve", slug: "federal-reserve" },
      { name: "Investment Banking", slug: "investment-banking" },
      { name: "Private Equity", slug: "private-equity" },
      { name: "Hedge Funds", slug: "hedge-funds" },
    ],
    'currencies': [
      { name: "US Dollar", slug: "us-dollar" },
      { name: "Euro", slug: "euro" },
      { name: "Currency Exchange", slug: "currency-exchange" },
      { name: "Gold Standard", slug: "gold-standard" },
      { name: "Reserve Currencies", slug: "reserve-currencies" },
    ],
    'cryptocurrency': [
      { name: "Bitcoin", slug: "bitcoin" },
      { name: "Ethereum", slug: "ethereum" },
      { name: "Crypto History", slug: "crypto-history" },
      { name: "Blockchain Economics", slug: "blockchain-economics" },
      { name: "NFT Economics", slug: "nft-economics" },
    ],
    'behavioral': [
      { name: "Behavioral Economics", slug: "behavioral-economics" },
      { name: "Nudge Theory", slug: "nudge-theory" },
      { name: "Richard Thaler", slug: "richard-thaler" },
      { name: "Prospect Theory", slug: "prospect-theory" },
    ],
    'economic-policies': [
      { name: "Capitalism", slug: "capitalism" },
      { name: "Socialism", slug: "socialism-economics" },
      { name: "Communism Economics", slug: "communism-economics" },
      { name: "Mixed Economy", slug: "mixed-economy" },
      { name: "Neoliberalism", slug: "neoliberalism" },
    ],
    'india': [
      { name: "Indian Economy", slug: "indian-economy" },
      { name: "Economic Reforms 1991", slug: "india-1991-reforms" },
      { name: "RBI", slug: "rbi" },
      { name: "Make in India", slug: "make-in-india" },
    ],
  },
  'politics': {
    'political-systems': [
      { name: "Democracy", slug: "democracy" },
      { name: "Monarchy", slug: "monarchy" },
      { name: "Dictatorship", slug: "dictatorship" },
      { name: "Communism", slug: "communism" },
      { name: "Federalism", slug: "federalism" },
      { name: "Parliamentary System", slug: "parliamentary-system" },
      { name: "Presidential System", slug: "presidential-system" },
      { name: "Constitutional Monarchy", slug: "constitutional-monarchy" },
    ],
    'world-leaders': [
      { name: "US Presidents", slug: "us-presidents" },
      { name: "British Prime Ministers", slug: "british-pms" },
      { name: "Indian Prime Ministers", slug: "indian-pms" },
      { name: "Chinese Leaders", slug: "chinese-leaders" },
      { name: "Russian Leaders", slug: "russian-leaders" },
      { name: "European Leaders", slug: "european-leaders" },
      { name: "African Leaders", slug: "african-leaders" },
    ],
    'leaders': [
      { name: "Abraham Lincoln", slug: "lincoln" },
      { name: "Winston Churchill", slug: "churchill" },
      { name: "Mahatma Gandhi", slug: "gandhi" },
      { name: "Nelson Mandela", slug: "mandela" },
      { name: "Franklin D. Roosevelt", slug: "fdr" },
      { name: "John F. Kennedy", slug: "jfk" },
      { name: "Martin Luther King Jr.", slug: "mlk" },
      { name: "Barack Obama", slug: "obama" },
    ],
    'political-parties': [
      { name: "US Political Parties", slug: "us-parties" },
      { name: "UK Political Parties", slug: "uk-parties" },
      { name: "Indian Political Parties", slug: "indian-parties" },
      { name: "Party Systems", slug: "party-systems" },
    ],
    'elections': [
      { name: "US Presidential Elections", slug: "us-elections" },
      { name: "Electoral College", slug: "electoral-college" },
      { name: "Voting Systems", slug: "voting-systems" },
      { name: "Election History", slug: "election-history" },
      { name: "Indian Elections", slug: "indian-elections" },
      { name: "UK Elections", slug: "uk-elections" },
    ],
    'international': [
      { name: "United Nations", slug: "united-nations" },
      { name: "NATO", slug: "nato" },
      { name: "European Union", slug: "european-union" },
      { name: "G7 & G20", slug: "g7-g20" },
      { name: "International Law", slug: "international-law" },
      { name: "Diplomacy", slug: "diplomacy" },
    ],
    'un': [
      { name: "UN History", slug: "un-history" },
      { name: "UN Security Council", slug: "un-security-council" },
      { name: "UN General Assembly", slug: "un-general-assembly" },
      { name: "UN Agencies", slug: "un-agencies" },
      { name: "UN Peacekeeping", slug: "un-peacekeeping" },
    ],
    'constitutions': [
      { name: "US Constitution", slug: "us-constitution" },
      { name: "Indian Constitution", slug: "indian-constitution" },
      { name: "UK Constitution", slug: "uk-constitution" },
      { name: "Bill of Rights", slug: "bill-of-rights" },
      { name: "Constitutional Amendments", slug: "constitutional-amendments" },
    ],
    'movements': [
      { name: "Civil Rights Movement", slug: "civil-rights-movement" },
      { name: "Women's Suffrage", slug: "womens-suffrage" },
      { name: "Indian Independence Movement", slug: "indian-independence" },
      { name: "Anti-Apartheid Movement", slug: "anti-apartheid" },
      { name: "Labor Movements", slug: "labor-movements" },
      { name: "Environmental Movements", slug: "environmental-movements" },
    ],
    'political-history': [
      { name: "Cold War Politics", slug: "cold-war-politics" },
      { name: "American Revolution", slug: "american-revolution" },
      { name: "French Revolution", slug: "french-revolution" },
      { name: "Russian Revolution", slug: "russian-revolution" },
      { name: "Chinese Revolution", slug: "chinese-revolution" },
      { name: "Decolonization", slug: "decolonization" },
    ],
    'laws': [
      { name: "Rule of Law", slug: "rule-of-law" },
      { name: "Human Rights", slug: "human-rights" },
      { name: "Supreme Court Cases", slug: "supreme-court-cases" },
      { name: "Landmark Laws", slug: "landmark-laws" },
    ],
    'india': [
      { name: "Indian Politics", slug: "indian-politics" },
      { name: "Lok Sabha", slug: "lok-sabha" },
      { name: "Rajya Sabha", slug: "rajya-sabha" },
      { name: "Indian Judiciary", slug: "indian-judiciary" },
      { name: "Indian Political History", slug: "indian-political-history" },
    ],
  },
  'epics': {
    'mahabharata': [
      { name: "Mahabharata Overview", slug: "mahabharata-overview" },
      { name: "Pandavas", slug: "pandavas" },
      { name: "Kauravas", slug: "kauravas" },
      { name: "Kurukshetra War", slug: "kurukshetra-war" },
      { name: "Draupadi", slug: "draupadi" },
      { name: "Bhishma", slug: "bhishma" },
      { name: "Karna", slug: "karna" },
      { name: "Arjuna", slug: "arjuna" },
    ],
    'ramayana': [
      { name: "Ramayana Overview", slug: "ramayana-overview" },
      { name: "Lord Rama", slug: "lord-rama" },
      { name: "Sita", slug: "sita" },
      { name: "Hanuman (Ramayana)", slug: "hanuman-ramayana" },
      { name: "Ravana", slug: "ravana" },
      { name: "Ayodhya", slug: "ayodhya" },
      { name: "Lanka", slug: "lanka" },
    ],
    'bhagavad-gita': [
      { name: "Bhagavad Gita Overview", slug: "bhagavad-gita-overview" },
      { name: "Krishna's Teachings", slug: "krishna-teachings" },
      { name: "Karma Yoga", slug: "karma-yoga" },
      { name: "Bhakti Yoga", slug: "bhakti-yoga" },
      { name: "Arjuna's Dilemma", slug: "arjuna-dilemma" },
    ],
    'iliad': [
      { name: "Iliad Overview", slug: "iliad-overview" },
      { name: "Achilles", slug: "achilles" },
      { name: "Hector", slug: "hector" },
      { name: "Helen of Troy", slug: "helen-of-troy" },
      { name: "Paris", slug: "paris-troy" },
      { name: "Trojan War (Iliad)", slug: "trojan-war-iliad" },
    ],
    'odyssey': [
      { name: "Odyssey Overview", slug: "odyssey-overview" },
      { name: "Odysseus Journey", slug: "odysseus-journey" },
      { name: "Penelope", slug: "penelope" },
      { name: "Cyclops", slug: "cyclops" },
      { name: "Sirens", slug: "sirens" },
      { name: "Scylla & Charybdis", slug: "scylla-charybdis" },
    ],
    'aeneid': [
      { name: "Aeneid Overview", slug: "aeneid-overview" },
      { name: "Aeneas", slug: "aeneas" },
      { name: "Virgil", slug: "virgil" },
      { name: "Founding of Rome (Aeneid)", slug: "founding-rome-aeneid" },
    ],
    'beowulf': [
      { name: "Beowulf Overview", slug: "beowulf-overview" },
      { name: "Grendel", slug: "grendel" },
      { name: "Beowulf Hero", slug: "beowulf-hero" },
      { name: "Anglo-Saxon Epic", slug: "anglo-saxon-epic" },
    ],
    'divine-comedy': [
      { name: "Divine Comedy Overview", slug: "divine-comedy-overview" },
      { name: "Dante Alighieri", slug: "dante" },
      { name: "Inferno", slug: "inferno" },
      { name: "Purgatorio", slug: "purgatorio" },
      { name: "Paradiso", slug: "paradiso" },
    ],
    'paradise-lost': [
      { name: "Paradise Lost Overview", slug: "paradise-lost-overview" },
      { name: "John Milton", slug: "john-milton" },
      { name: "Satan (Paradise Lost)", slug: "satan-paradise-lost" },
      { name: "Adam & Eve", slug: "adam-eve" },
    ],
    'indian': [
      { name: "Indian Epics Overview", slug: "indian-epics-overview" },
      { name: "Panchatantra", slug: "panchatantra" },
      { name: "Hitopadesha", slug: "hitopadesha" },
      { name: "Jataka Tales", slug: "jataka-tales" },
    ],
    'puranas': [
      { name: "Puranas Overview", slug: "puranas-overview" },
      { name: "Vishnu Purana", slug: "vishnu-purana" },
      { name: "Shiva Purana", slug: "shiva-purana" },
      { name: "Bhagavata Purana", slug: "bhagavata-purana" },
    ],
  },
  'mathematics': {
    'fundamentals': [
      { name: "Number Systems", slug: "number-systems" },
      { name: "Fractions & Decimals", slug: "fractions-decimals" },
      { name: "Percentages", slug: "percentages" },
      { name: "Ratios & Proportions", slug: "ratios-proportions" },
      { name: "Order of Operations", slug: "order-operations" },
      { name: "Prime Numbers", slug: "prime-numbers" },
    ],
    'algebra': [
      { name: "Linear Equations", slug: "linear-equations" },
      { name: "Quadratic Equations", slug: "quadratic-equations" },
      { name: "Polynomials", slug: "polynomials" },
      { name: "Inequalities", slug: "inequalities" },
      { name: "Functions", slug: "functions-math" },
      { name: "Exponents & Logarithms", slug: "exponents-logarithms" },
      { name: "Systems of Equations", slug: "systems-equations" },
    ],
    'geometry': [
      { name: "Euclidean Geometry", slug: "euclidean-geometry" },
      { name: "Triangles", slug: "triangles" },
      { name: "Circles", slug: "circles" },
      { name: "Polygons", slug: "polygons" },
      { name: "Pythagorean Theorem", slug: "pythagorean-theorem" },
      { name: "Area & Volume", slug: "area-volume" },
      { name: "Coordinate Geometry", slug: "coordinate-geometry" },
      { name: "Transformations", slug: "transformations" },
    ],
    'trigonometry': [
      { name: "Trigonometric Functions", slug: "trig-functions" },
      { name: "Sin, Cos, Tan", slug: "sin-cos-tan" },
      { name: "Trigonometric Identities", slug: "trig-identities" },
      { name: "Unit Circle", slug: "unit-circle" },
      { name: "Inverse Trig Functions", slug: "inverse-trig" },
    ],
    'calculus': [
      { name: "Limits", slug: "limits" },
      { name: "Derivatives", slug: "derivatives" },
      { name: "Integrals", slug: "integrals" },
      { name: "Differential Equations", slug: "differential-equations" },
      { name: "Multivariable Calculus", slug: "multivariable-calculus" },
      { name: "Applications of Calculus", slug: "calculus-applications" },
    ],
    'statistics': [
      { name: "Mean, Median, Mode", slug: "mean-median-mode" },
      { name: "Standard Deviation", slug: "standard-deviation" },
      { name: "Probability", slug: "probability" },
      { name: "Normal Distribution", slug: "normal-distribution" },
      { name: "Hypothesis Testing", slug: "hypothesis-testing" },
      { name: "Regression Analysis", slug: "regression-analysis" },
      { name: "Bayesian Statistics", slug: "bayesian-statistics" },
    ],
    'number-theory': [
      { name: "Divisibility", slug: "divisibility" },
      { name: "Prime Factorization", slug: "prime-factorization" },
      { name: "GCD & LCM", slug: "gcd-lcm" },
      { name: "Modular Arithmetic", slug: "modular-arithmetic" },
      { name: "Fermat's Theorems", slug: "fermats-theorems" },
      { name: "Riemann Hypothesis", slug: "riemann-hypothesis" },
    ],
    'linear-algebra': [
      { name: "Matrices", slug: "matrices" },
      { name: "Vectors", slug: "vectors" },
      { name: "Determinants", slug: "determinants" },
      { name: "Eigenvalues", slug: "eigenvalues" },
      { name: "Linear Transformations", slug: "linear-transformations" },
    ],
    'discrete-math': [
      { name: "Combinatorics", slug: "combinatorics" },
      { name: "Graph Theory", slug: "graph-theory-math" },
      { name: "Set Theory", slug: "set-theory" },
      { name: "Boolean Algebra", slug: "boolean-algebra" },
      { name: "Recurrence Relations", slug: "recurrence-relations" },
    ],
    'logic': [
      { name: "Mathematical Logic", slug: "mathematical-logic" },
      { name: "Proof Techniques", slug: "proof-techniques" },
      { name: "Induction", slug: "induction" },
      { name: "Contradiction", slug: "contradiction" },
    ],
    'advanced': [
      { name: "Topology", slug: "topology" },
      { name: "Abstract Algebra", slug: "abstract-algebra" },
      { name: "Real Analysis", slug: "real-analysis" },
      { name: "Complex Analysis", slug: "complex-analysis" },
      { name: "Numerical Methods", slug: "numerical-methods" },
    ],
    'applied-math': [
      { name: "Mathematical Modeling", slug: "mathematical-modeling" },
      { name: "Operations Research", slug: "operations-research" },
      { name: "Cryptography Math", slug: "cryptography-math" },
      { name: "Game Theory", slug: "game-theory-math" },
      { name: "Financial Mathematics", slug: "financial-math" },
    ],
  },
};

let added = 0;
let skipped = 0;

for (const [category, subcats] of Object.entries(topics)) {
  console.log(`\n=== ${category.toUpperCase()} ===\n`);

  for (const [subcategory, topicList] of Object.entries(subcats)) {
    console.log(`${subcategory}:`);

    for (const topic of topicList) {
      if (existingSlugs.has(topic.slug)) {
        console.log(`  ~ ${topic.name} (exists)`);
        skipped++;
      } else {
        ensureTopic({
          category,
          subcategory,
          slug: topic.slug,
          name: topic.name,
        });
        existingSlugs.add(topic.slug);
        console.log(`  + ${topic.name}`);
        added++;
      }
    }
    console.log();
  }
}

console.log(`✓ Added: ${added} topics`);
console.log(`- Skipped: ${skipped} (already exist)`);

// Show total
const totalTopics = categories.flatMap(c => getTopics(c)).length;
console.log(`\nTotal topics in these categories: ${totalTopics}`);
