/**
 * Seed movie topics for all subcategories
 */

import { ensureTopic, getTopics, initRegistry } from '../src/lib/registry';

initRegistry();

// Get existing topics to avoid duplicates
const existingTopics = getTopics('movies');
const existingSlugs = new Set(existingTopics.map(t => t.slug));

const movies: Record<string, Array<{ name: string; slug: string }>> = {
  action: [
    { name: "Die Hard", slug: "die-hard" },
    { name: "Mad Max: Fury Road", slug: "mad-max-fury-road" },
    { name: "The Dark Knight", slug: "the-dark-knight" },
    { name: "Gladiator", slug: "gladiator" },
    { name: "John Wick", slug: "john-wick" },
    { name: "Kill Bill", slug: "kill-bill" },
    { name: "The Matrix", slug: "the-matrix-movie" },
    { name: "Terminator 2: Judgment Day", slug: "terminator-2" },
    { name: "Top Gun", slug: "top-gun" },
    { name: "Top Gun: Maverick", slug: "top-gun-maverick" },
    { name: "Mission: Impossible Series", slug: "mission-impossible-movies" },
    { name: "The Bourne Identity", slug: "bourne-identity" },
    { name: "Casino Royale", slug: "casino-royale" },
    { name: "Skyfall", slug: "skyfall" },
    { name: "Raiders of the Lost Ark", slug: "raiders-of-the-lost-ark" },
    { name: "Crouching Tiger, Hidden Dragon", slug: "crouching-tiger" },
    { name: "The Raid", slug: "the-raid" },
    { name: "300", slug: "300" },
    { name: "Extraction", slug: "extraction" },
    { name: "Nobody", slug: "nobody" },
    { name: "Atomic Blonde", slug: "atomic-blonde" },
    { name: "Heat", slug: "heat" },
    { name: "Speed", slug: "speed" },
    { name: "Lethal Weapon", slug: "lethal-weapon" },
    { name: "Beverly Hills Cop", slug: "beverly-hills-cop" },
  ],

  comedy: [
    { name: "Superbad", slug: "superbad" },
    { name: "The Hangover", slug: "the-hangover" },
    { name: "Bridesmaids", slug: "bridesmaids" },
    { name: "Anchorman", slug: "anchorman" },
    { name: "Step Brothers", slug: "step-brothers" },
    { name: "Dumb and Dumber", slug: "dumb-and-dumber" },
    { name: "There's Something About Mary", slug: "theres-something-about-mary" },
    { name: "Groundhog Day", slug: "groundhog-day" },
    { name: "The Big Lebowski", slug: "the-big-lebowski" },
    { name: "Ferris Bueller's Day Off", slug: "ferris-buellers-day-off" },
    { name: "Home Alone", slug: "home-alone" },
    { name: "Mrs. Doubtfire", slug: "mrs-doubtfire" },
    { name: "Airplane!", slug: "airplane" },
    { name: "The Naked Gun", slug: "the-naked-gun" },
    { name: "Ghostbusters", slug: "ghostbusters" },
    { name: "Coming to America", slug: "coming-to-america" },
    { name: "Trading Places", slug: "trading-places" },
    { name: "Caddyshack", slug: "caddyshack" },
    { name: "Animal House", slug: "animal-house" },
    { name: "Blazing Saddles", slug: "blazing-saddles" },
    { name: "Monty Python and the Holy Grail", slug: "monty-python-holy-grail" },
    { name: "Life of Brian", slug: "life-of-brian" },
    { name: "Shaun of the Dead", slug: "shaun-of-the-dead" },
    { name: "Hot Fuzz", slug: "hot-fuzz" },
    { name: "The Grand Budapest Hotel", slug: "grand-budapest-hotel" },
    { name: "Knives Out", slug: "knives-out" },
    { name: "Game Night", slug: "game-night" },
    { name: "21 Jump Street", slug: "21-jump-street" },
    { name: "Tropic Thunder", slug: "tropic-thunder" },
    { name: "Borat", slug: "borat" },
  ],

  drama: [
    { name: "The Shawshank Redemption", slug: "shawshank-redemption" },
    { name: "The Godfather", slug: "the-godfather" },
    { name: "The Godfather Part II", slug: "the-godfather-2" },
    { name: "Schindler's List", slug: "schindlers-list" },
    { name: "Forrest Gump", slug: "forrest-gump" },
    { name: "Fight Club", slug: "fight-club" },
    { name: "Pulp Fiction", slug: "pulp-fiction" },
    { name: "Goodfellas", slug: "goodfellas" },
    { name: "The Green Mile", slug: "the-green-mile" },
    { name: "A Beautiful Mind", slug: "a-beautiful-mind" },
    { name: "American Beauty", slug: "american-beauty" },
    { name: "The Departed", slug: "the-departed" },
    { name: "No Country for Old Men", slug: "no-country-for-old-men" },
    { name: "There Will Be Blood", slug: "there-will-be-blood" },
    { name: "12 Years a Slave", slug: "12-years-a-slave" },
    { name: "Moonlight", slug: "moonlight" },
    { name: "Parasite", slug: "parasite" },
    { name: "Whiplash", slug: "whiplash" },
    { name: "The Social Network", slug: "the-social-network" },
    { name: "Birdman", slug: "birdman" },
    { name: "Spotlight", slug: "spotlight" },
    { name: "Manchester by the Sea", slug: "manchester-by-the-sea" },
    { name: "Marriage Story", slug: "marriage-story" },
    { name: "Oppenheimer", slug: "oppenheimer" },
    { name: "Killers of the Flower Moon", slug: "killers-of-the-flower-moon" },
    { name: "The Pianist", slug: "the-pianist" },
    { name: "Million Dollar Baby", slug: "million-dollar-baby" },
    { name: "Titanic", slug: "titanic" },
    { name: "The Revenant", slug: "the-revenant" },
    { name: "The Wolf of Wall Street", slug: "wolf-of-wall-street" },
  ],

  horror: [
    { name: "The Shining", slug: "the-shining" },
    { name: "The Exorcist", slug: "the-exorcist" },
    { name: "Psycho", slug: "psycho" },
    { name: "Halloween", slug: "halloween" },
    { name: "A Nightmare on Elm Street", slug: "nightmare-on-elm-street" },
    { name: "Friday the 13th", slug: "friday-the-13th" },
    { name: "Scream", slug: "scream" },
    { name: "The Silence of the Lambs", slug: "silence-of-the-lambs" },
    { name: "Get Out", slug: "get-out" },
    { name: "Us", slug: "us" },
    { name: "Hereditary", slug: "hereditary" },
    { name: "Midsommar", slug: "midsommar" },
    { name: "The Conjuring", slug: "the-conjuring" },
    { name: "It", slug: "it-2017" },
    { name: "A Quiet Place", slug: "a-quiet-place" },
    { name: "The Ring", slug: "the-ring" },
    { name: "The Grudge", slug: "the-grudge" },
    { name: "Saw", slug: "saw" },
    { name: "The Texas Chain Saw Massacre", slug: "texas-chainsaw-massacre" },
    { name: "Rosemary's Baby", slug: "rosemarys-baby" },
    { name: "The Omen", slug: "the-omen" },
    { name: "Poltergeist", slug: "poltergeist" },
    { name: "The Blair Witch Project", slug: "blair-witch-project" },
    { name: "Paranormal Activity", slug: "paranormal-activity" },
    { name: "Nope", slug: "nope" },
    { name: "Pearl", slug: "pearl" },
    { name: "Barbarian", slug: "barbarian" },
    { name: "Talk to Me", slug: "talk-to-me" },
  ],

  "sci-fi": [
    { name: "2001: A Space Odyssey", slug: "2001-space-odyssey" },
    { name: "Blade Runner", slug: "blade-runner" },
    { name: "Blade Runner 2049", slug: "blade-runner-2049" },
    { name: "Alien", slug: "alien" },
    { name: "Aliens", slug: "aliens" },
    { name: "E.T. the Extra-Terrestrial", slug: "et" },
    { name: "Close Encounters of the Third Kind", slug: "close-encounters" },
    { name: "Back to the Future", slug: "back-to-the-future" },
    { name: "The Terminator", slug: "the-terminator" },
    { name: "Jurassic Park", slug: "jurassic-park-movie" },
    { name: "Inception", slug: "inception" },
    { name: "Interstellar", slug: "interstellar" },
    { name: "Arrival", slug: "arrival" },
    { name: "Ex Machina", slug: "ex-machina" },
    { name: "District 9", slug: "district-9" },
    { name: "Edge of Tomorrow", slug: "edge-of-tomorrow" },
    { name: "The Martian", slug: "the-martian" },
    { name: "Gravity", slug: "gravity" },
    { name: "Moon", slug: "moon" },
    { name: "Looper", slug: "looper" },
    { name: "Minority Report", slug: "minority-report" },
    { name: "Total Recall", slug: "total-recall" },
    { name: "RoboCop", slug: "robocop" },
    { name: "The Fifth Element", slug: "the-fifth-element" },
    { name: "Dune (2021)", slug: "dune-2021" },
    { name: "Dune: Part Two", slug: "dune-part-two" },
    { name: "Everything Everywhere All at Once", slug: "everything-everywhere" },
    { name: "Tenet", slug: "tenet" },
    { name: "Annihilation", slug: "annihilation" },
    { name: "Her", slug: "her" },
  ],

  fantasy: [
    { name: "The Lord of the Rings: Fellowship", slug: "lotr-fellowship" },
    { name: "The Lord of the Rings: Two Towers", slug: "lotr-two-towers" },
    { name: "The Lord of the Rings: Return of the King", slug: "lotr-return-king" },
    { name: "The Hobbit Trilogy", slug: "the-hobbit-trilogy" },
    { name: "Harry Potter and the Sorcerer's Stone", slug: "harry-potter-1" },
    { name: "Harry Potter and the Prisoner of Azkaban", slug: "harry-potter-3" },
    { name: "Harry Potter and the Goblet of Fire", slug: "harry-potter-4" },
    { name: "Harry Potter and the Deathly Hallows", slug: "harry-potter-7" },
    { name: "The Princess Bride", slug: "the-princess-bride" },
    { name: "Pan's Labyrinth", slug: "pans-labyrinth" },
    { name: "The Wizard of Oz", slug: "wizard-of-oz" },
    { name: "Willow", slug: "willow" },
    { name: "Stardust", slug: "stardust" },
    { name: "The NeverEnding Story", slug: "neverending-story" },
    { name: "Labyrinth", slug: "labyrinth" },
    { name: "The Dark Crystal", slug: "dark-crystal" },
    { name: "Conan the Barbarian", slug: "conan-the-barbarian" },
    { name: "Highlander", slug: "highlander" },
    { name: "Edward Scissorhands", slug: "edward-scissorhands" },
    { name: "Big Fish", slug: "big-fish" },
    { name: "The Shape of Water", slug: "shape-of-water" },
    { name: "Fantastic Beasts", slug: "fantastic-beasts" },
    { name: "Narnia: The Lion, the Witch and the Wardrobe", slug: "narnia-lion-witch-wardrobe" },
    { name: "Percy Jackson", slug: "percy-jackson-movies" },
    { name: "Eragon", slug: "eragon" },
  ],

  animated: [
    { name: "Toy Story", slug: "toy-story" },
    { name: "Toy Story 2", slug: "toy-story-2" },
    { name: "Toy Story 3", slug: "toy-story-3" },
    { name: "Finding Nemo", slug: "finding-nemo" },
    { name: "The Incredibles", slug: "the-incredibles" },
    { name: "Up", slug: "up" },
    { name: "WALL-E", slug: "wall-e" },
    { name: "Inside Out", slug: "inside-out" },
    { name: "Coco", slug: "coco" },
    { name: "Soul", slug: "soul" },
    { name: "The Lion King", slug: "the-lion-king" },
    { name: "Aladdin", slug: "aladdin" },
    { name: "Beauty and the Beast", slug: "beauty-and-the-beast" },
    { name: "The Little Mermaid", slug: "the-little-mermaid" },
    { name: "Frozen", slug: "frozen" },
    { name: "Moana", slug: "moana" },
    { name: "Encanto", slug: "encanto" },
    { name: "Shrek", slug: "shrek" },
    { name: "Shrek 2", slug: "shrek-2" },
    { name: "How to Train Your Dragon", slug: "how-to-train-your-dragon" },
    { name: "Kung Fu Panda", slug: "kung-fu-panda" },
    { name: "Madagascar", slug: "madagascar" },
    { name: "Despicable Me", slug: "despicable-me" },
    { name: "Minions", slug: "minions" },
    { name: "Spider-Man: Into the Spider-Verse", slug: "spider-verse" },
    { name: "Spider-Man: Across the Spider-Verse", slug: "across-spider-verse" },
    { name: "The Nightmare Before Christmas", slug: "nightmare-before-christmas" },
    { name: "Spirited Away", slug: "spirited-away" },
    { name: "My Neighbor Totoro", slug: "my-neighbor-totoro" },
    { name: "Princess Mononoke", slug: "princess-mononoke" },
    { name: "Howl's Moving Castle", slug: "howls-moving-castle" },
    { name: "Your Name", slug: "your-name" },
    { name: "Akira", slug: "akira" },
    { name: "Ghost in the Shell", slug: "ghost-in-the-shell" },
  ],

  classics: [
    { name: "Casablanca", slug: "casablanca" },
    { name: "Citizen Kane", slug: "citizen-kane" },
    { name: "Gone with the Wind", slug: "gone-with-the-wind" },
    { name: "It's a Wonderful Life", slug: "its-a-wonderful-life" },
    { name: "Singin' in the Rain", slug: "singin-in-the-rain" },
    { name: "Some Like It Hot", slug: "some-like-it-hot" },
    { name: "Sunset Boulevard", slug: "sunset-boulevard" },
    { name: "12 Angry Men", slug: "12-angry-men" },
    { name: "The Apartment", slug: "the-apartment" },
    { name: "Roman Holiday", slug: "roman-holiday" },
    { name: "Breakfast at Tiffany's", slug: "breakfast-at-tiffanys" },
    { name: "The Sound of Music", slug: "sound-of-music" },
    { name: "West Side Story (1961)", slug: "west-side-story-1961" },
    { name: "Lawrence of Arabia", slug: "lawrence-of-arabia" },
    { name: "Ben-Hur", slug: "ben-hur" },
    { name: "The Ten Commandments", slug: "ten-commandments" },
    { name: "Spartacus", slug: "spartacus" },
    { name: "The Bridge on the River Kwai", slug: "bridge-on-river-kwai" },
    { name: "To Kill a Mockingbird", slug: "to-kill-a-mockingbird" },
    { name: "On the Waterfront", slug: "on-the-waterfront" },
    { name: "Vertigo", slug: "vertigo" },
    { name: "Rear Window", slug: "rear-window" },
    { name: "North by Northwest", slug: "north-by-northwest" },
    { name: "The Birds", slug: "the-birds" },
    { name: "Rebel Without a Cause", slug: "rebel-without-a-cause" },
  ],

  directors: [
    { name: "Steven Spielberg Filmography", slug: "spielberg-films" },
    { name: "Martin Scorsese Filmography", slug: "scorsese-films" },
    { name: "Christopher Nolan Filmography", slug: "nolan-films" },
    { name: "Quentin Tarantino Filmography", slug: "tarantino-films" },
    { name: "Stanley Kubrick Filmography", slug: "kubrick-films" },
    { name: "Alfred Hitchcock Filmography", slug: "hitchcock-films" },
    { name: "Denis Villeneuve Filmography", slug: "villeneuve-films" },
    { name: "Wes Anderson Filmography", slug: "wes-anderson-films" },
    { name: "David Fincher Filmography", slug: "fincher-films" },
    { name: "Ridley Scott Filmography", slug: "ridley-scott-films" },
    { name: "James Cameron Filmography", slug: "james-cameron-films" },
    { name: "Peter Jackson Filmography", slug: "peter-jackson-films" },
    { name: "Coen Brothers Filmography", slug: "coen-brothers-films" },
    { name: "Tim Burton Filmography", slug: "tim-burton-films" },
    { name: "Guillermo del Toro Filmography", slug: "del-toro-films" },
    { name: "Hayao Miyazaki Filmography", slug: "miyazaki-films" },
    { name: "Bong Joon-ho Filmography", slug: "bong-joon-ho-films" },
    { name: "Greta Gerwig Filmography", slug: "greta-gerwig-films" },
    { name: "Jordan Peele Filmography", slug: "jordan-peele-films" },
    { name: "Ari Aster Filmography", slug: "ari-aster-films" },
    { name: "Edgar Wright Filmography", slug: "edgar-wright-films" },
    { name: "Damien Chazelle Filmography", slug: "damien-chazelle-films" },
    { name: "Taika Waititi Filmography", slug: "taika-waititi-films" },
    { name: "Akira Kurosawa Filmography", slug: "kurosawa-films" },
  ],

  franchises: [
    // Already have: DC, Fast & Furious, Harry Potter, Indiana Jones, James Bond,
    // Jurassic Park, LOTR, Marvel, Mission Impossible, Pirates, Star Wars, Matrix
    { name: "Alien Franchise", slug: "alien-franchise" },
    { name: "Terminator Franchise", slug: "terminator-franchise" },
    { name: "Planet of the Apes", slug: "planet-of-the-apes" },
    { name: "Rocky / Creed Series", slug: "rocky-creed" },
    { name: "John Wick Series", slug: "john-wick-series" },
    { name: "The Hunger Games", slug: "hunger-games" },
    { name: "Twilight Saga", slug: "twilight-saga" },
    { name: "Transformers", slug: "transformers" },
    { name: "X-Men Series", slug: "x-men-series" },
    { name: "Spider-Man (Tobey Maguire)", slug: "spiderman-tobey" },
    { name: "The Amazing Spider-Man", slug: "amazing-spiderman" },
    { name: "Spider-Man (Tom Holland)", slug: "spiderman-tom-holland" },
    { name: "Batman (Tim Burton/Joel Schumacher)", slug: "batman-burton" },
    { name: "The Dark Knight Trilogy", slug: "dark-knight-trilogy" },
    { name: "Toy Story Series", slug: "toy-story-series" },
    { name: "Shrek Series", slug: "shrek-series" },
    { name: "Ice Age Series", slug: "ice-age-series" },
    { name: "Despicable Me / Minions", slug: "despicable-me-franchise" },
    { name: "The Conjuring Universe", slug: "conjuring-universe" },
    { name: "Saw Franchise", slug: "saw-franchise" },
    { name: "Halloween Franchise", slug: "halloween-franchise" },
    { name: "Scream Franchise", slug: "scream-franchise" },
    { name: "Final Destination", slug: "final-destination" },
    { name: "Monsterverse (Godzilla/Kong)", slug: "monsterverse" },
    { name: "Dune Series", slug: "dune-series" },
  ],

  studios: [
    // Already have: Disney, DreamWorks, Pixar, Studio Ghibli
    { name: "Warner Bros.", slug: "warner-bros" },
    { name: "Universal Pictures", slug: "universal-pictures" },
    { name: "Paramount Pictures", slug: "paramount-pictures" },
    { name: "20th Century Studios", slug: "20th-century-studios" },
    { name: "Sony Pictures", slug: "sony-pictures" },
    { name: "Lionsgate", slug: "lionsgate" },
    { name: "A24", slug: "a24" },
    { name: "Blumhouse Productions", slug: "blumhouse" },
    { name: "Illumination", slug: "illumination" },
    { name: "Laika", slug: "laika" },
    { name: "Aardman Animations", slug: "aardman" },
    { name: "Blue Sky Studios", slug: "blue-sky-studios" },
    { name: "Marvel Studios", slug: "marvel-studios" },
    { name: "DC Studios", slug: "dc-studios" },
    { name: "Lucasfilm", slug: "lucasfilm" },
  ],

  awards: [
    // Already have: Oscar Awards, BAFTA, Golden Globes
    { name: "Best Picture Winners", slug: "best-picture-winners" },
    { name: "Best Director Winners", slug: "best-director-winners" },
    { name: "Best Actor Winners", slug: "best-actor-winners" },
    { name: "Best Actress Winners", slug: "best-actress-winners" },
    { name: "AFI Top 100 Films", slug: "afi-top-100" },
    { name: "Cannes Palme d'Or Winners", slug: "cannes-palme-dor" },
    { name: "Venice Golden Lion Winners", slug: "venice-golden-lion" },
    { name: "Berlin Golden Bear Winners", slug: "berlin-golden-bear" },
    { name: "Sundance Award Winners", slug: "sundance-winners" },
    { name: "Critics Choice Awards", slug: "critics-choice-movies" },
    { name: "Screen Actors Guild Awards", slug: "sag-awards-movies" },
    { name: "Razzie Awards", slug: "razzie-awards" },
  ],

  genres: [
    // Already have: 80s classics, 90s classics, Action Blockbusters, Animated Movies,
    // Classic Hollywood, Documentary Films, Horror Classics, Oscar Winners, Rom-Coms
    { name: "Film Noir", slug: "film-noir" },
    { name: "Westerns", slug: "westerns" },
    { name: "Musicals", slug: "musicals" },
    { name: "War Films", slug: "war-films" },
    { name: "Sports Movies", slug: "sports-movies" },
    { name: "Heist Movies", slug: "heist-movies" },
    { name: "Courtroom Dramas", slug: "courtroom-dramas" },
    { name: "Disaster Movies", slug: "disaster-movies" },
    { name: "Superhero Movies", slug: "superhero-movies" },
    { name: "Spy Movies", slug: "spy-movies" },
    { name: "Buddy Cop Movies", slug: "buddy-cop-movies" },
    { name: "Coming-of-Age Films", slug: "coming-of-age" },
    { name: "Biopics", slug: "biopics" },
    { name: "Cult Classics", slug: "cult-classics" },
    { name: "Midnight Movies", slug: "midnight-movies" },
    { name: "Foreign Language Films", slug: "foreign-language-films" },
    { name: "Bollywood Films", slug: "bollywood-films" },
    { name: "Korean Cinema", slug: "korean-cinema" },
    { name: "Japanese Cinema", slug: "japanese-cinema" },
    { name: "French Cinema", slug: "french-cinema" },
  ],
};

let added = 0;
let skipped = 0;

for (const [subcategory, movieList] of Object.entries(movies)) {
  console.log(`\n${subcategory}:`);

  for (const movie of movieList) {
    if (existingSlugs.has(movie.slug)) {
      console.log(`  - ${movie.name} (exists)`);
      skipped++;
      continue;
    }

    ensureTopic({
      category: 'movies',
      subcategory,
      slug: movie.slug,
      name: movie.name,
      source_type: 'script',
    });

    console.log(`  + ${movie.name}`);
    added++;
  }
}

console.log(`\n✓ Added: ${added} movies`);
console.log(`- Skipped: ${skipped} (already exist)`);

// Final count
const allTopics = getTopics('movies');
console.log(`\nTotal movie topics: ${allTopics.length}`);
