/**
 * Seed science topics for all science categories
 */

import { ensureTopic, getTopics, initRegistry } from '../src/lib/registry';

initRegistry();

// Get existing topics
const existingTopics = [
  ...getTopics('physics'),
  ...getTopics('chemistry'),
  ...getTopics('biology'),
  ...getTopics('space'),
  ...getTopics('environment'),
  ...getTopics('animals'),
  ...getTopics('plants'),
];
const existingSlugs = new Set(existingTopics.map(t => t.slug));

const science: Record<string, Record<string, Array<{ name: string; slug: string }>>> = {
  'physics': {
    'mechanics': [
      { name: "Newton's Laws of Motion", slug: "newtons-laws" },
      { name: "Classical Mechanics", slug: "classical-mechanics" },
      { name: "Kinematics", slug: "kinematics" },
      { name: "Work, Energy & Power", slug: "work-energy-power" },
      { name: "Momentum & Collisions", slug: "momentum-collisions" },
      { name: "Rotational Motion", slug: "rotational-motion" },
      { name: "Gravitation", slug: "gravitation" },
      { name: "Simple Harmonic Motion", slug: "simple-harmonic-motion" },
      { name: "Fluid Mechanics", slug: "fluid-mechanics" },
      { name: "Projectile Motion", slug: "projectile-motion" },
      { name: "Friction & Forces", slug: "friction-forces" },
      { name: "Lagrangian Mechanics", slug: "lagrangian-mechanics" },
    ],
    'electromagnetism': [
      { name: "Electric Fields", slug: "electric-fields" },
      { name: "Magnetic Fields", slug: "magnetic-fields" },
      { name: "Electromagnetic Waves", slug: "electromagnetic-waves" },
      { name: "Maxwell's Equations", slug: "maxwells-equations" },
      { name: "Electric Circuits", slug: "electric-circuits" },
      { name: "Capacitance & Inductance", slug: "capacitance-inductance" },
      { name: "Ohm's Law & Resistance", slug: "ohms-law" },
      { name: "Electromagnetic Induction", slug: "em-induction" },
      { name: "AC & DC Current", slug: "ac-dc-current" },
      { name: "Coulomb's Law", slug: "coulombs-law" },
      { name: "Faraday's Laws", slug: "faradays-laws" },
      { name: "Lenz's Law", slug: "lenzs-law" },
    ],
    'thermodynamics': [
      { name: "Laws of Thermodynamics", slug: "laws-thermodynamics" },
      { name: "Heat Transfer", slug: "heat-transfer" },
      { name: "Entropy", slug: "entropy" },
      { name: "Carnot Cycle", slug: "carnot-cycle" },
      { name: "Ideal Gas Laws", slug: "ideal-gas-laws" },
      { name: "Kinetic Theory of Gases", slug: "kinetic-theory" },
      { name: "Thermal Expansion", slug: "thermal-expansion" },
      { name: "Specific Heat Capacity", slug: "specific-heat" },
      { name: "Phase Transitions", slug: "phase-transitions" },
      { name: "Stefan-Boltzmann Law", slug: "stefan-boltzmann" },
      { name: "Heat Engines", slug: "heat-engines" },
      { name: "Absolute Zero", slug: "absolute-zero" },
    ],
    'quantum': [
      { name: "Wave-Particle Duality", slug: "wave-particle-duality" },
      { name: "Heisenberg Uncertainty Principle", slug: "uncertainty-principle" },
      { name: "Schrödinger Equation", slug: "schrodinger-equation" },
      { name: "Quantum Entanglement", slug: "quantum-entanglement" },
      { name: "Superposition", slug: "superposition" },
      { name: "Quantum Tunneling", slug: "quantum-tunneling" },
      { name: "Photoelectric Effect", slug: "photoelectric-effect" },
      { name: "Planck's Constant", slug: "plancks-constant" },
      { name: "Quantum Computing", slug: "quantum-computing" },
      { name: "Bohr Model", slug: "bohr-model" },
      { name: "Spin & Pauli Exclusion", slug: "spin-pauli" },
      { name: "Quantum Field Theory", slug: "quantum-field-theory" },
    ],
    'relativity': [
      { name: "Special Relativity", slug: "special-relativity" },
      { name: "General Relativity", slug: "general-relativity" },
      { name: "Time Dilation", slug: "time-dilation" },
      { name: "Length Contraction", slug: "length-contraction" },
      { name: "E=mc²", slug: "mass-energy-equivalence" },
      { name: "Spacetime", slug: "spacetime" },
      { name: "Gravitational Waves", slug: "gravitational-waves" },
      { name: "Twin Paradox", slug: "twin-paradox" },
      { name: "Black Holes & Relativity", slug: "black-holes-relativity" },
      { name: "Light Speed Limit", slug: "speed-of-light" },
      { name: "Lorentz Transformation", slug: "lorentz-transformation" },
      { name: "Einstein's Thought Experiments", slug: "einstein-thought-experiments" },
    ],
    'optics': [
      { name: "Reflection & Refraction", slug: "reflection-refraction" },
      { name: "Lenses & Mirrors", slug: "lenses-mirrors" },
      { name: "Diffraction", slug: "diffraction" },
      { name: "Interference", slug: "interference" },
      { name: "Polarization", slug: "polarization" },
      { name: "Fiber Optics", slug: "fiber-optics" },
      { name: "Snell's Law", slug: "snells-law" },
      { name: "Optical Instruments", slug: "optical-instruments" },
      { name: "Laser Physics", slug: "laser-physics" },
      { name: "Color & Spectrum", slug: "color-spectrum" },
      { name: "Total Internal Reflection", slug: "total-internal-reflection" },
      { name: "Holography", slug: "holography" },
    ],
    'nuclear': [
      { name: "Nuclear Fission", slug: "nuclear-fission" },
      { name: "Nuclear Fusion", slug: "nuclear-fusion" },
      { name: "Radioactivity", slug: "radioactivity" },
      { name: "Half-Life", slug: "half-life" },
      { name: "Alpha, Beta, Gamma Radiation", slug: "radiation-types" },
      { name: "Nuclear Reactors", slug: "nuclear-reactors" },
      { name: "Nuclear Weapons", slug: "nuclear-weapons" },
      { name: "Binding Energy", slug: "binding-energy" },
      { name: "Mass Defect", slug: "mass-defect" },
      { name: "Carbon Dating", slug: "carbon-dating" },
      { name: "Nuclear Medicine", slug: "nuclear-medicine" },
      { name: "Chernobyl & Fukushima", slug: "nuclear-disasters" },
    ],
    'waves': [
      { name: "Wave Properties", slug: "wave-properties" },
      { name: "Sound Waves", slug: "sound-waves" },
      { name: "Doppler Effect", slug: "doppler-effect" },
      { name: "Standing Waves", slug: "standing-waves" },
      { name: "Resonance", slug: "resonance" },
      { name: "Ultrasound", slug: "ultrasound" },
      { name: "Acoustics", slug: "acoustics" },
      { name: "Longitudinal & Transverse Waves", slug: "wave-types" },
      { name: "Wave Equation", slug: "wave-equation" },
      { name: "Beats & Harmonics", slug: "beats-harmonics" },
      { name: "Seismic Waves", slug: "seismic-waves" },
      { name: "Speed of Sound", slug: "speed-of-sound" },
    ],
    'particle': [
      { name: "Standard Model", slug: "standard-model" },
      { name: "Quarks & Leptons", slug: "quarks-leptons" },
      { name: "Higgs Boson", slug: "higgs-boson" },
      { name: "Antimatter", slug: "antimatter" },
      { name: "Particle Accelerators", slug: "particle-accelerators" },
      { name: "CERN & LHC", slug: "cern-lhc" },
      { name: "Neutrinos", slug: "neutrinos" },
      { name: "Dark Matter", slug: "dark-matter" },
      { name: "Bosons & Fermions", slug: "bosons-fermions" },
      { name: "Fundamental Forces", slug: "fundamental-forces" },
      { name: "String Theory", slug: "string-theory" },
      { name: "Feynman Diagrams", slug: "feynman-diagrams" },
    ],
    'astrophysics': [
      { name: "Stellar Evolution", slug: "stellar-evolution" },
      { name: "Neutron Stars", slug: "neutron-stars" },
      { name: "Pulsars", slug: "pulsars" },
      { name: "Supernovae", slug: "supernovae" },
      { name: "Black Hole Physics", slug: "black-hole-physics" },
      { name: "Hawking Radiation", slug: "hawking-radiation" },
      { name: "Cosmic Microwave Background", slug: "cmb" },
      { name: "Dark Energy", slug: "dark-energy" },
      { name: "Redshift & Hubble's Law", slug: "redshift-hubble" },
      { name: "Big Bang Theory", slug: "big-bang-physics" },
      { name: "Gravitational Lensing", slug: "gravitational-lensing" },
      { name: "Quasars", slug: "quasars" },
    ],
  },

  'chemistry': {
    'elements': [
      { name: "Periodic Table History", slug: "periodic-table-history" },
      { name: "Alkali Metals", slug: "alkali-metals" },
      { name: "Noble Gases", slug: "noble-gases" },
      { name: "Transition Metals", slug: "transition-metals" },
      { name: "Halogens", slug: "halogens" },
      { name: "Lanthanides & Actinides", slug: "lanthanides-actinides" },
      { name: "Element Discovery History", slug: "element-discovery" },
      { name: "Atomic Structure", slug: "atomic-structure" },
      { name: "Isotopes", slug: "isotopes" },
      { name: "Electron Configuration", slug: "electron-configuration" },
      { name: "Mendeleev's Contributions", slug: "mendeleev" },
      { name: "Synthetic Elements", slug: "synthetic-elements" },
    ],
    'reactions': [
      { name: "Types of Chemical Reactions", slug: "reaction-types" },
      { name: "Oxidation-Reduction", slug: "redox-reactions" },
      { name: "Acid-Base Reactions", slug: "acid-base-reactions" },
      { name: "Combustion", slug: "combustion" },
      { name: "Precipitation Reactions", slug: "precipitation" },
      { name: "Catalysis", slug: "catalysis" },
      { name: "Reaction Kinetics", slug: "reaction-kinetics" },
      { name: "Chemical Equilibrium", slug: "chemical-equilibrium" },
      { name: "Le Chatelier's Principle", slug: "le-chatelier" },
      { name: "Activation Energy", slug: "activation-energy" },
      { name: "Exothermic & Endothermic", slug: "exo-endothermic" },
      { name: "Stoichiometry", slug: "stoichiometry" },
    ],
    'organic': [
      { name: "Hydrocarbons", slug: "hydrocarbons" },
      { name: "Functional Groups", slug: "functional-groups" },
      { name: "Alcohols & Ethers", slug: "alcohols-ethers" },
      { name: "Aldehydes & Ketones", slug: "aldehydes-ketones" },
      { name: "Carboxylic Acids", slug: "carboxylic-acids" },
      { name: "Esters & Amides", slug: "esters-amides" },
      { name: "Polymers & Plastics", slug: "polymers-plastics" },
      { name: "Aromatic Compounds", slug: "aromatic-compounds" },
      { name: "Isomerism", slug: "isomerism" },
      { name: "Organic Synthesis", slug: "organic-synthesis" },
      { name: "Petrochemicals", slug: "petrochemicals" },
      { name: "Pharmaceuticals", slug: "pharmaceuticals" },
    ],
    'inorganic': [
      { name: "Coordination Compounds", slug: "coordination-compounds" },
      { name: "Crystal Field Theory", slug: "crystal-field-theory" },
      { name: "Metallurgy", slug: "metallurgy" },
      { name: "Ionic Bonding", slug: "ionic-bonding" },
      { name: "Covalent Bonding", slug: "covalent-bonding" },
      { name: "Metallic Bonding", slug: "metallic-bonding" },
      { name: "Acids, Bases & Salts", slug: "acids-bases-salts" },
      { name: "Electrochemistry", slug: "electrochemistry" },
      { name: "Batteries & Fuel Cells", slug: "batteries-fuel-cells" },
      { name: "Corrosion", slug: "corrosion" },
      { name: "Solid State Chemistry", slug: "solid-state-chemistry" },
      { name: "Semiconductors", slug: "semiconductors" },
    ],
    'biochemistry': [
      { name: "Proteins & Amino Acids", slug: "proteins-amino-acids" },
      { name: "Carbohydrates", slug: "carbohydrates" },
      { name: "Lipids & Fats", slug: "lipids-fats" },
      { name: "Nucleic Acids (DNA/RNA)", slug: "nucleic-acids" },
      { name: "Enzymes", slug: "enzymes" },
      { name: "Metabolism", slug: "metabolism" },
      { name: "ATP & Energy", slug: "atp-energy" },
      { name: "Vitamins & Coenzymes", slug: "vitamins-coenzymes" },
      { name: "Hormones", slug: "hormones-biochem" },
      { name: "Photosynthesis Chemistry", slug: "photosynthesis-chemistry" },
      { name: "Cellular Respiration", slug: "cellular-respiration" },
      { name: "Fermentation", slug: "fermentation" },
    ],
    'analytical': [
      { name: "Spectroscopy", slug: "spectroscopy" },
      { name: "Chromatography", slug: "chromatography" },
      { name: "Mass Spectrometry", slug: "mass-spectrometry" },
      { name: "Titration", slug: "titration" },
      { name: "pH & Indicators", slug: "ph-indicators" },
      { name: "Qualitative Analysis", slug: "qualitative-analysis" },
      { name: "Quantitative Analysis", slug: "quantitative-analysis" },
      { name: "NMR Spectroscopy", slug: "nmr-spectroscopy" },
      { name: "X-Ray Crystallography", slug: "x-ray-crystallography" },
      { name: "Electrophoresis", slug: "electrophoresis" },
      { name: "Laboratory Techniques", slug: "lab-techniques" },
      { name: "Chemical Safety", slug: "chemical-safety" },
    ],
    'environmental': [
      { name: "Air Pollution Chemistry", slug: "air-pollution-chemistry" },
      { name: "Water Chemistry", slug: "water-chemistry" },
      { name: "Ozone Layer", slug: "ozone-layer" },
      { name: "Greenhouse Gases", slug: "greenhouse-gases" },
      { name: "Acid Rain", slug: "acid-rain" },
      { name: "Water Treatment", slug: "water-treatment" },
      { name: "Soil Chemistry", slug: "soil-chemistry" },
      { name: "Heavy Metal Pollution", slug: "heavy-metal-pollution" },
      { name: "Pesticides & Herbicides", slug: "pesticides-herbicides" },
      { name: "Green Chemistry", slug: "green-chemistry" },
      { name: "Bioremediation", slug: "bioremediation" },
      { name: "Carbon Cycle", slug: "carbon-cycle" },
    ],
    'materials': [
      { name: "Ceramics", slug: "ceramics" },
      { name: "Polymers & Composites", slug: "polymers-composites" },
      { name: "Nanomaterials", slug: "nanomaterials" },
      { name: "Superconductors", slug: "superconductors" },
      { name: "Alloys", slug: "alloys" },
      { name: "Glass & Silicates", slug: "glass-silicates" },
      { name: "Carbon Materials", slug: "carbon-materials" },
      { name: "Graphene", slug: "graphene" },
      { name: "Biomaterials", slug: "biomaterials" },
      { name: "Smart Materials", slug: "smart-materials" },
      { name: "Liquid Crystals", slug: "liquid-crystals" },
      { name: "3D Printing Materials", slug: "3d-printing-materials" },
    ],
  },

  'biology': {
    'cell-biology': [
      { name: "Cell Structure", slug: "cell-structure" },
      { name: "Organelles", slug: "organelles" },
      { name: "Cell Membrane", slug: "cell-membrane" },
      { name: "Mitosis & Meiosis", slug: "mitosis-meiosis" },
      { name: "Cell Cycle", slug: "cell-cycle" },
      { name: "Prokaryotes vs Eukaryotes", slug: "prokaryotes-eukaryotes" },
      { name: "Stem Cells", slug: "stem-cells" },
      { name: "Cell Signaling", slug: "cell-signaling" },
      { name: "Apoptosis", slug: "apoptosis" },
      { name: "Cell Transport", slug: "cell-transport" },
      { name: "Cytoskeleton", slug: "cytoskeleton" },
      { name: "Endoplasmic Reticulum", slug: "endoplasmic-reticulum" },
    ],
    'genetics': [
      { name: "DNA Structure & Replication", slug: "dna-replication" },
      { name: "Mendelian Genetics", slug: "mendelian-genetics" },
      { name: "Gene Expression", slug: "gene-expression" },
      { name: "Mutations", slug: "mutations" },
      { name: "Genetic Engineering", slug: "genetic-engineering" },
      { name: "CRISPR", slug: "crispr" },
      { name: "Human Genome Project", slug: "human-genome-project" },
      { name: "Heredity & Inheritance", slug: "heredity-inheritance" },
      { name: "Chromosomes", slug: "chromosomes" },
      { name: "Genetic Disorders", slug: "genetic-disorders" },
      { name: "Epigenetics", slug: "epigenetics" },
      { name: "Population Genetics", slug: "population-genetics" },
    ],
    'evolution': [
      { name: "Darwin's Theory", slug: "darwins-theory" },
      { name: "Natural Selection", slug: "natural-selection" },
      { name: "Speciation", slug: "speciation" },
      { name: "Fossil Evidence", slug: "fossil-evidence" },
      { name: "Human Evolution", slug: "human-evolution" },
      { name: "Evolutionary Trees", slug: "evolutionary-trees" },
      { name: "Adaptation", slug: "adaptation" },
      { name: "Convergent Evolution", slug: "convergent-evolution" },
      { name: "Mass Extinctions", slug: "mass-extinctions" },
      { name: "Origin of Life", slug: "origin-of-life" },
      { name: "Molecular Evolution", slug: "molecular-evolution" },
      { name: "Coevolution", slug: "coevolution" },
    ],
    'human-body': [
      { name: "Circulatory System", slug: "circulatory-system" },
      { name: "Respiratory System", slug: "respiratory-system" },
      { name: "Digestive System", slug: "digestive-system" },
      { name: "Nervous System", slug: "nervous-system" },
      { name: "Skeletal System", slug: "skeletal-system" },
      { name: "Muscular System", slug: "muscular-system" },
      { name: "Endocrine System", slug: "endocrine-system" },
      { name: "Immune System", slug: "immune-system" },
      { name: "Reproductive System", slug: "reproductive-system" },
      { name: "Excretory System", slug: "excretory-system" },
      { name: "Integumentary System (Skin)", slug: "integumentary-system" },
      { name: "Lymphatic System", slug: "lymphatic-system" },
    ],
    'microbiology': [
      { name: "Bacteria", slug: "bacteria" },
      { name: "Viruses", slug: "viruses" },
      { name: "Fungi", slug: "fungi-micro" },
      { name: "Protozoa", slug: "protozoa" },
      { name: "Microbiome", slug: "microbiome" },
      { name: "Antibiotics", slug: "antibiotics" },
      { name: "Vaccines", slug: "vaccines" },
      { name: "Infectious Diseases", slug: "infectious-diseases" },
      { name: "Epidemiology", slug: "epidemiology" },
      { name: "Prions", slug: "prions" },
      { name: "Pathogenic Microorganisms", slug: "pathogens" },
      { name: "Microbial Ecology", slug: "microbial-ecology" },
    ],
    'ecology': [
      { name: "Food Chains & Webs", slug: "food-chains" },
      { name: "Ecosystems", slug: "ecosystems-bio" },
      { name: "Biomes", slug: "biomes" },
      { name: "Population Dynamics", slug: "population-dynamics" },
      { name: "Symbiosis", slug: "symbiosis" },
      { name: "Biodiversity", slug: "biodiversity" },
      { name: "Conservation Biology", slug: "conservation-biology" },
      { name: "Invasive Species", slug: "invasive-species" },
      { name: "Nutrient Cycles", slug: "nutrient-cycles" },
      { name: "Ecological Succession", slug: "ecological-succession" },
      { name: "Keystone Species", slug: "keystone-species" },
      { name: "Habitat Destruction", slug: "habitat-destruction" },
    ],
    'neuroscience': [
      { name: "Brain Anatomy", slug: "brain-anatomy" },
      { name: "Neurons & Synapses", slug: "neurons-synapses" },
      { name: "Neurotransmitters", slug: "neurotransmitters" },
      { name: "Memory", slug: "memory-neuro" },
      { name: "Learning & Plasticity", slug: "learning-plasticity" },
      { name: "Sleep & Dreams", slug: "sleep-dreams" },
      { name: "Consciousness", slug: "consciousness" },
      { name: "Brain Disorders", slug: "brain-disorders" },
      { name: "Sensory Systems", slug: "sensory-systems" },
      { name: "Motor Control", slug: "motor-control" },
      { name: "Brain Imaging", slug: "brain-imaging" },
      { name: "Neuroplasticity", slug: "neuroplasticity" },
    ],
    'molecular': [
      { name: "Protein Synthesis", slug: "protein-synthesis" },
      { name: "Transcription", slug: "transcription" },
      { name: "Translation", slug: "translation" },
      { name: "RNA Types", slug: "rna-types" },
      { name: "Gene Regulation", slug: "gene-regulation" },
      { name: "Recombinant DNA", slug: "recombinant-dna" },
      { name: "PCR", slug: "pcr" },
      { name: "Gel Electrophoresis", slug: "gel-electrophoresis" },
      { name: "Cloning", slug: "cloning" },
      { name: "Proteomics", slug: "proteomics" },
      { name: "Genomics", slug: "genomics" },
      { name: "Bioinformatics", slug: "bioinformatics" },
    ],
  },

  'space': {
    'astronomy': [
      { name: "Constellations", slug: "constellations" },
      { name: "Types of Stars", slug: "types-of-stars" },
      { name: "Star Life Cycle", slug: "star-life-cycle" },
      { name: "Binary Stars", slug: "binary-stars" },
      { name: "Variable Stars", slug: "variable-stars" },
      { name: "Messier Objects", slug: "messier-objects" },
      { name: "Deep Sky Objects", slug: "deep-sky-objects" },
      { name: "Astronomical Units", slug: "astronomical-units" },
      { name: "Celestial Coordinates", slug: "celestial-coordinates" },
      { name: "Amateur Astronomy", slug: "amateur-astronomy" },
      { name: "Night Sky Phenomena", slug: "night-sky-phenomena" },
      { name: "Famous Astronomers", slug: "famous-astronomers" },
    ],
    'planets': [
      { name: "Mercury", slug: "mercury-planet" },
      { name: "Venus", slug: "venus-planet" },
      { name: "Earth", slug: "earth-planet" },
      { name: "Mars", slug: "mars-planet" },
      { name: "Jupiter", slug: "jupiter-planet" },
      { name: "Saturn", slug: "saturn-planet" },
      { name: "Uranus", slug: "uranus-planet" },
      { name: "Neptune", slug: "neptune-planet" },
      { name: "Dwarf Planets", slug: "dwarf-planets" },
      { name: "Pluto", slug: "pluto" },
      { name: "Planetary Moons", slug: "planetary-moons" },
      { name: "Planetary Rings", slug: "planetary-rings" },
    ],
    'solar-system': [
      { name: "The Sun", slug: "the-sun" },
      { name: "Asteroid Belt", slug: "asteroid-belt" },
      { name: "Kuiper Belt", slug: "kuiper-belt" },
      { name: "Oort Cloud", slug: "oort-cloud" },
      { name: "Comets", slug: "comets" },
      { name: "Meteors & Meteorites", slug: "meteors-meteorites" },
      { name: "Solar System Formation", slug: "solar-system-formation" },
      { name: "Trans-Neptunian Objects", slug: "trans-neptunian-objects" },
      { name: "Solar Wind", slug: "solar-wind" },
      { name: "Heliosphere", slug: "heliosphere" },
      { name: "Eclipses", slug: "eclipses" },
      { name: "Planetary Alignment", slug: "planetary-alignment" },
    ],
    'galaxies': [
      { name: "Milky Way", slug: "milky-way" },
      { name: "Andromeda Galaxy", slug: "andromeda-galaxy" },
      { name: "Galaxy Types", slug: "galaxy-types" },
      { name: "Galaxy Formation", slug: "galaxy-formation" },
      { name: "Galaxy Clusters", slug: "galaxy-clusters" },
      { name: "Active Galactic Nuclei", slug: "active-galactic-nuclei" },
      { name: "Local Group", slug: "local-group" },
      { name: "Supermassive Black Holes", slug: "supermassive-black-holes" },
      { name: "Galactic Collisions", slug: "galactic-collisions" },
      { name: "Dark Matter in Galaxies", slug: "dark-matter-galaxies" },
      { name: "Spiral Arms", slug: "spiral-arms" },
      { name: "Observable Universe", slug: "observable-universe" },
    ],
    'exploration': [
      { name: "Apollo Program", slug: "apollo-program" },
      { name: "Mars Rovers", slug: "mars-rovers" },
      { name: "Voyager Missions", slug: "voyager-missions" },
      { name: "Hubble Space Telescope", slug: "hubble-telescope" },
      { name: "James Webb Telescope", slug: "james-webb-telescope" },
      { name: "International Space Station", slug: "iss" },
      { name: "Space Shuttle Program", slug: "space-shuttle" },
      { name: "SpaceX", slug: "spacex" },
      { name: "NASA Missions", slug: "nasa-missions" },
      { name: "Future Mars Missions", slug: "future-mars-missions" },
      { name: "Moon Landing", slug: "moon-landing" },
      { name: "Space Race", slug: "space-race" },
    ],
    'astronauts': [
      { name: "Neil Armstrong", slug: "neil-armstrong" },
      { name: "Buzz Aldrin", slug: "buzz-aldrin" },
      { name: "Yuri Gagarin", slug: "yuri-gagarin" },
      { name: "Sally Ride", slug: "sally-ride" },
      { name: "Chris Hadfield", slug: "chris-hadfield" },
      { name: "Kalpana Chawla", slug: "kalpana-chawla" },
      { name: "John Glenn", slug: "john-glenn" },
      { name: "Valentina Tereshkova", slug: "valentina-tereshkova" },
      { name: "Spacewalks", slug: "spacewalks" },
      { name: "Astronaut Training", slug: "astronaut-training" },
      { name: "Living in Space", slug: "living-in-space" },
      { name: "Space Disasters", slug: "space-disasters" },
    ],
    'black-holes': [
      { name: "Black Hole Formation", slug: "black-hole-formation" },
      { name: "Event Horizon", slug: "event-horizon" },
      { name: "Schwarzschild Radius", slug: "schwarzschild-radius" },
      { name: "Singularity", slug: "singularity" },
      { name: "Spaghettification", slug: "spaghettification" },
      { name: "Black Hole Imaging", slug: "black-hole-imaging" },
      { name: "Stellar Black Holes", slug: "stellar-black-holes" },
      { name: "Primordial Black Holes", slug: "primordial-black-holes" },
      { name: "White Holes", slug: "white-holes" },
      { name: "Wormholes", slug: "wormholes" },
      { name: "Information Paradox", slug: "information-paradox" },
      { name: "Famous Black Holes", slug: "famous-black-holes" },
    ],
    'cosmology': [
      { name: "Big Bang Theory", slug: "big-bang" },
      { name: "Expansion of Universe", slug: "universe-expansion" },
      { name: "Cosmic Inflation", slug: "cosmic-inflation" },
      { name: "Age of the Universe", slug: "age-of-universe" },
      { name: "Fate of the Universe", slug: "fate-of-universe" },
      { name: "Multiverse Theory", slug: "multiverse" },
      { name: "Cosmic Microwave Background", slug: "cosmic-microwave-bg" },
      { name: "Dark Energy", slug: "dark-energy-cosmology" },
      { name: "Hubble Constant", slug: "hubble-constant" },
      { name: "Cosmological Principle", slug: "cosmological-principle" },
      { name: "Steady State Theory", slug: "steady-state-theory" },
      { name: "Anthropic Principle", slug: "anthropic-principle" },
    ],
  },

  'environment': {
    'climate': [
      { name: "Global Warming", slug: "global-warming" },
      { name: "Climate Change Science", slug: "climate-change-science" },
      { name: "Ice Ages", slug: "ice-ages" },
      { name: "El Niño & La Niña", slug: "el-nino-la-nina" },
      { name: "Climate Models", slug: "climate-models" },
      { name: "IPCC Reports", slug: "ipcc-reports" },
      { name: "Paris Agreement", slug: "paris-agreement" },
      { name: "Carbon Footprint", slug: "carbon-footprint" },
      { name: "Sea Level Rise", slug: "sea-level-rise" },
      { name: "Arctic & Antarctic Ice", slug: "polar-ice" },
      { name: "Climate Tipping Points", slug: "climate-tipping-points" },
      { name: "Climate History", slug: "climate-history" },
    ],
    'geology': [
      { name: "Plate Tectonics", slug: "plate-tectonics" },
      { name: "Earthquakes", slug: "earthquakes" },
      { name: "Volcanoes", slug: "volcanoes" },
      { name: "Rock Types", slug: "rock-types" },
      { name: "Minerals", slug: "minerals" },
      { name: "Fossils", slug: "fossils" },
      { name: "Geological Time Scale", slug: "geological-time-scale" },
      { name: "Mountain Formation", slug: "mountain-formation" },
      { name: "Continental Drift", slug: "continental-drift" },
      { name: "Earth's Layers", slug: "earths-layers" },
      { name: "Geothermal Energy", slug: "geothermal-energy" },
      { name: "Caves & Karst", slug: "caves-karst" },
    ],
    'weather': [
      { name: "Weather Patterns", slug: "weather-patterns" },
      { name: "Hurricanes & Cyclones", slug: "hurricanes-cyclones" },
      { name: "Tornadoes", slug: "tornadoes" },
      { name: "Thunderstorms", slug: "thunderstorms" },
      { name: "Atmospheric Layers", slug: "atmospheric-layers" },
      { name: "Weather Forecasting", slug: "weather-forecasting" },
      { name: "Clouds", slug: "clouds" },
      { name: "Precipitation", slug: "precipitation" },
      { name: "Wind Patterns", slug: "wind-patterns" },
      { name: "Monsoons", slug: "monsoons" },
      { name: "Blizzards", slug: "blizzards" },
      { name: "Heat Waves & Droughts", slug: "heat-waves-droughts" },
    ],
    'oceans': [
      { name: "Ocean Currents", slug: "ocean-currents" },
      { name: "Ocean Zones", slug: "ocean-zones" },
      { name: "Coral Reefs", slug: "coral-reefs" },
      { name: "Ocean Acidification", slug: "ocean-acidification" },
      { name: "Deep Sea Ecosystems", slug: "deep-sea-ecosystems" },
      { name: "Tides", slug: "tides" },
      { name: "Marine Pollution", slug: "marine-pollution" },
      { name: "Overfishing", slug: "overfishing" },
      { name: "The Great Pacific Garbage Patch", slug: "pacific-garbage-patch" },
      { name: "Hydrothermal Vents", slug: "hydrothermal-vents" },
      { name: "Ocean Exploration", slug: "ocean-exploration" },
      { name: "Mariana Trench", slug: "mariana-trench" },
    ],
    'conservation': [
      { name: "Endangered Species", slug: "endangered-species" },
      { name: "Wildlife Conservation", slug: "wildlife-conservation" },
      { name: "National Parks", slug: "national-parks" },
      { name: "Marine Protected Areas", slug: "marine-protected-areas" },
      { name: "Deforestation", slug: "deforestation" },
      { name: "Reforestation", slug: "reforestation" },
      { name: "Species Extinction", slug: "species-extinction" },
      { name: "Conservation Success Stories", slug: "conservation-success" },
      { name: "Poaching & Illegal Trade", slug: "poaching-illegal-trade" },
      { name: "Habitat Restoration", slug: "habitat-restoration" },
      { name: "Zoos & Breeding Programs", slug: "zoos-breeding" },
      { name: "Conservation Organizations", slug: "conservation-orgs" },
    ],
    'renewable': [
      { name: "Solar Energy", slug: "solar-energy" },
      { name: "Wind Energy", slug: "wind-energy" },
      { name: "Hydroelectric Power", slug: "hydroelectric-power" },
      { name: "Geothermal Power", slug: "geothermal-power" },
      { name: "Tidal & Wave Energy", slug: "tidal-wave-energy" },
      { name: "Biomass Energy", slug: "biomass-energy" },
      { name: "Nuclear Energy Debate", slug: "nuclear-energy-debate" },
      { name: "Electric Vehicles", slug: "electric-vehicles" },
      { name: "Energy Storage", slug: "energy-storage" },
      { name: "Smart Grids", slug: "smart-grids" },
      { name: "Hydrogen Fuel", slug: "hydrogen-fuel" },
      { name: "Net Zero Goals", slug: "net-zero-goals" },
    ],
    'disasters': [
      { name: "Tsunami", slug: "tsunami" },
      { name: "Volcanic Eruptions", slug: "volcanic-eruptions" },
      { name: "Major Earthquakes", slug: "major-earthquakes" },
      { name: "Floods", slug: "floods" },
      { name: "Wildfires", slug: "wildfires" },
      { name: "Landslides", slug: "landslides" },
      { name: "Disaster Preparedness", slug: "disaster-preparedness" },
      { name: "Historic Natural Disasters", slug: "historic-disasters" },
      { name: "2004 Indian Ocean Tsunami", slug: "2004-tsunami" },
      { name: "Hurricane Katrina", slug: "hurricane-katrina" },
      { name: "Disaster Response", slug: "disaster-response" },
      { name: "Climate-Related Disasters", slug: "climate-disasters" },
    ],
  },

  'animals': {
    'mammals': [
      { name: "Elephants", slug: "elephants" },
      { name: "Lions", slug: "lions" },
      { name: "Tigers", slug: "tigers" },
      { name: "Bears", slug: "bears" },
      { name: "Wolves", slug: "wolves" },
      { name: "Whales", slug: "whales" },
      { name: "Dolphins", slug: "dolphins" },
      { name: "Primates", slug: "primates" },
      { name: "Big Cats", slug: "big-cats" },
      { name: "Marsupials", slug: "marsupials" },
      { name: "Bats", slug: "bats" },
      { name: "Rodents", slug: "rodents" },
    ],
    'birds': [
      { name: "Eagles & Hawks", slug: "eagles-hawks" },
      { name: "Owls", slug: "owls" },
      { name: "Penguins", slug: "penguins" },
      { name: "Parrots", slug: "parrots" },
      { name: "Hummingbirds", slug: "hummingbirds" },
      { name: "Flamingos", slug: "flamingos" },
      { name: "Bird Migration", slug: "bird-migration" },
      { name: "Flightless Birds", slug: "flightless-birds" },
      { name: "Songbirds", slug: "songbirds" },
      { name: "Waterfowl", slug: "waterfowl" },
      { name: "Bird Intelligence", slug: "bird-intelligence" },
      { name: "Extinct Birds", slug: "extinct-birds" },
    ],
    'marine-life': [
      { name: "Sharks", slug: "sharks" },
      { name: "Sea Turtles", slug: "sea-turtles" },
      { name: "Octopuses", slug: "octopuses" },
      { name: "Jellyfish", slug: "jellyfish" },
      { name: "Coral", slug: "coral" },
      { name: "Deep Sea Creatures", slug: "deep-sea-creatures" },
      { name: "Tropical Fish", slug: "tropical-fish" },
      { name: "Seals & Sea Lions", slug: "seals-sea-lions" },
      { name: "Rays", slug: "rays" },
      { name: "Crustaceans", slug: "crustaceans" },
      { name: "Mollusks", slug: "mollusks" },
      { name: "Marine Mammals", slug: "marine-mammals" },
    ],
    'reptiles': [
      { name: "Snakes", slug: "snakes" },
      { name: "Crocodiles & Alligators", slug: "crocodiles-alligators" },
      { name: "Lizards", slug: "lizards" },
      { name: "Tortoises & Turtles", slug: "tortoises-turtles" },
      { name: "Komodo Dragon", slug: "komodo-dragon" },
      { name: "Geckos", slug: "geckos" },
      { name: "Chameleons", slug: "chameleons" },
      { name: "Iguanas", slug: "iguanas" },
      { name: "Venomous Reptiles", slug: "venomous-reptiles" },
      { name: "Frogs & Toads", slug: "frogs-toads" },
      { name: "Salamanders", slug: "salamanders" },
      { name: "Amphibian Life Cycle", slug: "amphibian-life-cycle" },
    ],
    'insects': [
      { name: "Butterflies & Moths", slug: "butterflies-moths" },
      { name: "Bees", slug: "bees" },
      { name: "Ants", slug: "ants" },
      { name: "Beetles", slug: "beetles" },
      { name: "Spiders", slug: "spiders" },
      { name: "Dragonflies", slug: "dragonflies" },
      { name: "Grasshoppers & Crickets", slug: "grasshoppers-crickets" },
      { name: "Flies", slug: "flies" },
      { name: "Termites", slug: "termites" },
      { name: "Mosquitoes", slug: "mosquitoes" },
      { name: "Insect Colonies", slug: "insect-colonies" },
      { name: "Metamorphosis", slug: "metamorphosis" },
    ],
    'endangered': [
      { name: "Giant Panda", slug: "giant-panda" },
      { name: "Mountain Gorilla", slug: "mountain-gorilla" },
      { name: "Bengal Tiger", slug: "bengal-tiger" },
      { name: "Black Rhino", slug: "black-rhino" },
      { name: "Blue Whale", slug: "blue-whale" },
      { name: "Snow Leopard", slug: "snow-leopard" },
      { name: "Orangutan", slug: "orangutan" },
      { name: "African Elephant", slug: "african-elephant" },
      { name: "Sea Otter", slug: "sea-otter" },
      { name: "Red Panda", slug: "red-panda" },
      { name: "Polar Bear", slug: "polar-bear" },
      { name: "IUCN Red List", slug: "iucn-red-list" },
    ],
    'behavior': [
      { name: "Animal Communication", slug: "animal-communication" },
      { name: "Migration Patterns", slug: "migration-patterns" },
      { name: "Hibernation", slug: "hibernation" },
      { name: "Mating Rituals", slug: "mating-rituals" },
      { name: "Predator-Prey Relationships", slug: "predator-prey" },
      { name: "Animal Intelligence", slug: "animal-intelligence" },
      { name: "Social Structures", slug: "social-structures-animals" },
      { name: "Camouflage", slug: "camouflage" },
      { name: "Nocturnal Animals", slug: "nocturnal-animals" },
      { name: "Animal Tools", slug: "animal-tools" },
      { name: "Pack Hunting", slug: "pack-hunting" },
      { name: "Parental Care", slug: "parental-care" },
    ],
    'prehistoric': [
      { name: "Dinosaurs", slug: "dinosaurs" },
      { name: "T-Rex", slug: "t-rex" },
      { name: "Velociraptors", slug: "velociraptors" },
      { name: "Pterosaurs", slug: "pterosaurs" },
      { name: "Marine Reptiles", slug: "marine-reptiles" },
      { name: "Mammoths", slug: "mammoths" },
      { name: "Saber-Toothed Cats", slug: "saber-toothed-cats" },
      { name: "Ice Age Megafauna", slug: "ice-age-megafauna" },
      { name: "Dinosaur Extinction", slug: "dinosaur-extinction" },
      { name: "Fossil Discovery", slug: "fossil-discovery" },
      { name: "Jurassic Period", slug: "jurassic-period" },
      { name: "Cretaceous Period", slug: "cretaceous-period" },
    ],
  },

  'plants': {
    'botany': [
      { name: "Plant Cell Structure", slug: "plant-cell-structure" },
      { name: "Photosynthesis", slug: "photosynthesis" },
      { name: "Plant Reproduction", slug: "plant-reproduction" },
      { name: "Plant Anatomy", slug: "plant-anatomy" },
      { name: "Roots, Stems & Leaves", slug: "roots-stems-leaves" },
      { name: "Plant Hormones", slug: "plant-hormones" },
      { name: "Transpiration", slug: "transpiration" },
      { name: "Pollination", slug: "pollination" },
      { name: "Seed Germination", slug: "seed-germination" },
      { name: "Plant Classification", slug: "plant-classification" },
      { name: "Tropisms", slug: "tropisms" },
      { name: "Plant Adaptations", slug: "plant-adaptations" },
    ],
    'flowers': [
      { name: "Roses", slug: "roses" },
      { name: "Orchids", slug: "orchids" },
      { name: "Tulips", slug: "tulips" },
      { name: "Sunflowers", slug: "sunflowers" },
      { name: "Lilies", slug: "lilies" },
      { name: "Cherry Blossoms", slug: "cherry-blossoms" },
      { name: "Lotus", slug: "lotus" },
      { name: "Carnivorous Plants", slug: "carnivorous-plants" },
      { name: "Flower Anatomy", slug: "flower-anatomy" },
      { name: "National Flowers", slug: "national-flowers" },
      { name: "Flower Symbolism", slug: "flower-symbolism" },
      { name: "Rare Flowers", slug: "rare-flowers" },
    ],
    'trees': [
      { name: "Oak Trees", slug: "oak-trees" },
      { name: "Redwoods & Sequoias", slug: "redwoods-sequoias" },
      { name: "Pine Trees", slug: "pine-trees" },
      { name: "Maple Trees", slug: "maple-trees" },
      { name: "Baobab Trees", slug: "baobab-trees" },
      { name: "Palm Trees", slug: "palm-trees" },
      { name: "Rainforest Trees", slug: "rainforest-trees" },
      { name: "Deciduous vs Evergreen", slug: "deciduous-evergreen" },
      { name: "Oldest Trees", slug: "oldest-trees" },
      { name: "Tree Rings", slug: "tree-rings" },
      { name: "Deforestation Impact", slug: "deforestation-impact" },
      { name: "Urban Trees", slug: "urban-trees" },
    ],
    'crops': [
      { name: "Wheat", slug: "wheat" },
      { name: "Rice", slug: "rice" },
      { name: "Corn/Maize", slug: "corn-maize" },
      { name: "Soybeans", slug: "soybeans" },
      { name: "Cotton", slug: "cotton" },
      { name: "Coffee", slug: "coffee-plant" },
      { name: "Tea", slug: "tea-plant" },
      { name: "Sugarcane", slug: "sugarcane" },
      { name: "Potatoes", slug: "potatoes" },
      { name: "GMO Crops", slug: "gmo-crops" },
      { name: "Sustainable Agriculture", slug: "sustainable-agriculture" },
      { name: "Crop Rotation", slug: "crop-rotation" },
    ],
    'fungi': [
      { name: "Mushroom Types", slug: "mushroom-types" },
      { name: "Edible Mushrooms", slug: "edible-mushrooms" },
      { name: "Poisonous Mushrooms", slug: "poisonous-mushrooms" },
      { name: "Fungi Life Cycle", slug: "fungi-life-cycle" },
      { name: "Mycorrhizae", slug: "mycorrhizae" },
      { name: "Yeast", slug: "yeast" },
      { name: "Mold", slug: "mold" },
      { name: "Medicinal Fungi", slug: "medicinal-fungi" },
      { name: "Fungal Diseases", slug: "fungal-diseases" },
      { name: "Decomposers", slug: "decomposers" },
      { name: "Truffle", slug: "truffle" },
      { name: "Lichens", slug: "lichens" },
    ],
    'medicinal': [
      { name: "Aloe Vera", slug: "aloe-vera" },
      { name: "Ginseng", slug: "ginseng" },
      { name: "Turmeric", slug: "turmeric" },
      { name: "Echinacea", slug: "echinacea" },
      { name: "Lavender", slug: "lavender" },
      { name: "Ginger", slug: "ginger" },
      { name: "Chamomile", slug: "chamomile" },
      { name: "Eucalyptus", slug: "eucalyptus" },
      { name: "Neem", slug: "neem" },
      { name: "Ayurvedic Plants", slug: "ayurvedic-plants" },
      { name: "Traditional Chinese Medicine Plants", slug: "tcm-plants" },
      { name: "Pharmaceutical Plants", slug: "pharmaceutical-plants" },
    ],
  },
};

let added = 0;
let skipped = 0;

for (const [category, subcategories] of Object.entries(science)) {
  console.log(`\n=== ${category.toUpperCase()} ===`);

  for (const [subcategory, topics] of Object.entries(subcategories)) {
    console.log(`\n${subcategory}:`);

    for (const topic of topics) {
      if (existingSlugs.has(topic.slug)) {
        skipped++;
        continue;
      }

      ensureTopic({
        category,
        subcategory,
        slug: topic.slug,
        name: topic.name,
        source_type: 'wikipedia',
      });

      console.log(`  + ${topic.name}`);
      added++;
      existingSlugs.add(topic.slug);
    }
  }
}

console.log(`\n✓ Added: ${added} topics`);
console.log(`- Skipped: ${skipped} (already exist)`);

// Final counts
const allScienceTopics = [
  ...getTopics('physics'),
  ...getTopics('chemistry'),
  ...getTopics('biology'),
  ...getTopics('space'),
  ...getTopics('environment'),
  ...getTopics('animals'),
  ...getTopics('plants'),
];
console.log(`\nTotal science topics: ${allScienceTopics.length}`);
